### ISSUE TITLE
Clicking pagination buttons throws server error in Alerts page

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#1002]
Found in version 0.11-pre10

Preconditions:
There are more than ten Alerts.
The Alerts listing displays 10 rows per page.

Reproduce steps:
Navigate to Alerts listing.
Click on the arrow to navigate to the next page.

Actual result:
A server error is thrown.
The following error is logged in the browser console:
```application-03fa5a3….js:27 GET http://cdx-stg.instedd.org/alerts?context=1f5b45d5-81d2-e63a-35ce-378a59acdcbb-%2A&page=2 500 (Internal Server Error)S @ application-03fa5a3….js:27E @ application-03fa5a3….js:27t @ application-03fa5a3….js:27t.handle @ application-03fa5a3….js:27
application-03fa5a3….js:27 GET http://cdx-stg.instedd.org/alerts?context=1f5b45d5-81d2-e63a-35ce-378a59acdcbb-%2A&page=2 500 (Internal Server Error)et.onload @ application-03fa5a3….js:27```

Poirot log:
http://poirot-stg2.instedd.org/activities/2016-03-22/6fcd36be-7c41-242e-d70d-f4b34270e731

Additional info:
The same issue happens when changing the number of items displayed per page

**Comment by nekron** [comment]
The issue is not in the pagination but when trying to display multiple sites names selected for an alert.

**Comment by mmuller** [comment]
Ok in version 0.11-pre10

**Comment by anthonyoleary** [comment]
I could not reproduce this, can it be tested/closed?

git clone https://github.com/instedd/cdx.git -b release/0.11
i created 12 alerts, click the next page, also view 50 alerts per page , and no error generated, it was all ok.

**Comment by nekron** [comment]
This has already been fixed and verified.
