### ISSUE TITLE
Update manifests and samples for Alere Q devices

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#1014]
- [x] Support parsing [this sample file](https://github.com/instedd/cdx/files/193907/01-02_NAT-04000443_2016-03-29-13-24-39.csv.zip). Adjust the pattern to match the file name.

- [x] Add the following custom fields to the Alere Q manifest:
 - Sample Detection 
 - Device
 - HIV-1 Positive Control
 - HIV-2 Positive Control
 - Negative Control
 - Analysis
 - Device Software

- [ ] Set test.type to specimen

**Comment by pmallol** [comment]
Ok in Version: 0.12-pre2
