### ISSUE TITLE
Results send from GeneXpert devices show incorrect results in CDx

### ISSUE THREAD

**Issue by cisaacs01** [instedd/cdx#1016]
**Reproduce**
http://cdx-stg.instedd.org/

- Navigate to FIND Geneva institution (site 1)
- Observe 330 test results sent from device FINDGX serial 801593
- See attached export file from same device

**Expected**

- Result types to match output of GX device i.e. ‘MTB Trace’, ‘MTB detected medium’ or ‘RIF indeterminate’
- Positive detections to be marked

**Actual**
In some cases where device has reported RIF resistance - CDx shows as negative
Sample ID MDR2_180316 is one such example
[FINDGX.zip](https://github.com/instedd/cdx/files/195968/FINDGX.zip)

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre13
