### ISSUE TITLE
Filter by QC samples in results list

### ISSUE THREAD

**Issue by cisaacs01** [instedd/cdx#1018]
Currently all QC samples are showing in the test results list. 

![image](https://cloud.githubusercontent.com/assets/2486669/14168278/b290b534-f721-11e5-9e7d-6aa181a454d6.png)

![image](https://cloud.githubusercontent.com/assets/2486669/14168284/be7b47f6-f721-11e5-84aa-2540e0f35fdc.png)

**Comment by nekron** [comment]
Actually there is a filter in the expanded section that allows you to filter by the test type: "specimen", "qc", and "all", with this last one selected by default.

<img width="1585" alt="screen shot 2016-03-31 at 10 08 20 am" src="https://cloud.githubusercontent.com/assets/957103/14176971/2eb8935e-f72a-11e5-8f70-930c682b7fb6.png">

We can add this to the list of things that should be visible in the table itself: https://github.com/instedd/cdx/issues/1017#issuecomment-203933901
