### ISSUE TITLE
Ad-hoc users are not being saved in the Alert view

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#1019]
Found in version 0.11-pre12.

Reproduce steps:
Navigate to the Alerts page.
Create an Alert.
Fill the 'Ad-hoc recipient' fields.
Press 'Create user'.
Press 'Save.'
Refresh the page.

Actual result:
The new user doesn't persist in the Alert form.
When the Alert is triggered the new user doesn't receive an alert email.  

Expected:
The new user should be displayed in the Alert form.
When the Alert is triggered the new user should receive an alert email.  

![screen shot 2016-04-01 at 1 51 35 pm](https://cloud.githubusercontent.com/assets/518152/14213972/fc5aa770-f810-11e5-8c00-02b68d802107.png)

**Comment by vtiffenberg** [comment]
The user is still there after creation. It disappears on update.

**Comment by anthonyoleary** [comment]
fixed https://github.com/instedd/cdx/issues/1019 in this pull request:
https://github.com/instedd/cdx/pull/1024

Found and fixed a issue whereby the flash message was not displayed on updated.

There is a UI issue when the left column sites are displayed, the ad hoc user fields do not look good.

**Comment by mmuller** [comment]
Ok in version 0.11-pre13
