### ISSUE TITLE
Logs should be displayed in descending order of timestamp.

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#1020]
Found in version 0.11-pre12

Now the oldest Logs are placed on the top and this sorting cannot be changed. 

![screen shot 2016-04-01 at 6 58 43 pm](https://cloud.githubusercontent.com/assets/518152/14221251/db3e5034-f83b-11e5-94d8-3f800945ef40.png)

**Comment by anthonyoleary** [comment]
@mmuller , hi, could we change the sorting order in:  class DeviceMessagesController < ApplicationController, def index   ,   change the SQL asc/desc order? [I guess people want to see the latest logs first]

**Comment by nekron** [comment]
Yes. Please change the order.

**Comment by anthonyoleary** [comment]
anthony: I will work on this.

**Comment by anthonyoleary** [comment]
Did a pull request, branch hotfix/device_messages_order for this.

**Comment by mmuller** [comment]
Ok in version 0.11-pre15
