### ISSUE TITLE
Custom roles are not working properly

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#1022]
Found in Version: 0.11-pre12

As Institution Admin:
1. Navigate to 'Roles' under Settings.
2. Click on button to create new reader Role:
3. In Policy select 'Institution' as Type, and 'All' as Action. Check 'Include subsites'. Save the form.
4. Navigate to 'Users' and create a new user 'Foo' assigning the reader Role.
5. Navigate to 'Policies' and add another Policy: select 'Patient' as Type, and 'Read' as Action. Check 'Include subsites'. Save the form.

As Reader user 'Foo':
1. Open CDx

Obtained:
The user 'Foo' cannot access to Patients listing belonging to the Institution.

Expected:
User 'Foo' should be able to read the Patients listing for the Institution its role belongs to.

Additional info:
The Patients page can be accessed via URL but the listing is empty.

![screen shot 2016-04-04 at 3 52 52 pm](https://cloud.githubusercontent.com/assets/518152/14259466/5d6e9ed6-fa7d-11e5-95ef-e4f251c2741d.png)
![screen shot 2016-04-04 at 3 52 21 pm](https://cloud.githubusercontent.com/assets/518152/14259467/5d7023aa-fa7d-11e5-90e9-366e26dd4a7e.png)
![screen shot 2016-04-04 at 3 52 03 pm](https://cloud.githubusercontent.com/assets/518152/14259465/5d6e7762-fa7d-11e5-8bd1-dd9f5d778270.png)
![screen shot 2016-04-04 at 3 51 56 pm](https://cloud.githubusercontent.com/assets/518152/14259469/5d71a310-fa7d-11e5-9155-96ca8120f6eb.png)
![screen shot 2016-04-04 at 3 51 50 pm](https://cloud.githubusercontent.com/assets/518152/14259468/5d709722-fa7d-11e5-9df9-21d743e0dcca.png)

**Comment by vtiffenberg** [comment]
Syntoms I was able to reproduce were not exactly as described. New user could see the patients listing in menu, but, as described, Patients menu was empty. 
Computed policies are not being updated on role update. So policies created after user creation are not applying

**Comment by pmallol** [comment]
User can read all Patients ok  in Version: 0.11-pre13
