### ISSUE TITLE
Home charts always display the data from the child sites

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#1027]
Steps to reproduce:
- Two sites are created, parent and child, with devices and tests in both.
- Select the parent site
- Unmark the "selection includes subsites"  checkbox

Expected:
- The charts only display data from the parent site devices.

Obtained:
- Tests from the child nodes are always displated

**Comment by anthonyoleary** [comment]
anthony is looking at this.

**Comment by anthonyoleary** [comment]
This has been fixed in the dashboard_reports branch.

**Comment by anthonyoleary** [comment]
Did a pull request for a fix against release/0.11 branch.

**Comment by mmuller** [comment]
Ok in version 0.11-pre15
