### ISSUE TITLE
"No incidents" message on Incidents section

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1066]
The message that discloses there are no incidents says, actually, that there _are_ incidents. It is a simple typo but it can generate confusion to users. See image for this issue attached, along with an image for the alert message to highlight the difference in approach, when both should be the same. 

![Screen Shot 2021-03-18 at 11 53 10 AM](https://user-images.githubusercontent.com/2902379/111615047-978daa80-87e0-11eb-9fbc-095a5ca1a3e6.png)

![Screen Shot 2021-03-18 at 11 48 03 AM](https://user-images.githubusercontent.com/2902379/111614933-77f68200-87e0-11eb-9e1b-0e43310164cd.png)

**Comment by diegoliberman** [comment]
This screen is reached from the Settings menu, with the Incidents link located in the Alert Groups box.

![image](https://user-images.githubusercontent.com/25181052/139721872-484dda6f-24d9-417e-89aa-b5091117dfb1.png)

**Comment by diegoliberman** [comment]
This looks like a very good first-ticket for a new dev.
