### ISSUE TITLE
Inconsistent behaviour when managing institutions

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1067]
There's some inconsistency in the way the UX is handled when managing institutions. 

When a user access the Institutions from the User Profile, having only 1 institution, they see this
![Screen Shot 2021-03-18 at 12 09 58 PM](https://user-images.githubusercontent.com/2902379/111617142-0e2ba780-87e3-11eb-8486-f1ffd69ff6e2.png)

After adding a second institution, this is what the profile looks like
![Screen Shot 2021-03-18 at 12 09 31 PM](https://user-images.githubusercontent.com/2902379/111617201-1e438700-87e3-11eb-947e-3032a583e07b.png)

However, if an institution is removed (regardless if there are 2 or more), the default screen turns to this
![Screen Shot 2021-03-18 at 12 09 20 PM](https://user-images.githubusercontent.com/2902379/111617290-36b3a180-87e3-11eb-8c12-1e13c8c980da.png)

**Comment by diegoliberman** [comment]
@gbatiston I can't reproduce this inconsistency.  For me, after creating the 2nd institution, I the the new UI with the list of institutions.  If you can't reproduce it again, I'd close this one.

**Comment by gbatiston** [comment]
I can't seem to reproduce this, and I did not do a good job at documenting how i got to it in the first place. I'm closing this for now.

**Comment by diegoliberman** [comment]
Work item deleted in Commit
