### ISSUE TITLE
Allow labs to attach files to sample

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1098]
After assays are run on samples, some results are provided in the form of image files; these files are then attached to the sample to prove the virus has been correctly inactivated. Images are also used to count viral load. 

File formats that _must_ supported: FASTA, genbank.

There is also information about the samples, such as the genomic sequence, that is of interest as well for the lab staff and they will provide via a file that would be attached to a sample. 

Ideally, we would explore the classic approaches to adding files: selecting or dragging&dropping (for which the customer expressed a strong desire). 

The files will be attached to a "parent" sample and the info should be shared at batch level for all samples that belong to the same batch.

**Comment by diegoliberman** [comment]
@gbatiston isn't this a duplicate of #1123?

**Comment by gbatiston** [comment]
Not quite, but this has already been covered by other tasks the team has worked on so we can close this one
