### ISSUE TITLE
Set sample as "Quality Control" 

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1113]
Allow users to set a sample as Quality Control, to identify the sample that will undergo a set of tests and assays to determine the quality and main characteristics of the batch. 

The sample identified as quality control acts as the _sample_ for the entire population of samples.

To identify a sample as quality control, users navigate to the specific sample details and check the Quality Control checkbox. This creates an icon next to the select sample that identifies it as QC. 

Samples identified as QC allow users to attach files and add notes to them.

**Comment by diegoliberman** [comment]
@gbatiston I think that the idea now is that Samples will be set as Quality Control by using the Specimen Role field #1223.  If you agree, let's cancel this issue/work item.

**Comment by gbatiston** [comment]
Closing due to changes in behaviour
