### ISSUE TITLE
Users can set the number of samples per batch

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1114]
When users create a batch, they can select the number of samples the batch contains. This will in turn generate as many UUIDs as indicated, with the barcodes to be printed for each sample. 

Once the batch is created users can still add more samples to the batch, manually.

**Comment by diegoliberman** [comment]
@gbatiston I think this is already implemented.  If this is the case, this issue should be moved to QA.

**Comment by gbatiston** [comment]
@diegoliberman this is correct
