### ISSUE TITLE
Edit QC-Sample: Assays

### ISSUE THREAD

**Issue by ftarulla** [instedd/cdx#1123]
When editing a Batch, the user may click on the QC-Sample in the Samples List

https://projects.invisionapp.com/d/main#/console/4103589/452291628/preview

~Because the sample is a `QC-Sample`~ the user may add Assays images

**Known issue**: #1215

**Comment by diegoliberman** [comment]
The Notes piece is the less important in this ticket, we could leave it for the future, as the user could upload notes in a TXT.

**Comment by mmuller** [comment]
We support the following formats: png, jpeg, gif.
The file size is not being validated.

**Comment by mmuller** [comment]
After selecting an image when pressing the `Save` button, an internal server error is thrown.
