### ISSUE TITLE
Review 500 error when setting up an account

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1196]
When a user creates an account in the http://cdx.instedd.org/ instance, after selecting a type of institution, the server returns a 500 error. 

If the user changes the URL to redirect from "dashboard" to any other place on the site, everything works fine, it's the redirect to the HOME that is causing issues.

**Comment by diegoliberman** [comment]
It was fixed but we are getting the same error when resetting the password.  Probably, the error has a different cause, hence we'll create a new ticket.
