### ISSUE TITLE
Add batch ID to batch creation

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1201]
A piece of feedback we got from the users after this week's demo is that they'd find it useful to have a batch number assigned to the batch when created. 

@jkicillof this is a piece of information we should add to the details when creating a batch, along with Volume, n of samples, technician name, etc

![image](https://user-images.githubusercontent.com/25181052/124316458-0272af80-db4c-11eb-84b7-5752a65b52c5.png)

**Comment by jkicillof** [comment]
[New batch - Empty](https://projects.invisionapp.com/d/main#/console/4103589/452219759/preview)
[New batch - Complete](https://projects.invisionapp.com/d/main#/console/4103589/452219758/preview)
[Edit batch](https://projects.invisionapp.com/d/main#/console/4103589/452219986/preview)
[Edit batch - Selected](https://projects.invisionapp.com/d/main#/console/4103589/452291697/preview)

**Comment by devduarte** [comment]
Just for QA purposes, the combination of `isolate name` and `batch_number` should be unique. There should not be two different batches with the same `isolate_name` and `batch_number`.

**Comment by mmuller** [comment]
@devduarte the validation of the combination of `isolate name` and `batch_number` is case-sensitive. 
Batch `B1` could have `1234` as `batch_number` and `foo` as `isolate_name`.
Batch `B2` could have `1234` as `batch_number` and `FOO` as `isolate_name`.
