### ISSUE TITLE
Add batch ID to batch list/table view

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1202]
Once issue #1201 has been completed, the batch ID has to be displayed as well in the batch list view, along with the current fields we are displaying.

@jkicillof the batch list view will then have the following details: Isolate name, volume, lab technician, inactivation, date produced, *batch number* 

![image](https://user-images.githubusercontent.com/25181052/124316631-4665b480-db4c-11eb-9ea2-c18eaafc4b6f.png)

**Comment by jkicillof** [comment]
[Batches](https://projects.invisionapp.com/d/main#/console/4103589/452219776/preview)

**Comment by mmuller** [comment]
@devduarte the `date produced` field is not included in the batches list.

The [mock-up](https://projects.invisionapp.com/d/main#/console/4103589/452219776/preview) is not available.

**Comment by diegoliberman** [comment]
@mmuller when verifying this issue, please limit the verification to the Batch ID column.  There will be another [issue](https://github.com/instedd/cdx/issues/1204), and it's there where we will make sure the columns are matching the design.  

By the way, [this](https://projects.invisionapp.com/d/main#/console/4103589/453801740/preview) is the new mockup link.
