### ISSUE TITLE
Allow users to navigate between batches and samples

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1204]
Building on top of #1203, we will modify the Samples section so that it contains the creation of samples and batches while offering users the possibility to toggle between Batch and Sample views, allowing them to navigate and edit its information.  

### Considerations
1. We can consider that we can collapse samples into batches, or that we can switch between samples/batches views. This is just a conceptual consideration.
2. When seeing batches, I think that we should hide samples that don't belong to a batch.
3. When seeing batches, we should show just the batch ID and if it's easy, the number of samples that it contains.  I don't think we should show fields that belong to the Sample, as these fields might have different values for samples that belong to the same batch. It would be awesome to include those fields but with a special logic: we show a Unique + Join of the samples values.

### Implementation
1. Both Samples/Batches are now accessible from the Samples view.
2. The user can switch between Samples/Batches via the Tab icons.
3. Each tab view has its own set of columns.
4. Filters will be implemented with another ticket.

### Invision
1. No samples: https://projects.invisionapp.com/d/main#/console/4103589/453801738/preview
2. Samples: https://projects.invisionapp.com/d/main#/console/4103589/453801737/preview.
3. Samples selected: https://projects.invisionapp.com/d/main#/console/4103589/453801736/preview
4. No batches: https://projects.invisionapp.com/d/main#/console/4103589/453801741/preview
5. Batches: https://projects.invisionapp.com/d/main#/console/4103589/453801740/preview
6. Batches selected: https://projects.invisionapp.com/d/main#/console/4103589/453801739/preview

**Comment by gbatiston** [comment]
@jkicillof let's discuss this when we can, also, to see how we can structure the Samples and its navigation.

**Comment by diegoliberman** [comment]
From [this message](https://manas.slack.com/archives/C034BR64J/p1624460036008400?thread_ts=1624459853.007500&cid=C034BR64J) I understand that 
1. There should be just 1 view for both Samples and Batches.
2. By default it shows single samples.
3. User can collapse batches (not sure what happens for single samples in this scenario)

**Comment by diegoliberman** [comment]
@gbatiston I think this issue description needs to be adjusted per the current plan of having 1 view for both samples and batches.  Let me know if I can help.

**Comment by diegoliberman** [comment]
@nditada did you see the screens that were designed for this feature? In the ticket description you have a link to each one.

**Comment by gbatiston** [comment]
@diegoliberman @jkicillof do we have the updated designs for the new changes?

**Comment by gbatiston** [comment]
@diegoliberman was there an agreement to reduce the number of filters we would use for batch and sample? I can see that there are a few in the designs, but in STG there is only an isolate filter. Can you confirm?

**Comment by diegoliberman** [comment]
> @diegoliberman was there an agreement to reduce the number of filters we would use for batch and sample? I can see that there are a few in the designs, but in STG there is only an isolate filter. Can you confirm?

I don't recall discussing about filters.  Let's talk during our IP :)

**Comment by devduarte** [comment]
For this issue we have changed the batches and index view (the view where those models are listed for the user) making them accesible with tabs. Regarding the creation of a sample or batch, there is a unified view where the user can select which model it wants to create and then gets redirected to the creation form of the chosen model.
@diegoliberman @gbatiston Just making sure we are all on the same page here, when the creation of a sample or a batch is succesful the user gets redirected to the list view of the created model. Same situation would happen if the creation form is cancelled. Is this the correct navigation workflow?

**Comment by diegoliberman** [comment]
> For this issue we have changed the batches and index view (the view where those models are listed for the user) making them accesible with tabs. Regarding the creation of a sample or batch, there is a unified view where the user can select which model it wants to create and then gets redirected to the creation form of the chosen model.
> @diegoliberman @gbatiston Just making sure we are all on the same page here, when the creation of a sample or a batch is succesful the user gets redirected to the list view of the created model. Same situation would happen if the creation form is cancelled. Is this the correct navigation workflow?

It sounds OK to me.

**Comment by gbatiston** [comment]
Sounds OK to me too
