### ISSUE TITLE
Can't set existing sample for existing batch as QC

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1207]
Whenever a sample that exists for an already existing batch is set as QC, there is a message displayed that reads "Core fields sample_type is not supported for entity Laboratorysample", and the sample is not registered as QC. This does not happen for new samples created for existing batches, or for samples created for new batches. 

Steps to reproduce:
1.- Access an existing batch
2.- Select an existing sample to edit
3.- Check the QC box
4.- Save changes

Expected: Sample is stored as QC, displays the QC icon next to its ID in the batch detail view
Actual: "Core fields sample_type is not supported for entity Laboratorysample" error displayed, sample is not saved as QC. 

![Screen Shot 2021-06-15 at 11 24 42 AM](https://user-images.githubusercontent.com/2902379/122028981-d07ff000-cdcc-11eb-9c11-9516f1150451.png)

**Comment by diegoliberman** [comment]
@gbatiston I would cancel this bug, as the Quality Control will be changed as described in #1223.

**Comment by gbatiston** [comment]
Closing due to changes in behaviour
