### ISSUE TITLE
Review 500 error when resetting the password

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1208]

**Comment by diegoliberman** [comment]
Waiting for confirmation that it's still happening in Prod.  cc @gbatiston

**Comment by gbatiston** [comment]
@diegoliberman I just ran a quick check on PRD (and STG just to be sure) and it's working fine on both envs.

**Comment by diegoliberman** [comment]
It was already solved.  The root cause was related to sending emails and it was solved in the infrastructure.
