### ISSUE TITLE
Restrictions on naming BATCHES

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1254]
There are, currently, two different use cases for batches:
1. A user wants to print N barcode tags and creates a batch because it is the quickest way to do it. 
2. A user creates a batch of samples that are related in _some_ way (for RADx all samples belonging to the same batch share the same conditions)

When it comes to naming the batch, N batches could share the same isolate name (in the second use case this represents the strain that's been grown and all samples within the batch will be the same) but what sets these batches apart is the `Batch ID`. 

Restrictions:
--> N batches ca have the `same` isolate name, but it should **not** be possible to have two (or more) with the same batch ID. 
--> There can be N batches with `different` isolate names, and have the **same batch id**. 
--> There should be zero batches with the same isolate name, **and** the same batch id.

**Comment by diegoliberman** [comment]
It's nice to know the use cases! In summary, the combination isolate-name + batch-id must have a unique constraint.

**Comment by straight-shoota** [comment]
I think this is already implemented completely. It even worked like that at the time this issue was created.

**Comment by diegoliberman** [comment]
I agree.

**Comment by diegoliberman** [comment]
Work item deleted in Commit
