### ISSUE TITLE
Restrictions on naming SAMPLES

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1255]
When it comes to Samples, these can be created individually and not be linked/related to a batch or even another sample. It does not make sense to have a Batch ID as a field for Samples. This means that, when naming samples, all names should be unique and it should not be possible to create two samples with the same name. 

### Questions
- Would it make more sense to allow samples to have identical names, for the case where multiple samples are extracted from a single patient and have the system/users identify these samples by their UUID? The pro here is that all samples could have the same name (i.e.: the patient's) but the con would be that for users to know which sample they are referring to, they should scan/inspect the UUID.

**Comment by nditada** [comment]
I think this is a semantic problem, i.e. what is the "name" of a sample? What is it used for?

**Comment by gbatiston** [comment]
This links to a question we left on the CDx channel about what fields should be available/mandatory when creating samples. If the field "isolate name" will not be mandatory for samples (as opposed for batches represent the strain and is, therefore, needed) then we should use simple restrictions for the field.
 As for the uses of the field, I am unsure what the samples can be named after. Patient initials? Sample type (tissue, blood, saliva, etc)? Test to be executed?

**Comment by gbatiston** [comment]
Considering most of the samples' fields will not be mandatory, and that on the sample list view we are not displaying the name of the sample but the UUID (which is by itself a unique identifier) I don't think it's necessary to have restrictions on naming samples. I am closing this task.
