### ISSUE TITLE
Improve LOINC selector to display information on available options

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1283]
When a user selects a value for LOINC there is little information on what each available option is and, for this reason, we'll adjust the field to display all available options containing a brief description of what it represents/stands for when the dropdown menu is expanded.

### InVision design
https://projects.invisionapp.com/d/main#/console/4103589/455772057/preview

**Comment by diegoliberman** [comment]
This issue requires the following step in order to work (to run a migration for creating the LOINC codes in the environment that it's being deployed):
https://github.com/instedd/cdx#additionally-setup-for-importing-loinc-codes
