### ISSUE TITLE
Assign samples to a site

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1285]
### Use case
A user at an Institution wants to assign samples to a site

The user should be able to select a site and a set of samples and link them in the system so that it is clear where/to who those samples went, for tracking purposes.

**Comment by diegoliberman** [comment]
@gbatiston I understand this issue is no longer valid.  If so, can we please delete it from Commit?

**Comment by gbatiston** [comment]
Work item deleted in Commit
