### ISSUE TITLE
3- Send a copy of the QC sample data associated with a receipt sample

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1287]
### What happens in the physical world?
When an Institution gets assigned a sample that belongs to a batch, normally they also receive a copy of the results obtained for the QC sample.  They don't receive the original QC, they don't have access to the original QC.  They just have a COPY of it.

### CDx approach
We want to reflect reality as much as possible.  Hence, we don't want to provide access to the original QC.  We want the recipient to have a copy of it.  
We are relaying on an assumption: the QC data shouldn't be modified after it's been sent.  That would be crazy.  Because modifying data afterwards, means that all of the previous tests that were done, need to be discarded.  It would be a very costly mistake, hence this is something that normally doesn't happen.  If it happens, probably the entire batch will be discarded and a new one will need to be created.  

### Potential plan
When a Sample that belongs to a Sample is transferred to another institution:
- [x] The system needs to check if the associated batch has a QC sample.  If it finds 1 or more, a copy of its data (Assays and Notes) needs to be accessible by the recipient.  Note: we are planning to store this data in the new entity called Sample Transfer Data.
- [x] Finding more than 1 QC for the same batch, is not something that should happen.  Hence, we don't want to do much about this, but we don't want the system to break.  Hence, we'll just grab the data of the first one that is found.  
---> It's still pending to define if we agree with Ger on the `first one` logic.

- [x] Add a [View QC Data](https://projects.invisionapp.com/d/#/console/4103589/113463974/preview) action in the samples. 
- [x] The `View QC Data` action needs to be shown only for transferred samples that have an associated Sample Transfer Data.
- [x] The `View QC Data` action takes the user to a view that shows the QC Sample in read mode: https://projects.invisionapp.com/d/main#/console/4103589/462864203/preview
- [x] From the read mode, the user can hit the back action to go back to the transferred sample.

**Comment by diegoliberman** [comment]
@gbatiston you should be aware and provide your opinion about this:
> Finding more than 1 QC for the same batch, is not something that should happen.  Hence, we don't want to do much about this, but we don't want the system to break.  Hence, we'll just grab the data of the first one that is found.

**Comment by gbatiston** [comment]
@diegoliberman "the first one that is found" worries me a bit, as it feels like there's no criteria of what that means, it could be the first or the last QC information available. I'd suggest we always go for the first created, based on the working assumption that there won't be more than one QC sample per batch.

**Comment by gbatiston** [comment]
I have sent an email to the UCSD lab teams to confirm whether this would be real-life use case that we need to worry about and consider, even.

**Comment by diegoliberman** [comment]
Verified in `Version: dev-525a860 (build 1058)` but a bug was found and reported in #1530.
