### ISSUE TITLE
Users can edit samples assigned to them

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1288]
Users can perform the following edits to the set of samples that's been assigned to them. 
- Attach/delete files
- Add/delete notes

 These edits should be allowed only on the attachments/edits the users have done themselves. Users should not be allowed to edit sample information that has been provided by another user (for e.g. the institution that assigned the samples).

-------
Question:
- Should site users be able to edit sample information? In the specific RADx use case it does not sound right, but in other use cases it might be useful/recommended.

**Comment by diegoliberman** [comment]
@gbatiston I understand that this requirement is no longer valid.  If so, can we please delete the work item from Commit?

**Comment by gbatiston** [comment]
Work item deleted in Commit
