### ISSUE TITLE
Iterate sample label information

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1293]
The UCSD lab has highlighted the fact that the printing labels are missing key information. A complete barcode label needs to contain the same information it does now, plus:

- Isolate Name
- Inactivation method
- Production date
 
 If this information is not added to the label by the system, that means they need to either add it manually, which isn't possible due to the size of the label, or they need to use yet another device and increase friction in the process of labelling samples.

**Comment by mmuller** [comment]
@diegoliberman, take into account that the `Isolate name` field is not being validated now:

![image](https://user-images.githubusercontent.com/518152/129064233-33c998d1-a4ed-4b04-86fa-a6f3ba6bbd93.png)
