### ISSUE TITLE
Enable dual boot for having multiple Rails versions

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1322]
The idea is to use a Gem that allows to have multiple versions of rails in the same project/branch.  You will select the version that you want to use at deployment time and it can be part of the CI.
This way, we will be able to work on new features and on migrating, both things in the same branch.  This helps avoiding the difficult situation of working on the migration on a branch that gets too behind the production branch, and then it gets super complicated to merge it.

Here's an article explaining how to enable the dual boot:
https://www.fastruby.io/blog/upgrade-rails/dual-boot/dual-boot-with-rails-6-0-beta.html

Here's the conversation about it:
https://manas.slack.com/archives/C034BR64J/p1630682303031000?thread_ts=1630571164.013600&cid=C034BR64J

**Comment by ysbaddaden** [comment]
The dual-boot means that we should run the CI workflow twice. One with `Gemfile` and another one in parallel with `Gemfile.next`. We can reuse workflows in GitHub Actions now, so it should be achievable without too much repetition (hopefully).

Yet, we should have an alternative Docker image built. For example if I build the `main` branch, I'd like to have a `:dev` tag with the current version of rails (4.2) as well as a `:dev-next` tag with the in-progress version of rails (5.0). Same for release tags, a `:0.19.0` image should have the alternative `:0.19.0-next`.

@matiasgarciaisaia Do you have an idea about how to add this to `build.sh`? Maybe a mere `DOCKER_TAG_SUFFIX` parameter?

**Comment by ysbaddaden** [comment]
Oh, we'll may also have to specify an alternate Dockerfile and/or some build-arg to choose another FROM image. We'll have to upgrade Ruby for the `-next` boot at some point.

**Comment by matiasgarciaisaia** [comment]
Are you interested in actually publishing two different images? Or just building and testing?

[In Verboice](https://github.com/instedd/verboice/blob/b66bda85f030cc15369941bd32b5942d1121e42d/build.sh#L9-L10) we publish two images from a single repo - one with the (Rails) web app, another with the (Erlang) broker. Those `-s` and `-d` are parameters to [manastech/ci-docker-builder](https://github.com/manastech/ci-docker-builder).

**Comment by ysbaddaden** [comment]
Both? Dealing with a `Dockerfile-next-dev` for example will be chieved with a compose override I think. Thanks for for example and `-s` and `-d` parameters, I'll have a look!

**Comment by straight-shoota** [comment]
Yes, we should definitely upgrade to newer Ruby versions! I'm just not sure if we need to be able to dual boot with different Ruby versions simultaneously. A Ruby upgrade should be easier than a Rails upgrade (hopefully) and we might be able to do it in a simple step, without a period where we may need two Ruby versions.
If we can pull that off, it would make things easier in many ways and we could avoid creating a dual boot setup for Ruby.

We'll still need docker images for newer Ruby versions, of course.

**Comment by ysbaddaden** [comment]
Now both versions are tests on GHA :tada: 

We're only missing a `-next` image build.
