### ISSUE TITLE
Minor error in empty batches listing

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#1325]
**Found in version:** eb0b48a

![image](https://user-images.githubusercontent.com/518152/133092134-2917d9b5-94b9-47eb-a314-2491c3e3335f.png)

**Comment by diegoliberman** [comment]
I guess the best here would be to hide the listing title bar. I should only see the central image with its text.

**Comment by diegoliberman** [comment]
Verified in Version: dev-525a860 (build 1058)
