### ISSUE TITLE
Monitor server errors (Sentry)

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/cdx#1328]
Integrate CDx into InSTEDD's Sentry instance to monitor server errors in both staging and production.

We must take care to santitize and filter any sensitive data from reports.

**Comment by diegoliberman** [comment]
@mmuller let us know when you deploy to Staging, as there is a configuration that we need to do for Sentry to Work.

**Comment by mmuller** [comment]
@diegoliberman it is already deployed to Staging
