### ISSUE TITLE
Upgrade Rails from 4.2.5.2 to 4.2.11.3

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/cdx#1329]
The first step to upgrading Rails would be to get Rails 4.2 and its dependencies as up-to-date as possible, being as conservative as possible, by only upgrading to the latest patch and maybe minor releases for some gems —depending on whether they follow semver or not).

That would bring us from Rails 2016 to Rails 2020. Nice.

**Comment by ysbaddaden** [comment]
I made a quick try, since it's recommended to upgrade to the latest patch before trying a rails upgrade and... this time it worked! I wanted to go a patch version at a time (4.2.6, 4.2.7, ...) but I messed up and I got 4.2.11 installed without noticing.

Just one issue with Rake being updated to 13.x which triggered an incompatibility with rspec-core but downgrading back to 10.5 fixed the issue.

**Comment by diegoliberman** [comment]
@ysbaddaden if the issue is closed, shouldn't it be in the QA column? Shouldn't we close the issues when the PR is merged?
