### ISSUE TITLE
Code refactor date_produced in Sample/SampleForm and Batch/BatchForm

### ISSUE THREAD

**Issue by ftarulla** [instedd/cdx#1336]
Move this logic to a concern and the validation should be executed at the `model` level

**Comment by devduarte** [comment]
QA Guidelines:
- Batches and Samples should work as expected.
- Test valid dates for both, Batches and Samples.
- Test saving non valid dates for both batches and samples.
- Test saving blank dates for both batches and samples.
- Test saving alphanumeric characters for both batches and samples.
