### ISSUE TITLE
Sample saved even when entering invalid specimen role

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1339]
### Steps to reproduce the error
1. Create a new sample
2. Enter a production date
3. Select a specimen role, for instance "F"
![image](https://user-images.githubusercontent.com/25181052/136192286-b4c5fe57-30e6-42f5-83e8-48af2f6abd66.png)
4. Place the focus in the specimen role and type an invalid option
![image](https://user-images.githubusercontent.com/25181052/136192323-25070238-fb17-44eb-9860-7f5db99aac19.png)
5. Save the sample

The form will be saved without showing any errors.  The specimen role will be set to the one selected in step 3. 

### Expected behaviour
When entering an invalid option in the specimen role field, and attempting to save the form, it should show the error message that shows today if you skip step 3.
![image](https://user-images.githubusercontent.com/25181052/136192610-625a875e-7b41-4354-81c5-df447fa14753.png)

### Notes
This should be considered for all autocompletes.  For instance, for the LOINC field.

**Comment by mmuller** [comment]
@diegoliberman I couldn't reproduce it by following these steps. 

Please see the screen recording:
https://recordit.co/11FLzQQiT8

**Comment by diegoliberman** [comment]
@mmuller perhaps it's a missed frame in the screen recording, but as far as I can see, the steps weren't reproduced exactly as I tried to explain.  In step 3, pay attention to the screenshot, where I show that the selected option is the one that starts with F, not the letter "F".

**Comment by straight-shoota** [comment]
The same issue applies to the LOINC field.  And probably other autocomplete form fields as well.

**Comment by mmuller** [comment]
Working properly in version fd72912
