### ISSUE TITLE
Provide more filtering options in the Sample view

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1363]
The UCSD team has mentioned that being able to use filters to search for specific batches and samples is very useful, but that they sometimes miss being able to filter using other fields despite the provided ones (sample ID, Batch ID, Isolate name)

They have made two specific requests:
- To be able to filter by Specimen Role in the Sample View
- To be able to filter by Date, in the Batch view.  

### Notes on Date filter
The idea is to start with the easiest solution we can think of.  Two fields for picking start/end dates and done.  I think we don't have a calendar picker, hence let's add fields with a format hint, as it was done with the `Production Date` field in the `Sample` form.

**Comment by jkicillof** [comment]
[Samples](https://projects.invisionapp.com/d/main#/console/4103589/453801737/preview)
[Batches](https://projects.invisionapp.com/d/main#/console/4103589/453801740/preview)
