### ISSUE TITLE
Provide more filtering options in the Batch view

### ISSUE THREAD

**Issue by devduarte** [instedd/cdx#1376]
Splited #1363 into two issues. This issue is for the Batches view.

The UCSD team has mentioned that being able to use filters to search for specific batches and samples is very useful, but that they sometimes miss being able to filter using other fields despite the provided ones (sample ID, Batch ID, Isolate name)

They have made this request:

To be able to filter by Date, in the Batch view.

Notes on Date filter
The idea is to start with the easiest solution we can think of. Two fields for picking start/end dates and done. I think we don't have a calendar picker, hence let's add fields with a format hint, as it was done with the Production Date field in the Sample form.

Design: [Batches](https://projects.invisionapp.com/d/main#/console/4103589/453801740/preview)

**Comment by ysbaddaden** [comment]
@diegoliberman @devduarte There is a `date` input type that displays the date in a local way (e.g. DD/MM/YYYY in France) but formats the value as per ISO8601 (YYYY-MM-DD) + presents a calendar picker.

See https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/date

**Comment by diegoliberman** [comment]
I didn't know that! Looks awesome and a low-hanging fruit.  Do you want to give it a try @devduarte !

**Comment by devduarte** [comment]
@diegoliberman @ysbaddaden Sure! I'll create the PR as it is now and set it as a draft  PR so I can implement the `date` input.
