### ISSUE TITLE
Parse String saved values into Time for Batches and Samples

### ISSUE THREAD

**Issue by devduarte** [instedd/cdx#1382]
Before #1336  Samples that were being created along with batches were being saved as a string . After we refactored the date_produced, the date validations were placed correctly in both models (samples and batches ). The already saved data were not valid anymore so the migrations we created for the filters issues (#1363 and #1376 ) did not saved successfully the invalid models.

**Comment by diegoliberman** [comment]
Testing guidelines:
play with the date produced field, using pre-existent samples, and new samples.  Within the form itself and within the search filters.

Same for specimen role.

Thanks!
