### ISSUE TITLE
2- Allow to transfer a sample that belongs to a batch

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1388]
### What happens in the physical world?
The Sample is sent to the recipient.  But there is not such a thing as a physical batch that is being sent as well.  They just add a stamp in the sample with the Original Batch ID.  This is just for tracking purposes.  They make a copy of the batch's QC data and send that copy along with the sample.

### CDx approach
We want to reflect reality as much as possible within the system. Hence, we want the Sample to be owned by the Recipient institution.  But we don't want the Batch to change of owner.  And we do want the recipient to be able to see a copy of the QC data.

### Potential solution
Note: This issue will remove the IF added in the item 4.2 of #1385 .

For the case that the sample being transfer belongs to a batch, we need to implement the following logic:

- [x] Same logic than implemented in #1385 
> 4.1 The send action changes the access of the Sample, to make it belong to the recipient institution.
- [x] The Batch ID needs to appear in the UI when seeing the Sample, below the Sample UID.  This field can be displayed for all samples that belong to a batch, and for all sample that used to belong to a batch.
[Invision](https://projects.invisionapp.com/d/main#/console/4103589/113463974/preview)
- [x] The sender of the sample, when accessing to the associated batch, shouldn't see the sample that was transferred in the list of samples that belong to the batch.
- [x] ~~A sample that belongs to a batch, can't be transferred again.  This item is just for simplifying, as we should think what happens with the Sample Transfer Data.~~
- [x] In the Samples view, if view filter by Batch ID, we should ideally show also the samples that were received from another institution and that used to belong to that batch id.

![image](https://user-images.githubusercontent.com/25181052/152162091-bed89af1-2fc1-4243-83ce-fad84e3c6bdb.png)

The above diagram can be found [here](https://drive.google.com/drive/folders/1u4MFveAZi6YcyQkRsmGxHEeRRl7aEIxJ).

**Comment by devduarte** [comment]
Samples that belong to a batch and get transferred will be able to be transferred again as it was easier to implement this way.

**Comment by diegoliberman** [comment]
> * item is just for simplifying, a

@devduarte please change the Issue description.  We aim to have in the description what was indeed implemented.

**Comment by diegoliberman** [comment]
Verified in `Version: dev-525a860 (build 1058)`.  However, the batch ID isn't shown for samples that were transferred.  I won't create a ticket for this, let's see if the user asks for it.

**Comment by straight-shoota** [comment]
The old batch number is already tracked. You should be able to filter examples by the original batch number.
It just needs to be shown in the view layer. That should be a trivial one-line fix.
