### ISSUE TITLE
5- Allow to accept a transferred Sample

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1389]
- [x] Transferred samples should have an initial **Transfer Status** of `In Transit`.  

### Log of transfers
https://projects.invisionapp.com/d/main#/console/4103589/462385786/preview
- [x] `In Transit` samples don't display the last 4 numbers of the sample ID.
- [x] `In Transit` samples have an action that presents a modal called "Confirm receipt". 
- [x] Ignore the blue dot that appears in the Samples list icon.  This dot is to represent that there are new received samples, but we are not implementing that right now.  Just mark this check box to acknowledge that you won't implement it now.

### Confirm receipt modal
https://projects.invisionapp.com/d/main#/console/4103589/461729947/preview

- [x] At this point, we won't include the Sample ID field.  Just mark this check box to acknowledge that you won't implement it now.
- [x] The modal has the designed look & feel.
- [x] The modal has a cancel action that simply closes the modal and nothing is done.  The same for the top-right X.
- [x] The modal has a confirm action that changes the transfer status of the Sample to `Received`.

### Note
Only 1 Sample at a time can be confirmed.

### Test cases
- [ ] Confirm the receipt of a Sample, and make sure that the sample is now shown normally in the list of Samples.
- [ ] Also, confirm that you can access to that Sample, you can edit the data, you can add assays, notes.

**Comment by straight-shoota** [comment]
I'm wondering about the state transition of `In transit` samples. This needs some clarification.

Citing from #1101:

> Once the samples are transferred

This is actually not a single point in time. A transfer has two stages: When the sender initializes a transfer, the sample is `In transit`, when the receiver confirms the transfer, it's `Confirmed`.

> .- Samples are removed from the sample list and moved to the Sample Log view
> .- From this point on, Institution A cannot access the sent samples, just see them on the Sample Log view

I'd assume this means the sample should be inaccessible for the sender as soon as the transfer is initialized?

I think in terms of technical implementation it's probably best to remove the association between sample and institution then. That means samples in status `In transition` won't be attached to any institution. Only the transfer is visible, for both receiver and sender.

> .- Confirmation upon reception is required for samples to be displayed on the Sample Log view
> .- After confirming reception, Institution B sees the assigned sample/batch in their Sample/Batch views

That's clear. A sample won't show up in the receiver's sample list until the transfer is `Confirmed`.

**Comment by ysbaddaden** [comment]
Temporarily removing the `institution_id` also works, but maybe it will have some unpredicted consequences?

**Comment by straight-shoota** [comment]
> I'd try to delete the entry from FileTransfer when reception is confirmed, but maybe we still need the information?

I'm pretty sure confirmed transfers must not be deleted. They are intended to be retained as transaction logs. See #1390

> Temporarily removing the institution_id also works, but maybe it will have some unpredicted consequences?

I went with that solution for now. I think it makes sense. If nobody owns samples while they're in transit, they shouldn't be associated. That makes sense from the domain model. And the implementation is pretty simple.

**Comment by diegoliberman** [comment]
@straight-shoota do you still need answers here?  I agree there are some misleadings, but I think it's a case for discussing on a call.  Ping me.

**Comment by straight-shoota** [comment]
No, I don't need any input. I have posted an implementation in #1495. It's probably best to look at that and see whether it needs further changes.

**Comment by diegoliberman** [comment]
Verified in `Version: dev-525a860 (build 1058)`
