### ISSUE TITLE
99- Icon for highlighting there are new In-Transit samples

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1395]
Whenever there are new In-Transit samples, we can let the user know by adding a blue dot in the Logs view icon.

Does the NEW is by user? Or for the entire institution?
What action exactly makes the blue dot go away? 

Live reload?

**Comment by diegoliberman** [comment]
@gbatiston what action would remove the blue dot?  As soon as I access the log section, it disappears? For me and for all users?
@jkicillof what do you advice?

**Comment by jkicillof** [comment]
I think it should be by user

**Comment by straight-shoota** [comment]
Maybe it would be useful to have an indicator whenever there are unconfirmed transfers? These could be two stages of indicators, one when there are *new* unconfirmed transfers and another one when there are *any* unconfirmed transfers. For example, blue dot and grey dot.

**Comment by jkicillof** [comment]
That could work but I think we can't know for sure until real users start using this

**Comment by diegoliberman** [comment]
@jkicillof when does the dot disappears? Or when does a log looses the "new" status?

**Comment by diegoliberman** [comment]
Work item deleted in Commit
