### ISSUE TITLE
Get list of institutions for selecting in the dropdown

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1398]
We need to check this, because the institutions are under the permissions mechanism.  We'll need to find out how to get a  list of all institutions except the current one, as it doesn't make sense to transfer to itself.

**Comment by diegoliberman** [comment]
Leverage #1401

**Comment by ftarulla** [comment]
## The findings from #1401 

We have an endpoint at [`Api::InstitutionsController #index`](https://github.com/instedd/cdx/blob/3a5376175c036b82bad0b7bd07ad398e2276db01/app/controllers/api/institutions_controller.rb#L2)
This is the method used for creating the app's side bar with all the `Institutions` (and `sites`) for the current user.

For this new feature we should add a new `method` (ie define a new endpoint) to return **all** the `institutions`

From the thread in slack with @ysbaddaden, here are some implementations:

The trivial (but slow) implementation:
```
Institution.all.map do |institution|
   {"uuid" => institution.uuid, "name" => institution.name}
end
```

A (lot) more **performant implementation**:
```
Institution
   .pluck(:uuid, :name)
   .map{|uuid, name| {uuid: uuid, name: name}}
```

Another performant implementation:
```
Institution.select(:uuid,:name).as_json
```
(This last solution also returns the `id` attribute)

Between `pluck` and `select`:
- pluck more performant
- select more readable

**Comment by ysbaddaden** [comment]
Oh, select+as_json` is quite nice! Yet, pluck+map is maybe more explicit to me as to what we get in the end.
