### ISSUE TITLE
88 - Show warning message in duplicated original QC

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1399]
When a Sample that belongs to a batch is transferred, the QC associated to that batch is duplicated and sent to the recipient.
We should add a warning message in the original QC, letting the user know that future modifications to the QC, won't be applied to the copies already sent to the recipients.

**Comment by nditada** [comment]
Careful, it's not the QC sample what needs to be duplicated but the data associated to the QC sample. Duplicating the QC sample would be akin to having made another "test tube" of the specimen and that's not what's happening. We are simply attaching the data that was produced after analyzing the QC sample.

**Comment by diegoliberman** [comment]
This issue is no longer valid.  As we are not going to duplicate the QC.  Instead, we will be copying the relevant data (Assays and Notes).  
Additionally, I proposed changed the check box from `Include QC data` to `Include a copy of the QC data`, which will explain better to the sender that they are sending a copy and that future modifications are obviously not synched to the copy.

**Comment by diegoliberman** [comment]
Work item deleted in Commit

**Comment by diegoliberman** [comment]
@ftarulla fyi comments above
