### ISSUE TITLE
Add a Country selector when creating an institutions

### ISSUE THREAD

**Issue by devduarte** [instedd/cdx#1412]
Add a Country selector when user creates an institution, as required in #1379.

Design doc:

https://projects.invisionapp.com/d/main#/console/4103589/460430730/preview

**Comment by diegoliberman** [comment]
Cancelled for the time being.

**Comment by diegoliberman** [comment]
@gbatiston I took the liberty to remove this from the refinement column, as it was canceled AFAIK.  My apologies if this is a mistake.
