### ISSUE TITLE
Icons for Samples & Batches don't match design

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1425]
Johny spotted that these icons are not exactly the same than provided in the designs.

Implemented
![image](https://user-images.githubusercontent.com/25181052/150830173-2bcc912a-b901-4c1a-9d7f-2385ae01abe8.png)
![image](https://user-images.githubusercontent.com/25181052/150830212-0ff077ea-c9e3-459c-9b60-d80cfc06eacb.png)

Designed
![image](https://user-images.githubusercontent.com/25181052/150830267-5635af10-cb3c-4a60-9ced-f85e86505afb.png)
![image](https://user-images.githubusercontent.com/25181052/150830300-c766d5a0-fec3-42ee-a5d0-64c4624e54c7.png)

**Comment by ysbaddaden** [comment]
@jkicillof I can't download the icons from Invision. I see the symbols and paths (fill, rectangle), CSS, but nothing to download the SVG.

**Comment by jkicillof** [comment]
@ysbaddaden you can download the icons now
