### ISSUE TITLE
Use the custom font for adding icons

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1429]
**A bit of history:**
1. More than 5 years ago, a custom font was created with the [IcoMoon](https://icomoon.io/#preview-free) tool for creating custom fonts.  
2. This was shared with the development team, and it was implemented in the site.
3. New icons were created in the Designs.  
4. Sometimes, when a new icon wasn't found, we searched for 1 similar in IcoMoon, and added that one to the custom font.
5. This ended up on having some icons that don't match with the design.

**What do we need to do to correct the deviation?**
1. Document the correct procedure for adding new icons into the font, so that this doesn't happen again in the future.  We can do this in the ReadMe or in the Wiki.
2. Try to spot the icons that don't match the design, and you will need to download the asset, and upload it to the custom font.
3. Take the opportunity to fix the size of the icons, as all of them should be set at 24px by 24px.

**Comment by jkicillof** [comment]
These are the missing icons:
![Icon - Send](https://user-images.githubusercontent.com/5031636/151422011-1ec35b91-aa03-46af-835d-62a467748369.svg)
![Icon - Confirm](https://user-images.githubusercontent.com/5031636/151422015-b43b34a5-285d-49bd-bd67-d559da47cd61.svg)
![Icon - Sync](https://user-images.githubusercontent.com/5031636/151422019-4d7c300c-920a-4b6a-9551-fc8771d9c6be.svg)
![Icon - Batch](https://user-images.githubusercontent.com/5031636/151422023-e888c1c4-9bca-4e0d-8dcf-64847f3a1c1e.svg)

**Comment by diegoliberman** [comment]
@jkicillof for some reason, the icons didn't get attached.

**Comment by ysbaddaden** [comment]
@diegoliberman click on the icons and you'll have the SVG :)

**Comment by diegoliberman** [comment]
> @diegoliberman click on the icons and you'll have the SVG :)

I swear they didn't show up when I made the comment.  Who knows.  Thanks!

**Comment by ysbaddaden** [comment]
Closing since icons are now plain SVG files.

**Comment by diegoliberman** [comment]
Work item deleted in Commit
