### ISSUE TITLE
 Rellocate the [Institution Invite] flow from User section to Context Selector

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1430]
### Issue details
After a conversation with Joni that stemmed from whether it made sense to display sent invites along with the list of users for an Institution, we concluded that having the Institution invite flow engrained within the regular user invites made no sense. We will remove the new invite flow from its current place and turn it into a fixed banner to display on the platform.

### Behaviour / Acceptance criteria
The user can see the button on the CDx website, at the bottom of the context selector (left-hand side, collapsible menu)
When the user clicks on the button, it triggers the institution invite flow
The user is then asked to provide a Name for the Institution, and to select its type
Possible types of Institution are: institution, manufacturer, health organisation
On the next step, users are prompted to provide admin details for the new institution: name, surname, and email
There is a back button for users to navigate to the previous step
When users finalise and send the invitation, a message tells the user the invite has been sent successfully
Users can invite one admin at a time, it's not allowed to provide multiple emails

### Designs
[Designs](https://projects.invisionapp.com/d/main#/console/4103589/463525686/preview)

### Summary
- [x] Restore the user invite flow as it was before the institutions invite (no split, it should take you directly to the user invite)
- [x] Add the button for inviting institutions in the left navigation bar as shown in the design
- [x] When the button is clicked, show the institution invite modal that had been implemented in the users section.  
- [x] Make sure we ticked all the acceptance criterias.

**Comment by mmuller** [comment]
Working properly in version fd72912
