### ISSUE TITLE
[BUG] Invites - Backend email validation

### ISSUE THREAD

**Issue by devduarte** [instedd/cdx#1436]
Add a backend email validation when inviting new users/institutions. Frontend validation fixed in: #1422

**Comment by ysbaddaden** [comment]
Let's try to tackle this _quickly_. It shouldn't take more than a couple hours.

**Comment by diegoliberman** [comment]
@devduarte have you already started? If not, perhaps it's a good candidate for Johannes.

**Comment by devduarte** [comment]
Nope! Go ahead with assigning this to anyone else.

**Comment by diegoliberman** [comment]
Verified in `Version: dev-525a860 (build 1058)`, both user/institution invites are working.
