### ISSUE TITLE
Handle errors gracefully when attaching files in assays

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1456]
- [x] Mandatory fields: ~~LOINC code~~ and (result or attachment)
- [x] If the attachment type is not supported, then show a message saying "The file extension is not supported"
- [x] If the file size exceeds the limit, show the current error message.
- [ ] Other errors: "Something went wrong and we could not save your file, please try again or contact your administrator"

**Comment by diegoliberman** [comment]
@straight-shoota we thought about this issue for you in the upcoming iteration.  @devduarte you might have tips?

**Comment by straight-shoota** [comment]
Additional to improving errors, I noticed another issue with the UI:

When you tried to attach an invalid file and there's an error, you cannot simply delete the assay attachment. You can click the upload field to open a file selector and then hit abort. But I'm pretty sure there should be an `X` like in valid or empty forms, to just delete the item.

**Comment by diegoliberman** [comment]
Johannes is referring to this
<img width="457" alt="image" src="https://user-images.githubusercontent.com/25181052/154088752-315a7702-93dd-4d9e-a47d-aad6ef38de39.png">


Where the user doesn't have the possibility of deleting the Assay.

@straight-shoota I agree it would make sense to keep the delete action, but I guess it was hidden for a reason (perhaps it got complicated).  @devduarte do you remember if there was a reason for hiding the delete action?

@straight-shoota [this](https://projects.invisionapp.com/d/main#/console/4103589/113463974/preview) is the original design for error messages in Assays.

**Comment by straight-shoota** [comment]
Thanks.

The thing is, in this state the user is lost. The form can't be saved because the assay is incomplete and there's no obvious way to remove it. I myself didn't immediately think of opening the file dialog and hitting abort to do that. And even when I did, I wasn't sure if it would work. Of course, an obvious way forward is adding a file (even if just a dummy) and deleting the item then. But that course of action doesn't exactly suggest itself when you only accidentally tried to attach a file.

If you actually want to upload a new file after the previous one has been rejected, the behaviour doesn't seem right as well. When you see the above error and click on the the file area, you can select a new file for upload. But that actually destroys the previous assay and create a new one, with the values for LOINC and result being reset to empty. So I'm pretty sure that needs fixing as well.

**Comment by diegoliberman** [comment]
@straight-shoota I totally agree with you.  My only suggestion is to talk with @devduarte, to leverage learnings that he might have obtained when implementing this feature.  This might save you from getting into dead-ends.  

If I recall correctly, we agreed to destroy the previous Assay, because we were on a hurry for finishing this feature and starting the next one. And this undesirable behaviour was simpler.  

I created #1465 to separate these problem from the original matters of this ticket.  My suggestion is for you to invest a few hours to investigate and see if you can come up with an idea about how to solve it.  If it doesn't take too much time, perhaps we can take the opportunity to fix it.

**Comment by straight-shoota** [comment]
Argh, client side error handling appears to be broken because we're overriding some of `dropzonejs`'  default behaviour 🤦‍♂️.

**Comment by diegoliberman** [comment]
@straight-shoota, before #1454 `.fa` files were rejected by the backend, but we didn't show any error message.  This is a contradiction with not having a validation of file type.  Perhaps the validation is being done by the `dropzonejs` library.  And I hope we can find a way for showing error messages for files that the library will not accept.

I would love these validations to be done client side, but I guess we also need to validate in the backend, for security reasons.  Right?

Regarding overriding the default behaviour of the library, I'd find out why we did that, so that we spread that knowledge across the team.  Also, because with time, we could have new ideas that simplify this piece.

Thanks!

**Comment by straight-shoota** [comment]
Not sure I follow. Do you think there should currently be file type restrictions in place? I can't see any, neither in backend nor frontend code. In both places it should be easy to implement. But doing good error messages seems a bit hard because of structural issues (that I'd like to address first before trying to shoehorn something oonto the current state).

> I would love these validations to be done client side, but I guess we also need to validate in the backend, for security reasons. Right?

Yes, of course. But we wouldn't have to bother with nice error messages. Those should already appear on the client side.

> Also, because with time, we could have new ideas that simplify this piece.

Very much. I already have ideas for that 😆 But it's out of scope for this issue.

**Comment by diegoliberman** [comment]
@straight-shoota hahah great that you already have ideas :) 

If you think that it will be better to delay any of the check boxes of this issue, I think that's fine. We don't want to invest a lot of time before doing a fresh analysis on this feature.

What I do think is important, is for you to figure out where the file type validations are being done, as there's no doubt about that.  Did you read the PR #1454 that brings some light into this topic? -->
> Root cause: For security reasons, Paperclip gem does a file type validation before creating the AssayFile model (detailed info [here](https://github.com/thoughtbot/paperclip/blob/main/README.md#security-validations) and [here](https://thoughtbot.com/blog/prevent-spoofing-with-paperclip)). Since .fa files are not supported, the model was not being saved thus making the AssayAttachment to be rendered without an AssayFile and preventing it to be downloaded.

**Comment by straight-shoota** [comment]
The bullet points 2 and 3 are not entirely resolved, even with #1474. 
Errors during file upload are not handled correctly in the upload widget. So when you try to upload an invalid file there is no error message but you can't submit the form (button is disabled). Fixing this should be deferred for #1465

**Comment by jkicillof** [comment]
@ysbaddaden:
1. The filename was already in the designs.
2. The button to remove an assay without deleting the card could be shown on hover.
3. I'll play around to see if I find a better layout

**Comment by jkicillof** [comment]
I moved the error to an extra line on bottom leaving an icon to add file if nothing attached or a delete icon on hover.
![image](https://user-images.githubusercontent.com/5031636/155014726-a4f1ae10-bfb3-4023-8f62-68fb30b276ef.png)

**Comment by gbatiston** [comment]
@jkicillof I really like how you solved this!

**Comment by diegoliberman** [comment]
I documented the design changes in #1465.

**Comment by diegoliberman** [comment]
@jkicillof I couldn't find in Invision the screen that you are showing.  Perhaps you forgot to update Invision?  Thanks

**Comment by jkicillof** [comment]
@diegoliberman [here](https://projects.invisionapp.com/d/main#/console/4103589/464419852/preview) it is
