### ISSUE TITLE
Root cause of AssayFiles with nil references

### ISSUE THREAD

**Issue by devduarte** [instedd/cdx#1461]
As researched in #1427, when deploying [version 0.16.1](https://github.com/instedd/cdx/releases/tag/0.16.1) AssayAttachments references were lost. So we need to confirm the root cause and fix [this migration](db/migrate/20211104135226_migrate_assay_attachment_pictures_to_assay_file.rb).

**Comment by devduarte** [comment]
I think that whats left here is to modify `20211104135226_migrate_assay_attachment_pictures_to_assay_file.rb` file to just delete the attachment columns from `AssayAttachments`: 

```
def up
    remove_column :assay_attachments, :picture_file_name
    remove_column :assay_attachments, :picture_file_size
    remove_column :assay_attachments, :picture_updated_at
    remove_column :assay_attachments, :picture_content_type
end
```

. There are several reasons for this: 

- This migration was intended to migrate the attachments references from the assay_attachments table to assay_files table. The way is written now does not have Paperclip (and the way it handles file paths) into account, we are just copying values from one table to another. The correct way to handle this problem is doing this: 
```
  assay_file = AssayFile.create(picture: assay_attachment.picture) 
  assay_file.assay_attachment = assay_attachment
  assay_file.save!
```

But the picture attribute from `AssayAttachments` was moved to the `AssayFile` model, so the solution does not work anymore. (Maybe there is another way to move Paperclip attachments from table to another that I'm not aware of)

-Since we only have one client (@diegoliberman please correct me if I'm wrong here) that went through the process of using previous versions of the model, new clients won't the problems that the migration intended to fix and also the problems that were caused by this migration. Basically, new clients won't need the data to be moved to another model since they will be using the updated one.

-Also, we manually fixed inconsistencies related to files references with Mati, so the problems that the client had are already fixed and the problems that this migration tries to solve are gone. We should confirm with the client that everything is solved.

- #1485 will contain a full analysis on how to improve the feature and prevent inconsistencies we have had in the past due to `AssayAttachments` model mutating, so that will cause that the mentioned migration file to be more outdated than it is now.

**Comment by diegoliberman** [comment]
@devduarte it sounds fine to me.
