### ISSUE TITLE
[Bug] Incomplete sample form validation

### ISSUE THREAD

**Issue by straight-shoota** [instedd/cdx#1476]
I noticed another UX issue related to the samples form. When there's an error in some of the sample data that's validated in `SampleForm`, other errors won't be shown because validation stops before validating the actual mode.

For example, when I create a new sample but fill no input field, only create a new, empty assay attachment. There should be at least two error messages: Production date can't be empty and the assay needs a LOINC code as well as either result or a file attachment.
But only the former messages actually shows up:

![grafik](https://user-images.githubusercontent.com/466378/154966456-fec1085d-fc12-412c-b7db-fc36fc3bd3dd.png)

It looks like everything's okay except for the production date. Only after filling in a value on the date field, the form shows the additional errors in the assay attachment.

The relevant code is here:

https://github.com/instedd/cdx/blob/4c31f3011f7a2ac143b7ec292f1dcd769e4ed56b/app/models/sample_form.rb#L83-L89

**Comment by straight-shoota** [comment]
When talking about this earlier, I confused this with https://github.com/instedd/cdx/issues/1065. That one is about attaching error messages directly to the fields, while this here is about changing the validation logic.

**Comment by diegoliberman** [comment]
> When talking about this earlier, I confused this with #1065. That one is about attaching error messages directly to the fields, while this here is about changing validation logic in the samples form.

Both are good candidates for me.  Let's start with this one and then continue with #1065.

**Comment by diegoliberman** [comment]
Testing: batches, patients and Samples

**Comment by mmuller** [comment]
Working properly in version fd72912
