### ISSUE TITLE
7- Q samples cannot be transferred

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1483]
### Details 
 As the QC Sample is the one that contains all the relevant assay information that sets the bases for all sample recipients to run their tests, these should not be allowed to be transferred. 

### Behaviour
- When a user selects Specimen Role as Q, when creating a new sample or batch, there is a message on screen that lets the user know these samples are not transferrable
- When a user transfers samples that have no QC, there is a message that lets the users know there is no QC info available for those samples (#1484)
- When users select samples from a list, the Transfer icon should not be enabled if a QC sample is selected

### Questions

**Comment by jkicillof** [comment]
[Sample detail](https://projects.invisionapp.com/d/main#/console/4103589/113463974/preview)

**Comment by gbatiston** [comment]
@jkicillof how should we prevent users from trying to transfer Q samples?
1. Disabling the Transfer button if the users select Q samples from a list
2. Allowing users to select all samples they want to transfer but displaying an error message if they click on the transfer button when having QC selected
  - In this scenario, I would expect the system to somehow identify which are the problematic samples that are blocking the transfer (either by an error message that lists the sample IDs, or by highlighting the samples on a list, or some other way)

**Comment by jkicillof** [comment]
I go with #1 showing a message on the table title like [this](https://projects.invisionapp.com/d/main#/console/4103589/464738448/preview)

**Comment by gbatiston** [comment]
Thank you, @jkicillof!

@diegoliberman I think we have everything we needed to move forward here, otherwise let me know
