### ISSUE TITLE
88 - "Include QC Info" checkbox is disabled for batches with no QC samples in them

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1484]
### Details
 When a user transfers samples from a batch that has no QC sample determined, the checkbox to "Include QC Info" is hidden, and we show a proper message in its place, as [designed](https://projects.invisionapp.com/d/main#/console/4103589/464604107/preview). 

![image](https://user-images.githubusercontent.com/25181052/156381995-bba1b6a8-6f7d-4d46-bf24-e6ec50d8c0d5.png)
![image](https://user-images.githubusercontent.com/25181052/156382253-a75cdcae-4a35-49e2-9aa7-2764896e77a8.png)

**Comment by diegoliberman** [comment]
@gbatiston this has already been done as part of #1287.  The link shows only when there's a link to a QC Info.  @devduarte can you confirm?

**Comment by gbatiston** [comment]
@diegoliberman am I mistaken in thinking there was a comment from you here?

**Comment by jkicillof** [comment]
[Transfer sample](https://projects.invisionapp.com/d/main#/console/4103589/464604107/preview)

**Comment by diegoliberman** [comment]
> @diegoliberman am I mistaken in thinking there was a comment from you here?

You are correct, but I deleted it because I was saying nonsenses :P

**Comment by devduarte** [comment]
@diegoliberman @gbatiston What should happen with the checkbox when I want to transfer two samples from two different batches, one having a QC Sample and the other one doesn't have a QC Sample?
I thought about showing both things and tweaking the info description to be "There is no Quality Control (QC) info available for some of these samples". If the user checks the checkbox, the QcInfo will be available for the samples that actually have a QC sample in their batches. On the other hand, this might be misleading for the user.

**Comment by ysbaddaden** [comment]
Some ideas out my brain:
- specify "[ ] transfer QC info (when available) in the checkbox?
- visually mark the samples without QC?

**Comment by diegoliberman** [comment]
@devduarte 

1. If there's no QC for none of the samples, we show the message as design.
2. If all of them have a QC sample, we don't show the message and display the check box as it is.
3. If some have and some doesn't, show the check box and show a new info message below: "There is no Quality Control (QC) info available for N samples".   N should be dynamic. 
4. I like the idea of visually marking the samples without QC, but for now let's not do it.  I'll create a separated ticket for that.
