### ISSUE TITLE
99- [Sample Transfer] Users can mark a sample as 'Lost'

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1500]
### Details
[This could be considered as an iteration on the Sample Transfer feature, not a feature needed for launch]

It could happen that a sample is transferred from an institution to another, but the physical sample gets lost and the recipient never gets it. In that scenario, users should have a way to identify the sample as "lost" or "not delivered", in the system. 

In the case where a sample is lost, ownership of the sample should be sent back to the sender, so that they can determine if the sample should be deleted, or traced through the delivery system. 

### Behaviour
1. A sample gets transferred from Inst A to Inst B
2. The sample status gets updated to In Transit in the system
3. Inst B has an option to Confirm Reception, or to indicate the sample has been Lost
4. When sample gets marked as Lost, its ownership changes back to Inst A, who determines the fate of the sample

**Comment by straight-shoota** [comment]
I've thought about this as well and I believe wording can be more general than "lost". There could be other reasons to revoke a transfer. For example, starting the transfer in the first place could've just been a mistake.

**Comment by gbatiston** [comment]
@straight-shoota hhmm perhaps something more generic experience, then? A "reject" option, where the recipient can input the cause for rejection? (Lost, sent by mistake, accepted by mistake, wrong sample, etc). We can prompt the users to describe why they want to reject the sample, and leave an input text field open for that

**Comment by straight-shoota** [comment]
Hm, yeah that would bring some more complexity which I'm not sure if it would be much useful. Depends on how common such a scenario is.

I think the easiest implementation would be adding an option to cancel a transfer. I would give that option only to the sender, though. They should be in control of the transfer process.
If the receiver has a reason to reject it, they can contact the sender and discuss what to do. Or, to properly represent the real world if the sample actually arrived but they didn't want/shouldn't get it, they can confirm the receipt and start a transfer to send it back.

**Comment by diegoliberman** [comment]
Work item deleted in Commit
