### ISSUE TITLE
Avoid mixing secure and non-secure content

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1506]
For example, when opening a Sample, you can see the mixed content warning in Google Chrome's console.  We should avoid mixing content that loads from `https` with content that loads from `http`.

![image](https://user-images.githubusercontent.com/25181052/156767094-1d76a48f-83c8-40b1-aec6-2211b81baeb7.png)

**Comment by ysbaddaden** [comment]
This example should be fixed by #1504 since links to S3 should always use HTTPS.
