### ISSUE TITLE
UUID presentation

### ISSUE THREAD

**Issue by straight-shoota** [instedd/cdx#1510]
UUIDs are quite a bunch of characters. Displaying them on the page is sometimes a bit of a challenge, especially when space is rare, like in tables. The exact UUID value bears no real information, it's only use case is for identifying objects. That's somewhat restricted when part of the UUID is chopped off because it doesn't fit in the table column for example.

![grafik](https://user-images.githubusercontent.com/466378/157053710-7cfb6cd4-5f72-4b0f-9b59-51d52f185870.png)

Some of the design previous present UUIDs as five groups of four uppercase characters (https://projects.invisionapp.com/d/main#/console/4103589/462385786/preview). That's less than the 36 characters of a full UUID and thus it takes less space in the preview than the real full UUID. And in other previews as well as in the actual app, UUIDs use lowercase characters.
I'm not sure if these other designs are just a mistake/unspecific or if they represent some idea for usability improvement.

Technically, it should be possible to limit UUIDs to a part of themselves. For example, we could always chop off the last 8 characters. That should still have plenty of space for avoiding collisions and would make it easier for users because they have to deal with less characters.

As an example for some practical effects:  #1389 asks that the last four characters of an unconfirmed UUID should be hidden. But this is pretty much without effect because the end of the UUID is always chopped off on reasonably wide viewports.

![grafik](https://user-images.githubusercontent.com/466378/157053591-7d5f80db-f604-4ed3-9a3b-185dc8876e38.png)
![grafik](https://user-images.githubusercontent.com/466378/157053801-f269f4ce-ccbc-4ba6-81b4-4b545223bc89.png)

I'm wondering what can be done to improve UUID presentation. I think it doesn't make much sense to almost always have only a chopped off part of UUID presented in tables. If there's no other solution, we should at least add a tooltip or some other mechanism to reveal the full UUID when parts are hidden overflow. The same applies to other values in table cells, really. So maybe it's not even a specific problem about UUIDs and about table cells in general.

**Comment by nditada** [comment]
IMO, the best way to display guids is to show the first few and the last few chars with an ellipsis in between, that's all you need to verify you have the right sample. Clicking or hovering should display the rest.
