### ISSUE TITLE
[Sample Transfer] Allow users to select multiple samples from different batches

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1512]
### Use case
As a user, I want to transfer multiple samples from different batches, at the same time so that I don't need to repeat the operation several times

### Details
As users will be sending multiple samples belonging to different batches, at once, we want to provide a nice experience where they can do so without having to start the processing time and time again. 

### Behaviour
Since this is still a to-be-explored enhancement, here are some ideas:
1.- Allow users to select samples from different batches, keeping their selection if they apply filters or change pages
2.- Ask users if they want to send samples to their last recipient (should consider attachments also)

**Comment by diegoliberman** [comment]
Duplicated with #1563

**Comment by diegoliberman** [comment]
Work item deleted in Commit
