### ISSUE TITLE
No notification on incoming samples for recipient

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1524]
### Details 
When a sample is transferred, the recipient Institution sees, in the Transfer section, the incoming samples. There should be a blue dot to notify users there are incoming samples in this section, so that users know something requires their attention. 

### Steps to reproduce
1. Send samples from Institution A to Institution B
2. Navigate to Institution B

Expected: User sees a blue dot on the Transfer menu, upon access the samples are displayed
Actual: The samples are displayed when the user access the Transfer menu, but there is no notification that there are new items to review

**Comment by diegoliberman** [comment]
@gbatiston this was supposed to be tackled in #1395.

**Comment by diegoliberman** [comment]
Work item deleted in Commit
