### ISSUE TITLE
Transfer sample action is enabled even when selecting QC samples

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1525]
In order to reproduce this bug, these exact steps must be followed:

1. Go to he samples view
2. Select a QC sample
3. Result: the transfer action is disabled and the error message displayed.  So far, so good.
4. Select a non QC sample
5. Result: the transfer action gets enabled.  The error message remains.  Wrong and inconsistent.
6. Select another non QC sample.  Same result than step 3.  Wrong.
7. Remove the selection of a non-QC sample.  
8. The message disappears and the action gets enabled.  Even when there's still a QC sample select.   Wrong.

I didn't continue testing, but let's try to test everything that comes to our mind when fixing this.

**Comment by straight-shoota** [comment]
This should've been implemented in #1515. The screenshot there indicates that it works. So apparently, something's gone wrong.

**Comment by diegoliberman** [comment]
> This should've been implemented in #1515. The screenshot there indicates that it works. So apparently, something's gone wrong.

@straight-shoota yes, it works but there are bugs in several test cases.
