### ISSUE TITLE
Access to view QC info returns a 403 error

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1530]
### Details
 After transferring samples to an institution, including the QC info, when the recipient clicks on "View QC info" a 404 error is returned

### Steps to reproduce
1. Transfer a sample from InstA to InstB
2. Make sure to include a copy of QC info
3. Log in as InstB and confirm sample reception
4. Access the sample and click on View QC info

Expected: QC sample info is accessible and visible
Actual: A 403 error is returned and the user cannot see the QC info copy

<img width="755" alt="Screenshot 2022-03-14 at 11 56 57" src="https://user-images.githubusercontent.com/2902379/158158727-4f8d4540-5a45-4d3b-8c8b-45bf0d188df7.png">

**Comment by gbatiston** [comment]
@diegoliberman challenge accepted, here you have a recording of it. 
https://user-images.githubusercontent.com/2902379/158203987-2c567aa8-cc23-4920-9bb3-c38d034809a2.mov

**Comment by diegoliberman** [comment]
@gbatiston could you share the email of the test user, the roles that it has, and the permissions for that role?

**Comment by gbatiston** [comment]
@diegoliberman this is gbatiston@instedd.org, with an Admin role, with the following set of permissions 

<img width="934" alt="Screenshot 2022-03-14 at 16 45 19" src="https://user-images.githubusercontent.com/2902379/158208855-1bab67be-a4c7-4458-ba42-90676321c723.png">

**Comment by diegoliberman** [comment]
This is so confusing.  How can German get to the Samples view when he doesn't have any access granted for the Sample/Batches entities.

**Comment by diegoliberman** [comment]
@gbatiston in the Institution permissions, there are more if you scroll down.  Could you let us know if you have permission for creating samples/batches?

**Comment by gbatiston** [comment]
Here's the full list of actions

<img width="329" alt="Screenshot 2022-03-14 at 17 04 43" src="https://user-images.githubusercontent.com/2902379/158212600-718e7f13-f16b-4395-a027-a0e0e9b215b6.png">

**Comment by diegoliberman** [comment]
I started getting the error in the same Sample test.  Not sure what I did to make it happen.

**Comment by diegoliberman** [comment]
![image](https://user-images.githubusercontent.com/25181052/158213502-9b77d21d-db7f-4006-aa9a-8f6ea0bb556e.png)

**Comment by straight-shoota** [comment]
Ah, that explains it!

The reason is that the access check for QC info checks if the user has can read the first sample associated with it. This assumes that all samples that the QC is attached to are equal. But that's not the case when a part of the samples has been transferred twice, because the QC does not get regenerated.

So I think the solutions are 1) allow access to QC info whenever the user has access to *any* of the associated samples 2) always create a new QC info instance when a sample is transferred, even if it's already assigned one.

**Comment by straight-shoota** [comment]
The solution should probably be evaluated in the context of  #1499 and general consideration about QCInfo - currently this concept only exists for samples that have been transferred - but it should be able to apply it equally to non-transferred samples.
