### ISSUE TITLE
The search by batch ID in the log of transfer doesn't work

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1538]
When searching by Batch ID, it's not finding any matches even when I did transferred samples that used to belong to that batch id.

1. Create a batch with N samples
2. Transfer 1 of the samples to institution B
3. Go to the log of transfers and filter by batch ID
4. You'll get no results.
5. Login to institution B.  You'll get to the same bug.

![image](https://user-images.githubusercontent.com/25181052/158247648-25f4d8e3-a3e8-4cea-9202-8c8bd819e578.png)
![image](https://user-images.githubusercontent.com/25181052/158247883-794a6444-0c35-458a-a231-1cf9ee2279ce.png)

<img width="1539" alt="image" src="https://user-images.githubusercontent.com/25181052/158247732-1afb4bfd-138e-4ce7-82d8-8c322958f745.png">

**Comment by mmuller** [comment]
This issue is still present in version be18ffa
