### ISSUE TITLE
Allow to share measurement reports

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1555]
Allow downloading reports PDFs and SVG images, from the specified buttons shown in this [mockup](https://projects.invisionapp.com/d/main#/console/4103589/470820372/preview). 

Previous specification for this issue was to allow sharing of reports, in case there is time to implement it here it was its specification: 

Allow to share measurement reports with other institutions.   The institution that receives a shared report will see it in its own list of reports, but won't be able to modify it, nor delete it.

### Acceptance criteria
1. I can share a measurement report with 1 or more institutions
2. I can see a measurement report that was shared by other institution
3. I can distinguished between my own measurement reports and the ones that were shared with me
4. I can't modify nor delete reports that were shared with me
5. I can stop sharing a report with other institution
6. For the shared reports, I can see what's the institution name that shared it with me

**Comment by leandroradusky** [comment]
For testing purposes (cc @sardar-usman)

This feature was modified by the client: now the way to share reports is implemented in the buttons `Download charts as SVG` and `Download PDF`.

We should check that the generated SVG images and the PDFs reflect the information seen in the report as pointed out in #1830.

**Comment by cclopez78** [comment]
Blocked by #1873

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine now.
