### ISSUE TITLE
Change the "transfer samples" modal into a full page form

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1566]
### Context
The transfer samples modal doesn't make sense when thinking on the scanning QR codes flow.  It used to make sense when the modal was working on the samples selected in the background list.  Now, the sample transfer will be more independent, and it makes sense to make it a full page form.  It will also provide value as there will be more space for showing more data if needed.

[This](https://projects.invisionapp.com/d/main#/console/4103589/465342627/preview) is the full page design.

### Game plan
- [x] step 1: no change in behavior (keep form, autocomplete, ...);
  - [x] step 2:
    - [x] add `samples#show` (JSON) to request a Sample by UUID (or use autocomplete?);
    - [x] request sample when a valid UUID is scanned / typed / pasted;
    - [x] validate the sample and either add it to the form, or display an error/notice message + clear input.

### Acceptance criteria
1. When I open the transfer form, the institution field is the first one I see.
2. After selecting an institution, the focus is placed automatically into the empty field for entering a sample ID.
3. In the empty field, I see a hint `Enter, paste or scan the sample ID`.
4. **Optional**: if trivial/easy, when I start typing, I see an autocomplete with suggested IDs.
5. If I enter paste or scan a sample ID that matches with a sample within the current institution, the sample is added to the list of samples to be transferred, the field gets emptied and receives the focus.
6. If we implemented the autocomplete, and after typing some characters, there are no matchings, the autocomplete shows the message `No matches found` as the unique/unselectable option.
7. If I paste or scan a sample ID that doesn't match, a feedback message appears below the field `The sample id xxxxx wasn't found`, the field gets emptied and receives the focus.
8. The same logic than described for `No matches` applies if the sample ID has already been added to the list of samples to be transferred.  In this case, the message is `The sample ID xxxx can't be added twice`.
9. Same logic for message `The sample ID xxxx can't be added because it's a QC`.
10. I see a button for cancelling the transfer action, which takes me back to the list of transfers.
11. I see a button called `Transfer` which executes the transferring action.  I see a success message after pressing it. 

### Considerations
- [ ] Some scanners might include a carriage return at the end of the string.  We should handle this use case by correctly reading the sample ID and searching for matches without the carriage return as part of the search string.

**Comment by straight-shoota** [comment]
> After selecting an institution, the focus is placed automatically into the empty field for entering a sample ID.

I don't think this can work anymore because we also have the *Recipient* field now which would be skipped if it worked that way. Since it's free form text input, there is no selection complete event we could use as a trigger to focus the UUID input field.
But it's possible to jump to the field using tab.

**Comment by straight-shoota** [comment]
I postponed autocomplete. It should be simple to add in later, but isn't necessary for a MVP. You can do a partial search (press enter) after entering an unambiguous number of characters from the UUID.

**Comment by diegoliberman** [comment]
This one is related with #1610.  At the time of QA, you might find that samples can't be transferred anymore.  Instead, boxes will be transferred if #1610 was already implemented.

**Comment by mmuller** [comment]
Working properly in version fd72912
