### ISSUE TITLE
Add responsible recipient when transferring samples

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1572]
When transferring samples, a very important piece of information is the name of the person that is legally responsible for receiving the samples.  For traceability, they need to keep track of who was this person for each transfer.

- [x] Let's add a free text field, below the institution field.  [Invision](https://projects.invisionapp.com/d/main#/console/4103589/465275290/preview).

The field should be optional, as for use cases beyond UCSD, it might not be relevant data.

- [x] Let's add a column in the log of transfers.  [Invision](https://projects.invisionapp.com/d/main#/console/4103589/465275288/preview).

### Note
We already have 3 fields for the transfer action: Institution, Responsible, and Include QC Info.   It's becoming logic to think that the transfer should be an entity of its own in the system's backend and frontend.  For now, let's not do nothing non-trivial to go in this direction.  Just bear in mind that at one point, we will have to consider it so that we better represent reality.

**Comment by ysbaddaden** [comment]
With the current schema we'd have to duplicate that recipient column for each SampleTransfer. But... since we know we'll want to have a package of sample transfers, let's create a simple model now:

```ruby
class TransferPackage < ApplicationRecord
  has_many :sample_transfers

  # attribute :id, :uuid
  # attribute :recipient, :string (nilable)
end

class SampleTransfer < ApplicationRecord
  belongs_to :package, class_name: "TransferPackage"
end
```

There is only one change: when we create the sample transfers, we first create a TransferPackage —with the recipient's name—, then create each sample transfers through it. Listing the transfer log won't change, except for a `.preload(:package)` to display the recipient's name (`sample_transfer.package.recipient`).

**Comment by ysbaddaden** [comment]
The reworked sample transfer form, with the responsible person field, and reordered fields:

![Capture d'écran du 2022-04-01 11 20 55@2x](https://user-images.githubusercontent.com/47380/161235079-830db0f0-4a6c-42d0-991d-b4a93d9f65ab.jpeg)

---

The responsible person column in the transfers list:

![Capture d'écran du 2022-04-01 11 21 08@2x](https://user-images.githubusercontent.com/47380/161235083-0c8476d9-c207-4c87-990a-53b19866205f.jpeg)

**Comment by straight-shoota** [comment]
1. The table view was already pretty cramped. Now even more so. Using a short UUID would only give a bit more space. But relevant information (such as status dates) are pretty much hidden. We should consider an alternative presentation format (for example have each item span two rows, group some data per package, or remove data from the overview and provide a more detailled view for individual transfers).
2. "responsible person" is very specific. It could just be a generic recipient id. For practical purposes it doesn't matter whether that's an actual person's name or any other kind of identifier. The actual semantics can be entirely decided by the transfer parties.

**Comment by diegoliberman** [comment]
1. I would go in the direction of having a delivery package, and within the samples that were included in that delivery.  I'll create a work item where the first step would be to design something.  But I don't think we'll get to do it this with the current budget, so let's not invest much time now.
2. I agree, we could rename it to `Recipient`.  I'll create a work item for that as well.
