### ISSUE TITLE
Rename the Responsible person field to Recipient

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1583]
- [x] Rename the field in the transfer form
- [x] Rename the column in the list of transfer logs
- [x] Ask Johny to update the designs

![image](https://user-images.githubusercontent.com/25181052/161783782-ffb765c7-ae81-4f6f-b93c-d89b78eba7ba.png)
![image](https://user-images.githubusercontent.com/25181052/161783820-3001a551-f179-4dc5-a5e7-fc234f7b3161.png)

**Comment by devduarte** [comment]
johnny asked [here](https://manas.slack.com/archives/C034BR64J/p1649454335501019)

**Comment by jkicillof** [comment]
All screens were updated
