### ISSUE TITLE
Validate uniqueness of institution name

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1585]
Now that we can transfer samples, having duplicated names of institutions, causes some problems: you can't differentiate which institutions is the one that you actually want.
![image](https://user-images.githubusercontent.com/25181052/162052100-f9a0c330-ad2a-4385-b982-79b280f787a3.png)

- [ ] When creating an institution, its name must be unique across CDx.
- [ ] When editing the institution, the same validation applies.
- [ ] When inviting institution, the same validation applies.
- [ ] Manually edit institutions that remained with duplicate names in Prod or Staging.

**Comment by straight-shoota** [comment]
It's probably a good idea to require uniqueness for the name. However, I want to mention that it could be an alternative to instead add an unambiguous identifier to tell different institutions apart. For example, we already have a database ID that could be used for that. This would be much easier to implement as it only requires a simple display change and does not involve mutation of production data.
It's probably not the *right* solution though and it would clutter the UI, but it's a quick and cheap alternative.
There might be some case for institutions sharing the same name (it's an open global system after all). Might be worth considering.

**Comment by diegoliberman** [comment]
I always like to hear about cheaper solutions.  I'd consider showing the ID if we can also show it in the institution details page (I need to know which is the ID of my institution in order to identify it in the list among other IDs).  If the ID is just a sequential number, we can show it as is.  But if it's a random long string, I'd show just the last 4 characters.  `<institution name> <id>`

Note: if CDx gets to a point where institutions with the same name are created, I think it would be a reason for celebration.  The current collisions must be tests/mistakes.

**Comment by ysbaddaden** [comment]
The best UX course is to have unique names across a CDx instance. Having to deal with UUID in addition to the name is just confusing and plain cumbersome.

Validating that the institution name is unique on save will be quick & simple. I don't see much breaking, we just need to take care to properly report the uniqueness error when creating/updating the institution as well as during the invite feature, and that's it.

Staging is likely full of duplicates, production may have some duplicates (mostly tests) and radx is probably fine.
