### ISSUE TITLE
Show date last modified date in Samples

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1598]
### Use case that triggered this req
A user needs to know when Assays have been uploaded into the Q sample.  Today, the person is accessing each Q sample to see if there are new assays for any.

### Idea
In order to make a general solution, we could add a column in the Sample's listing, showing the last modified date.  The date should be updated when any sample's attribute is modified, including Assays or Notes.

### Acceptance criteria
1. I attach an Assay to a Sample, save, and in the list of samples, it's shown with today's date in a `Modified` column.
2. I make any modification to a sample, and the `Modified` date is updated with today`s date. 
3. I have a way to quickly find the samples that were modified most recently.

### Options for finding samples that were modified recently
1. Allowing to sort by Modified, descending.  Sorting hasn't been implemented anywhere else in the site.
2. Allowing to filter by a start/end date.  This has been implemented in the Batches list.
3. Adding a dropdown filter labeled "Modified" with these options: today, yesterday, last 7 days, last 30 days, last 60 days, last year.

**Comment by straight-shoota** [comment]
I suppose this should also include sorting and/or filtering by modification date? Showing the date on the index page is certainly already an improvement, but when working with lots of samples to keep track of, I imagine it would help a lot to be able to sort and/or filter by date.

**Comment by diegoliberman** [comment]
You're absolutely right, it needs to be implemented along with something else.  I would start with a simple filter with fixed options: modified in the last 7 days, 14 days, 30 days.   I'm not suggesting to start with a sort, because we don't have any other sort in the page, so it might require more effort than adding a filter.

**Comment by straight-shoota** [comment]
The implementation is actually quite similar and any differences should really be neglibible. So I think it should be up to what's most useful.

**Comment by diegoliberman** [comment]
We'll decide when the implementation time comes.  Maybe both? Who knows :)

**Comment by diegoliberman** [comment]
I think the sorting could be more useful.

**Comment by mmuller** [comment]
In version `7100246`: 
-after clicking on the `Modified` header, the samples sorting doesn't change.
-the `Modified` date is not updated after adding an Assay. It happens **randomly**.

**Comment by diegoliberman** [comment]
> In version `7100246`: -after clicking on the `Modified` header, the samples sorting doesn't change. -the `Modified` date is not updated after adding an Assay. It happens **randomly**.

@mmuller we didn't implement sorting when clicking on the header.  Instead, there are 2 new filters to select a date range.

**Comment by omelao** [comment]
> > In version `7100246`: -after clicking on the `Modified` header, the samples sorting doesn't change. -the `Modified` date is not updated after adding an Assay. It happens **randomly**.
> 
> @mmuller we didn't implement sorting when clicking on the header. Instead, there are 2 new filters to select a date range.

@diegoliberman yes we did...but after code review, it's not working anymore. I will check what's happening.
