### ISSUE TITLE
New fields for samples

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1603]
Those boxes that have a predefined purpose, require more fields.  These fields are applicable to all samples, but for boxes with a purpose, these fields are very important.

### New fields
1. Virus lineage.  Free text field. It needs to be created for the batch as well.  All samples from the same batch, will have the same virus lineage.  Remember that when creating batches with N samples, the N samples should be completed with the field values entered in the batch.  
2. Box ID (will be added when we implement the creation of the Box entity).  It's listed here just as a FYI.
3. Box purpose.  We will need to show this field when printing a list of samples, and in other places.  I don't know if we need to store it as part of the sample, or pull it from the Box record.
4. Concentration: `n` * 10^-`e` (the user inputs the values for `n` and for `e`).
5. Replicate: number (normally from 1 up to 18)
6. Media: dropdown with 3 options: 
   1. Transport media
   2. Saliva
   3. Other

<img width="557" alt="image" src="https://user-images.githubusercontent.com/25181052/166696282-5da27e5f-852a-4a45-9d6e-2889b82f9ead.png">

### Invision
Note: concentration, replicate and media should be placed between Volume and Assays.

https://projects.invisionapp.com/d/main#/console/4103589/113463974/preview

### Acceptance criteria
- [ ] I create a Batch and I have the option to determine the Virus Lineage.
- [ ] I create a Sample and I have the option to determine the Virus Lineage, Concentration, Replicate, Media.
- [ ] When entering the Media, i can select 1 of 3 options: Transport media, Saliva, Other.

**Comment by leandroradusky** [comment]
Probably another field called MSDS (Material Safety Data Sheet). Format TBD.

**Comment by diegoliberman** [comment]
No MSDS field for now.

**Comment by ysbaddaden** [comment]
@diegoliberman We'd may want to add the Virus Lineage (and maybe the Media?) to the Batch, too? It could be copied automatically when creating the sample.

**Comment by diegoliberman** [comment]
> @diegoliberman We'd may want to add the Virus Lineage (and maybe the Media?) to the Batch, too? It could be copied automatically when creating the samples.

Virus lineage yes, as the virus will be the same for all samples of the same batch.  However, the media corresponds to the tube, not to the batch.  In the process of aliquoting, they decide what media will be used to dilute and transport the virus.  Samples from the same batch may have a different media.  Perhaps there is a use case where it would make sense, but I would wait for that use case to come up to the surface and fully understand it before adding this field into the batch.  

@leandroradusky do you have any thoughts about this?

**Comment by leandroradusky** [comment]
For what I understand what is as @diegoliberman says :)

**Comment by mmuller** [comment]
The fields are misaligned in version 3f8fdea

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/518152/169892357-45eb06e4-c3c8-4180-9dc0-d8c4e0647fe3.png">

**Comment by ysbaddaden** [comment]
@mmuller this was caused by the qrcode/print label using the whole column of the form. I reduced it to only use the top part of the form:

![Capture d'écran du 2022-05-24 11 18 35@2x](https://user-images.githubusercontent.com/47380/169998615-d39ef3dd-34ae-415d-b981-1726e83a6bbb.jpeg)
![Capture d'écran du 2022-05-24 11 19 46@2x](https://user-images.githubusercontent.com/47380/169998620-c75a4cd4-ee59-47b8-b43d-14b960a865e4.jpeg)

**Comment by diegoliberman** [comment]
> Is _media_ a concrete technical term? I would expect the singular form to be _medium_.
> 
> (There is also _media_ as singular form but I don't think that matches the semantics here).

I googled and it seems that both are used.  See [this](https://microbeonline.com/transport-medium-bacterial-viral-sample-transport-used-microbiology-laboratory/) example.

cc @leandroradusky

**Comment by mmuller** [comment]
Working properly in version https://github.com/instedd/cdx/commit/1ace6019d5cccc50cd836e0dbc8c7f0c4462c110
