### ISSUE TITLE
[Out] Allow to create empty batches

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1604]
As a lab technician, I want to create empty batches, so that I can select them when I'm creating a box.

Empty batches didn't make sense at first.  But now, it does make sense thinking on the physical world flow. 

1. A virus is grown in a big container, and we call this a batch.
2. We know in advance that the batch will contain N samples, and it could make sense to create the N samples at the same time as the batch.
3. However, it could be very useful to create the samples ad hoc.  Because the technician, in the physical world, won't be aliquoting (see dictionary) as soon as the batch is created.  And it's useful to create the batch in the system to acknowledge its existence, and then when needed, to add samples.  When samples are added, we'll provide the possibility of printing those sample's labels. This will fit better into reflecting real life scenarios: 1 day the batch is grown, another day some samples are aliquoted, another day more samples are aliquoted, etc.  

All of this context explanation, is just for a simple requirement:
- [ ] Remove the validation that prevents a batch to be saved without defining the quantity of samples.

Although it would be great to allow adding N samples at once from within the Batch, the current goal is to achieve a good experience for the boxes use case.  In that journey, N samples will be created automatically when a new box is saved.

### Dictionary
1. Aliquoting is the action of taking the virus from the batch, and putting it into a tube which represents the sample.  When this action is done, they could also dilute the virus which is also known as the virus to have a certain concentration.   

### Thoughts
I imagine that in the future it might be useful to allow defining the batch capacity.  And CDx could calculate how much has been already used in samples, and how much remains in the batch.

**Comment by straight-shoota** [comment]
I think the context asks for more more than just allowing the creation of empty batches.

Given an existing batch, it should be easy to create more samples. Currently, you can only add a single sample to a batch.
Considering the process of aliquoting it could also be possible to configure the volume of each created sample. Currently, the volume is fixed for all samples of a batch. Not sure if that's relevant in practice, but it seems like a sensible thing.

It's also worth considering whether metadata such as production date and lab technician need to be refined and or disambiguated between a batch and a sample.

**Comment by diegoliberman** [comment]
Perhaps those are good improvements:
1. Allow to configure the volume of the samples that are being added.  It would also require to allow adding N samples at the same time.
2. Allow to configure lab technician.  Although, if this refers to the technician that created the batch, then it makes sense to be the same for all samples.

Production date I think refers to the batch, not to when the sample was aliquoted.

But, I think batches is good enough as it is. There are other areas much weaker that need to be prioritized before we think an evolved stage of batches.  For now, removing the restriction is something that would allow a coherent chronological flow in the platform.  And I'd like to hear an actual user expressing the need, as perhaps the volume of samples is always the same for the current use cases.

**Comment by ysbaddaden** [comment]
This is a simple feature. Though it might be nice to rework the "add sample" feature to allow to add X samples at once.

**Comment by mmuller** [comment]
Working properly in version fd72912
