### ISSUE TITLE
[Out] Allow to print box labels - by steps

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1607]
Option of controlled printing: by steps.  Perhaps, like a wizard: next, next, next (step 1 of N, step 2 of N, etc).
1. The first step will be printing the box's label.  
2. The second step will be printing the samples that belong to the first batch that was selected.  `You are printing labes for samples from batch ID xxxxxx`.
    1. Sub-step for printing at each concentration.  `You are printing the concentration 10^N`.
3. The third step will be printing the samples that belong to the second batch that was selected, and so on, until printing all sample's labels. 

The idea of this feature is that it will allow the technician to organize the labels easily.  They could place the labels in little bags, and add a post-it with the batch ID and concentration.  This way, it will be very easy for them to match the labels with the tubes and the correct virus at the correct concentration.  It will be less error-prone. 

### Context
Remember that the labels don't inform what batch they belong to, nor the concentration.  Perhaps, in the future, we could allow the user to define that they want the label to include this information.  This way, they could print all the labels at once.  But in the current use case that we want to address, samples need to be blind, so we need to control who can see the sample's attributes.

**Comment by straight-shoota** [comment]
We need to be careful about terminology: "batch" here seems to have a different meaning than in #1604

**Comment by straight-shoota** [comment]
Just an idea that popped into my head while reading the context description: It could be an option to print an identifier (such as a number, letter or symbol) that's unique within at least the current process of creating a box.
Then you could have a clear mapping between the identifier and sample information. But the identifier won't disclose the information directly.

**Comment by diegoliberman** [comment]
> Just an idea that popped into my head while reading the context description: It could be an option to print an identifier (for example a number, letter, symbol, or color) that's unique within at least the current process of creating a box. Then you could have a clear mapping between the identifier and sample information. But the identifier won't disclose the information directly. The identifier would still identify samples from the same batch, so that might be a dead end.

I see.  Kind of a secret message.  Not sure if the printers can handle colors other than black & white.  But batch IDs are dynamic, how would we add a code that the technician can mentally map to a certain batch? If they need to check something digitally, then I don't like it, as in that case, I would rather guide them to search the sample ID in the list of samples.

**Comment by straight-shoota** [comment]
I understand that here "batch" means a group of tubes containing/to-be-filled-with the same sample material in a box. That sample material comes from a batch as defined in #1604, a supply kept in store and used to aliquot into tubes.

**Comment by diegoliberman** [comment]
What I tried to express in this issue, is that the samples will be printed in certain order.  When I'm mentioning `batch`, I'm actually referring to the samples that belong to the first/second/etc batch that was selected.  I have re-written that sentence, hopefully it's more clear now.

But basically, in this form, we select batches from the list of batches, and then we sort the printing according to which sample was selected first, second, etc.

**Comment by diegoliberman** [comment]
Work item deleted in Commit
