### ISSUE TITLE
Allow to transfer boxes

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1610]
As a delivery responsible, I want to easily transfer a Box of samples, so that I can send the materials to the requester institution.

In the same way we are allowing to transfer samples, we can also allow to select a box.  Samples won't be transferred directly, only through a box.

The transfer action moves the samples records & box records to the recipient institution.

### Mock up
![image](https://user-images.githubusercontent.com/25181052/167026572-d308c0cd-a9ec-46d3-976a-da8a208b1203.png)

### Invision
https://projects.invisionapp.com/d/main#/console/4103589/465275290/preview
And see subsequent screens

**Comment by straight-shoota** [comment]
For this we'll need a table to express a many-to-many relationship between `TransferPackage` and `Box`. A `TransferPackage` can contain multiple boxes and a `Box` could be transferred multiple times - at least theoretically. I think it makes sense to use this model just to be future proof. It isn't really more effort than a one-to-many relationship.

Lately, `SampleTransfer` has served this purpose for transfers of individual samples. It doesn't really serve any other purpose any more. It was originally created to keep track of transfers, but that role has been taken over by `TransferPackage`. We can probably drop `SampleTransfer` entirely after the transition to transferring boxes.

**Comment by straight-shoota** [comment]
@diegoliberman How are we going to handle QC samples with box transfers? Do we need to check for QC samples when transferring a box? Or should it already be impossible to add QC samples to a box?
I think the latter might make more sense. There should be no reason to have QC samples in a box, when the purpose of boxes is being transferred, right?

**Comment by ysbaddaden** [comment]
We can't add arbitrary samples to a Box, yet, so it's not a problem _now_.

But when we implement the 'Other' purpose, we'll have to deal with it, yes.

**Comment by straight-shoota** [comment]
Yes, we'll have to implement that *now* in order to migrate transfer packages to transfer boxes instead of samples.

**Comment by diegoliberman** [comment]
We should restrict QC samples from being added to a box.  Whenever it's convenient implementation wise.  Just in case, I added this consideration in #1619.
