### ISSUE TITLE
Allow to add in a box: individual samples

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1619]
When the box's purpose is `Other`, we should allow to add existing samples to the box.

### Story
As UCSD, I want to create a custom box for transferring some specific samples, so that I can keep track of what happened with these samples.

### Acceptance criteria
1. I select the `Other` purpose.
2. I can see a field for entering a sample ID, I'll call this field `Find ID`.
3. If 1 or more non-QC samples match with the **partial** ID of the previous step, I can confirm which one I want to add and it gets added to a list of samples being added to the box.  After confirming, the focus moves back to the `Find ID`.
4. I can continue adding as many samples as I want.
5. If a non-QC sample matches with the **complete** ID of step 2, the sample gets added automatically and the focus is placed again in the `Find ID`.
6. I can save the box.

### Invision
https://projects.invisionapp.com/d/main#/console/4103589/466673800/preview

**Comment by mmuller** [comment]
Working properly in version e452dd3
