### ISSUE TITLE
[Out] Calculate the truth of samples

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1621]
At this point, there will be a field named Truth that is selected manually by the user in each sample.

Now, with #1603, we have a new field named Concentration.  In order to calculate the truth for the sample, we need another field named Threshold.  For the moment, both Concentration and Threshold will be entered manually by the user.  

The logic for the truth is simple: if the concentration is greater than the threshold, then the truth is POSITIVE.  Else it's NEGATIVE.

The user won't be able to continue defining the truth manually, at least not in a direct way.  They will have to enter the threshold and the concentration.

**Comment by straight-shoota** [comment]
At which point is this truth value needed? For example, if it is mostly for reporting, it would be pretty simple to integrate into the reporting interface and only calculate at the time the reporting happens. Then we wouldn't need to attach this value to individual samples and could simply skip the manual user input.

**Comment by diegoliberman** [comment]
I totally agree.  I wrote a series of stages for calculating the truth.  Your suggestion was exactly the last stage of that plan. 
 We need to start with the easiest one, and then see if there's time left for enhancements.

**Comment by straight-shoota** [comment]
If we only need that value for the report and it's acceptable to input the value there, then this would be by far the easiest implementation. No leading steps necessary.

**Comment by leandroradusky** [comment]
@diegoliberman after analysis this was going to be defined at reporting time and this issue should be closed.

**Comment by diegoliberman** [comment]
Work item deleted in Commit
