### ISSUE TITLE
[Out] Allow to administer virus types

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1622]
Perhaps even consider that there is hierarchy of virus and then virus types, for instance:
Virus: SARS-COV2
Virus type: Omnicron

We should define if the virus type are going to be cross-CDx, or administered per institution.   If it's per institution, we need to think what happens when a sample is transferred to another institution, as the virus type of the sample will be linked to a record that belongs to a different institution.   Also, it smells bad to allow creating the same virus types for different institutions.  Probably, the best would be to have a highlevel cross-CDx list of viruses, as we have for LOINC codes.

**Comment by leandroradusky** [comment]
An a 3rd hierarchy was mentioned in the documents: Virus lineage (i.e. B.1.23)

**Comment by diegoliberman** [comment]
Work item deleted in Commit
