### ISSUE TITLE
Remove/Refactor *Transfer Samples* modal workflow

### ISSUE THREAD

**Issue by straight-shoota** [instedd/cdx#1626]
#1566/https://github.com/instedd/cdx/pull/1625 do not remove the old *Transfer Samples* modal on the samples index page. The implementation of the new workflow is completely unrelated, thus removing the predecessor should be a separate step.

We could also consider adapting the existing workflow to work with the new *Transfer Package* form: Selected samples on the samples index would be pre-filled in the form.

*Select samples in list and click send button:*
![grafik](https://user-images.githubusercontent.com/466378/165474689-96448cc8-390a-4b55-97ff-38c1aa5365b5.png)

*Pre-filled form:*
![grafik](https://user-images.githubusercontent.com/466378/165474819-b34006bb-595a-44f7-95b7-33162f0c2413.png)

Not sure if there's a reasonable use case for that. It would be easy to implement.

**Comment by diegoliberman** [comment]
For now, let's please remove the transfer action from the list of samples.  Let's see wait to see some real life action with the new transfer flow, and then yes we can further enhance what makes sense.
