### ISSUE TITLE
Error when attaching a file for an Assay within a Sample

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1633]
### Steps
1. Create a new sample
2. Attach a file within the Assay section
3. A 500 error appears in the console.  The save button gets disabled.

PS: It works fine in Staging, the error is in Prod.

![image](https://user-images.githubusercontent.com/25181052/166507912-abcf65e1-fdd4-4cf6-b58b-58633cabb8a5.png)

**Comment by diegoliberman** [comment]
![image](https://user-images.githubusercontent.com/25181052/166508759-b57fd1f3-8ee4-44b1-90d4-e2ac3ebc2942.png)
![image](https://user-images.githubusercontent.com/25181052/166508804-b04f377e-a7a6-460d-9c66-478cfc588e69.png)
![image](https://user-images.githubusercontent.com/25181052/166508837-6b8a656c-41de-42b8-9850-d2205fa039c7.png)
![image](https://user-images.githubusercontent.com/25181052/166508861-49964e8b-c349-4c00-8729-a9aecb00dca1.png)
![image](https://user-images.githubusercontent.com/25181052/166508897-18ca582f-eacf-4faf-afe5-e40b647c43a4.png)

**Comment by diegoliberman** [comment]
I have already tested this in Prod and works fine.  The QA for this ticket is just making sure that it works fine in Staging as well.

**Comment by mmuller** [comment]
Working properly in version fd72912
