### ISSUE TITLE
Error when printing/deleting multiple samples at once

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1634]
### Steps
1. In the samples list page, select more than 1 sample.
2. Print.

### Expected a result
A PDF with 1 sample per page.

### Actual result
A PDF with the only 1 sample's label, from the ones that were selected, the one that appears last in the list.

![image](https://user-images.githubusercontent.com/25181052/166510072-61189449-7a5b-4f5d-ad80-de1d2cb76d1a.png)

### Deleting
Same experience

**Comment by straight-shoota** [comment]
This error is pretty interesting: It seems to be caused by using GET method to submit the form. Changing to POST makes it work. Apparently, the form serialization doesn't account for multiple checkbox values in a GET request. It results in query data like `sample_ids[]=5` instead of `sample_ids[]=4&sample_ids[]=5`.

**Comment by straight-shoota** [comment]
After fixing the method, the print action errors with #1645.

For the delete action, there is some copious client-side javascript code for showing a confirmation dialog. Apparently, that breaks the method configuration and results in sending a GET request instead.

**Comment by mmuller** [comment]
In version fd72912, I am obtaining a PDF with 3 pages per sample.

**Comment by ysbaddaden** [comment]
It's working as expected with #1650 and #1658 in development.

**Comment by mmuller** [comment]
Thanks @ysbaddaden

**Comment by ysbaddaden** [comment]
Note that I don't know why it didn't work, and I didn't fix anything specifically. It just happens to be working in development :shrug:

**Comment by ysbaddaden** [comment]
The problem wasn't fixed, and only appeared in the production environments (staging, production): WickedPDF failed to find and inline the precompiled assets (CSS, logo), which resulted in the CSS not being applied.

I have a fix in 61878987
