### ISSUE TITLE
Error on db:migrate when pulling main branch

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1636]
When pulling `main` branch, the pending migration error is shown and `bin/rake db:migrate RAILS_ENV=development` is asked to be run. But when the command is run the following error is thrown:

```
StandardError: An error has occurred, all later migrations canceled:

SampleTransfer#sender_institution delegated to transfer_package.sender_institution, but transfer_package is nil: 
#<SampleTransfer id: 1, sample_id: 2, sender_institution_id: 1, receiver_institution_id: 8, confirmed_at: "2022-03-18 15:48:31", created_at: "2022-03-18 11:07:43", updated_at: "2022-03-18 15:48:31", transfer_package_id: nil>/src/app/models/sample_transfer.rb:20:in `rescue in sender_institution' 
```

**Comment by straight-shoota** [comment]
I added in `SampleTransfer#sender_institution` as an alias in order to keep backwards compatibility. But that breaks in an intermediate state, when a `SampleTransfer` is not yet associated with a `TransferPackage`.

We can probably drop the delegation to fix this.

**Comment by ysbaddaden** [comment]
Or access the column value with `[]` instead of using the attribute?

E.g. `record[:column_name]`.

**Comment by straight-shoota** [comment]
@ysbaddaden Yeah, I fixed it like that (just with `_id` attributes) in #1637.
