### ISSUE TITLE
Allow to define the Media when creating a box

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1673]
### Context
When the Awardee requests materials, they also inform what’s they preferred media.  So there are use case where all the samples within a box will have the same media.

### Story
As UCSD I want to define the Media that will be used for all samples within a box I'm creating, so that the Awardee can confirm that they received the samples within the Media they requested.

### Acceptance criteria
1. When creating a box, I see a field for selecting the Media.  This field is optional.
2. After saving the box, all samples that were created for the box, have the Media that was selected.
3. When the box's purpose is Other, the Media field is hidden.

**Comment by mmuller** [comment]
Working properly in version https://github.com/instedd/cdx/commit/1ace6019d5cccc50cd836e0dbc8c7f0c4462c110
