### ISSUE TITLE
Error when printing samples from the Batch view

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1678]
### Steps
1. Access to a batch that has several samples.
2. Select 1 or more samples.
3. Press the print icon.
4. An error is raised.

### Button
<img width="713" alt="image" src="https://user-images.githubusercontent.com/25181052/169889273-51307e92-70f0-425e-8aad-43cf156cdd74.png">

### Error
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/25181052/169889378-ea8e542e-84c2-43e2-aabd-f2b576995ad3.png">

**Comment by mmuller** [comment]
Working properly in version 1ace601
