### ISSUE TITLE
Add creation date in the list of boxes

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1684]
Perhaps it isn't frequent to have multiple boxes created on the same date.  But there is room for adding more columns and at least for the purposes of testing it would be useful to easily identify boxes.  I would add a column with the creation date & time of the box.  Sort should be descending by creation date.  

![image](https://user-images.githubusercontent.com/25181052/170036676-954a6558-67d8-4abc-b42f-b7dde60c34a6.png)

**Comment by diegoliberman** [comment]
@jkicillof please follow this issue and if we get to implement it, update the design.  Thanks!

**Comment by ysbaddaden** [comment]
Good idea, and easy to add. Let's do it.

**Comment by mmuller** [comment]
Working properly in version https://github.com/instedd/cdx/commit/1ace6019d5cccc50cd836e0dbc8c7f0c4462c110
