### ISSUE TITLE
[BUG] When accessing some transfers in transit an error is thrown

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#1708]
**Found in version:**
f1b71ab

**Steps to reproduce:**

1. Create a box `B1`.
2. Transfer the box `B1`.
3. As admin of the receiving institution, navigate to the transfers listing.
4. Click on the transfer of the box `B1`.

**Obtained result:**
- In this case, an error (403) is thrown.
- In other transfers, an internal server error is thrown.

**Expected result:**
- The transfer details view is displayed

**Additional information:**
- Other transfer in transit doesn't throw an error

**Comment by straight-shoota** [comment]
I can't reproduce this, but I think I know what's going on.

**Comment by straight-shoota** [comment]
Yeah, I'm pretty sure it was a typo using `authorize_resource` instead of `authorize_resource?`. The latter just returns a boolean while the former responds with not-authorized.
