### ISSUE TITLE
[BUG] Error when printing an individual sample label

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1712]
### Steps to reproduce the error
1. Open an individual sample
2. Click the print action
3. The file won't get downloaded and an error will show up "Failed - No file".

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/25181052/173448297-3b4611a4-d54d-4cd2-a2da-fdfab4e555fe.png">

### Version
Version: dev-01802a4 (build 1580)

**Comment by ysbaddaden** [comment]
Yeah, the link is completely broken:

```
https://cdx-stg.instedd.org/samples/%23%3CSamplePresenter:0x007f291a37a380%3E/print?context=b2892c86-b103-0e64-5180-8d20d47c84f3
```

**Comment by straight-shoota** [comment]
This could easily be covered in a simple spec.
