### ISSUE TITLE
Improve performance of the print PDF actions

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1723]
The current implementation required to changed a server timeout.  See this [thread](https://github.com/instedd/cdx/issues/1715).

The goal of this ticket is to improve the performance, if possible, to avoid future problems in scenarios that may have more than 108 samples for printing.  The most likely use cases are:
1. There is a new box's purpose that requires more than 108 samples.
2. The user creates a batch with more than 108 samples and decides to print all by selecting all samples and printing from the batch detail.

**Comment by ysbaddaden** [comment]
Marked as both an enhancement (optimize the PDF generation) and a bug (can't handle more than N samples).
