### ISSUE TITLE
1- Enable printing label for recipient of a sample

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1724]
Today, the print action that we have in Sample Detail
<img width="532" alt="image" src="https://user-images.githubusercontent.com/25181052/173886233-e34e225d-576f-46c9-9be4-ba0d09eb5732.png">

Gets hidden when the sample has been received from a transfer
<img width="984" alt="image" src="https://user-images.githubusercontent.com/25181052/173886323-fa13e483-5652-4dd8-8a63-5a1fbb8e8354.png">

We don't need to hide it, so let's remove that unnecessary logic.

**Comment by ysbaddaden** [comment]
**Warning**: make sure to blind the attributes in the generated PDF if the box is blinded!

**Comment by diegoliberman** [comment]
> **Warning**: make sure to blind the attributes in the generated PDF if the box is blinded!

Yes, that will be done in #1720, when the Isolate Name gets blinded as well.

**Comment by ysbaddaden** [comment]
Yes, but the values must be blinded in the views (by wrapping samples in SamplePresenter), so we musn't forget to do it for this view :)
