### ISSUE TITLE
2- Enable printing box and sample labels for the recipient of a box

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1725]
The recipient of a box don't get to see the Print action within the box detail.
<img width="499" alt="image" src="https://user-images.githubusercontent.com/25181052/173886927-bf2da964-15e9-4619-9b35-c905d372931f.png">

We should show them the action, BUT, the order that the labels are printed, should be the same order that we use for listing samples in the `Download inventory` action. 
For the Sender (author) of the box, the order should be: by batch, concentration and replicate.
For the recipient of a box, IF the transfer was blinded, the order should be by UUID.

### Acceptance criteria
1. Both sender and recipient of a box, get to see the print action in the box detail.
2. The sender can **download the inventory** and **print the labels**.  Samples are ordered by batch, concentration & replicate in the inventory and in the PDF.
3. The recipient do the same but 
   1. If the transfer was blinded, the order is by UUID.
   2. Else, the order is the same than for the Sender.

**Comment by ysbaddaden** [comment]
**Warning**: some sample attributes should be blinded if the box is blinded!

**Comment by diegoliberman** [comment]
> It could be interesting to consider the sender case when the box isn't blinded, and the receiver case when the box is blinded. Receiving a box doesn't mean that the samples are blinded, and we don't need to scramble the order (thinking in terms of a generic feature).
> 
> **Warning**: some sample attributes should be blinded if the box is blinded.

Excellent observations Julien.  I have added a consideration for ordering by UUID only if the transfer was blinded.
