### ISSUE TITLE
3- Blinding changes: same fields for all box purposes

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1726]
Right now, we are blinding different fields depending on the box purpose.  We should remove this logic, we'll be blinding the same fields for all box purposes.

The fields that need to be blinded are:
1. Batch
2. Virus lineage
3. Isolate name
4. Concentration
5. Replicate

Here's an example of what blinding means (for the recipient of a transfer):
<img width="541" alt="image" src="https://user-images.githubusercontent.com/25181052/173893699-90a19c41-0173-47e0-847d-e18de9f26ba8.png">

### Acceptance criteria
1. After transferring any type of box, the mentioned fields will be blinded in the:
   1. Sample Detail
   2. Box inventory CSV

**Comment by ysbaddaden** [comment]
Said differently: we should always blind the same list of attributes, independently from the box purpose.

**Comment by diegoliberman** [comment]
> Said differently: we should always blind the same list of attributes, independently from the box purpose.

Incorrect.  For LOD we don't need to blind Virus Lineage, Batch nor Isolate Name.

**Comment by diegoliberman** [comment]
@ysbaddaden I changed the approach of this issue.  The blinding per box purpose goes against future changes in boxes.  So now, we will be blinding regardless of the purpose, exactly as you suggested.

**Comment by mmuller** [comment]
Working properly in version 7757444
