### ISSUE TITLE
Add Culture media

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1730]
In the box form, add the option to select "Culture media" in the "Media" field.  Sort the options alphabetically ascending, but keep "Other" as the last option.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/25181052/175038785-2786aed6-3190-45e1-a625-13585cc9c8ac.png">

**Comment by omelao** [comment]
Where does the data for the options in this field come from?

**Comment by straight-shoota** [comment]
https://github.com/instedd/cdx/blob/main/deps/cdx_core/lib/config/fields.yml

**Comment by ysbaddaden** [comment]
This is part of the [Entity Framework](https://github.com/instedd/cdx/wiki/Entity-Concern-Framework) of CDX (it has nothing to do with Rails). It allows to declare some additional metadata about model attributes.

**Comment by omelao** [comment]
So...if I need to sort alphabetically ascending, I just need to change the order of this lines? Does this imply any problems in the places where it has already been filled?

**Comment by mmuller** [comment]
Working properly in version 7757444
