### ISSUE TITLE
Reprocess device events when manifest changes

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#175]
When changing the manifest for a device model, look for all the devices with the same device model, delete all its events and reprocess all its device events

**Comment by nekron** [comment]
The current subscriber model will trigger all the subscribers for those events. We should rethink this and for now don't try to resend a test after updating the manifest.

**Comment by spalladino** [comment]
Use device model id as the document type in ES instead of manifest id. Remember to regenerate the type mapping in ES based on the new manifest.
