### ISSUE TITLE
Change the concentration field from scientific notation to float

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1752]
The current scientific format for entering the concentration used to make sense when preparing a very specific set of samples.
![image](https://user-images.githubusercontent.com/25181052/184214255-89112b23-bfa8-4179-8194-af9b51c6488f.png)

For concentrated samples, there are may be concentrations that aren't well represented with a scientific notation.  We need to implement an alternative that can be more flexible.  Hence, the proposal to remove those 2 fields and leave just 1 with the concentration, which can be a float.

- [ ] Change the field in the sample form.
- [ ] Consider the change in the script that creates samples from a box submission.
- [ ] Consider the change when downloading a box inventory.
- [ ] Consider if we need to do any data migration.

**Comment by diegoliberman** [comment]
@leandroradusky what's the maximum concentration value we could get?

**Comment by leandroradusky** [comment]
Concentration can be expressed in two flavors: 

- as a fraction between zero and one. E.g. imagine that in the glass there is 100ml, and then I make mixes of a red liquid and water putting a 5% or red liquid (5/100 = 0.05, or 5*10^-2), 10%, 20%, etc...

![image](https://user-images.githubusercontent.com/13782680/184330186-ed3135c6-8196-4972-810b-8549e4c66076.png)

In this case the values range between zero and one, If all is red liquid the concentration is 1.

- **Or** as parts per something (per mill, per million, per billion, etc.), where you express the concentration as an **integer** and leave the divisor implicit.

![image](https://user-images.githubusercontent.com/13782680/184325740-bfd52ca0-8c38-43ee-9316-4008a21c52f4.png)

In the firsts versions of Yves spreadsheet they were expressed as fractions (10e-2, 10e-4, 10e-8, ...) but they changed the units to **copies per ml** (copies of the inactivated virus per milliliters in the sample). Then, the new value of the concentration will be a positive integer.  Could be a long integer, ranging from units to millions of copies. The values that they shown in the emails are in the order of the thousands of copies but hundreds of thousands or even millions can be expected.

**Comment by diegoliberman** [comment]
A misunderstanding came up to the surface yesterday.  They're happy with using the scientific notation, but they want us to remove the fixed minus sign in the equation.  They also want to be able to enter any float number for the first value and any integer for the exponent (including zero and negative numbers).

![image](https://user-images.githubusercontent.com/25181052/184348812-e26d42bc-4869-4722-b050-8bcd29b3317c.png)

This way, they can define concentrations with more flexibility such as:
1. For 1536 they could do 1536 x 10^0; or 1.536 x 10^3 which is also 1536.
2. Similarly for a concentration of .001536 you would enter 1.536 x 10^(-3).

**Comment by diegoliberman** [comment]
Work item deleted in Commit
