### ISSUE TITLE
Data type conflicts while indexing custom fields from different devices

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#176]
If two devices report test results with the same sample_uid and their respective manifests declare the custom fields with the same name and different data type, there will be a conflict adding that to ES.

**Comment by nditada** [comment]
The issues here are two as far as I can understand: 1) custom fields from different manifest are NEVER the same, regardless of having the same name. 2) custom fields should not be indexed and can only be retrieved for single tests.

**Comment by nekron** [comment]
See #159

**Comment by nditada** [comment]
putting this on hold until we find real examples of clashing.

**Comment by nekron** [comment]
Custom fields are now being stored but not indexed, there is no more risk of clashing.
