### ISSUE TITLE
Recover specs

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1767]

**Comment by ysbaddaden** [comment]
@diegoliberman do you have any description?

**Comment by diegoliberman** [comment]
> @diegoliberman do you have any description?

@ysbaddaden from the [commit](https://github.com/instedd/cdx/commit/98bafc0d7c69f7ffc2d34df5d14f54822bfacc3c) I referenced, there are several messages mentioning specs.  Perhaps it's worth keeping them.  I'm not sure, perhaps with all the future changes that are coming, these specs don't make sense anymore.

**Comment by diegoliberman** [comment]
There were some tests recovered, and 1 removed.
