### ISSUE TITLE
Allow to edit the box: just the blind check box

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1772]
See the section `Logic for editing boxes` in #1755

**Comment by ysbaddaden** [comment]
:warning: There is a permission issue: for the policy system the owner of a resource is allowed to edit it; this is no longer true for boxes!

There are no issues until the box is transferred: the owner of the box is the sender and is allowed to transfer it. But once the box is transferred (i.e. the box belongs to transfer package) the owner of the box will be the receiver institution, and its users musn't be allowed to edit/unblind the box: only the sender institution shall be allowed to!

**Comment by diegoliberman** [comment]
When the implementation time comes, let's discuss in detail. This requirement isn't a deal breaker, so we may even cancel it, if it will require a big effort.

**Comment by ysbaddaden** [comment]
No, we just need to be careful.

**Comment by omelao** [comment]
We just need to enable this for the first owners. For boxes not yet transferred, right?

**Comment by sardar-usman** [comment]
@omelao It's working fine as expected.
