### ISSUE TITLE
Samples can be in only 1 box at a time

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1774]
Today, if you add a sample to a box, and you try to add it to another box, the system allows it, and the samples remain in the new box.  This is a problem because they could use this trick to unblind a sample, as the blind check is in the box.  

When adding samples to a box, if the sample is already part of another box, the system should show an error message saying that the sample can't be added as it belongs to another box and show the id of that box.

In the future, we will allow to edit boxes, so the user will be able to remove the sample from the original box and then yes, add it to the new one.

**Comment by sardar-usman** [comment]
@omelao It is working fine as expected.
