### ISSUE TITLE
Changing the sources empties the contents

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1778]
If the samples source is change to `Create new samples` or `Select from inventory`, the system shows a warning message and after confirming, the contents are emptied.

https://projects.invisionapp.com/d/#/console/4103589/470324049/comments/149800275

**Comment by omelao** [comment]
Is there already any pattern for this message “window”?

**Comment by diegoliberman** [comment]
Yes, when deleting a sample for example.

![image](https://user-images.githubusercontent.com/25181052/200876292-f609c681-eb4d-4c27-8daa-88bf705392cb.png)

**Comment by cclopez78** [comment]
@ysbaddaden IIRC yesterday at the IP you mentioned that Muhammad found a bug and reported it separately, so this issue could be considered done, and we could just follow the pending work on the bug-issue. Can you confirm (please add a reference to the bug-issue) and move this issue in the board accordingly, if applicable, please? Thank you in advance!

**Comment by ysbaddaden** [comment]
@cclopez78 I believe it's #1851 ?
