### ISSUE TITLE
Support lookup of device information in manifest

### ISSUE THREAD

**Issue by spalladino** [instedd/cdx#178]
Allow device, laboratory and location information lookup in manifest. Useful for composing `sample_uid` as a combination of `sample_id` and `laboratory`.

**Comment by nditada** [comment]
Only support this in embedded javascripts for the manifests, no need to support it in json.

**Comment by nekron** [comment]
Add also a way to access DateTime.now

**Comment by asterite** [comment]
@nekron You can do `new Date()` in javascript and it works out of the box. Is this enough? Or what's the use case?
