### ISSUE TITLE
Fix UI glitches in the settings of roles and policies

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1785]
#Steps to reproduce the glitch
1. WIth an admin user, go tot he settings menu
2. Go to the Roles section
3. Access the role detail page for any role
4. Click on a policy
5. Scroll down to the bottom --> GLITCH! You will be automatically scrolled back up to top of the page.

https://user-images.githubusercontent.com/25181052/219039468-0b276800-92c7-4f0d-9da9-71567432a7e8.mov

**Comment by ysbaddaden** [comment]
@diegoliberman could you add some details?

**Comment by diegoliberman** [comment]
> @diegoliberman could you add some details?

Done

**Comment by ysbaddaden** [comment]
Oooh right. That rings a bell.

**Comment by sardar-usman** [comment]
@bolom It looks good, working as expected.
