### ISSUE TITLE
Replace abandoned 'therubyracer' gem / XML device message parser

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/cdx#1790]
The `therubyracer` gem has been abandoned for years, and uses a very old version of V8. We use it compile assets, so we can replace it with anything, but it appears we also use it to run arbitrary code to parse manifest fields (see `ManifestFieldMapping`).

**Comment by ysbaddaden** [comment]
Syntaxes are basically the same between `mini_racer` and `therubyracer`: just eval each variable instead of augmenting the context with values, ... and that would have been super easy to migrate, if not for one edge case:

```
  1) Manifest operations loads xml in javascript
     Failure/Error: raise ManifestParsingError.script_error(@field.target_field, e.message)

     ManifestParsingError:
       Error executing script while mapping the field 'patient.name': TypeError: message.xpath is not a function
     # ./app/models/manifest_field_mapping.rb:141:in `rescue in run_script'
```

We actually expose a wrapped `Nokogiri::XML::Element` object to JavaScript. The script itself is basically calling Ruby code from JavaScript, with automatic binding of Ruby objects (with methods) as actual JavaScript objects. This is bad**, like **very bad**: we're exposing bare ruby objects to be accessible from a user controlled environment: 

1. We don't control the exposed API. It's a Nikogiri::XML::Element and then anything that the methods on the object (e.g. `message.xpath` returns an Array of other elements or attributes or whatever): we can't migrate from the nokogiri or `therubyracer` gems.

2. `mini_racer` won't map non trivial objects, unlike `therubyracer`, so we can't replicate this behavior. We must provide a limited API for parsing XML, or return trivial objects.

Note: other parsers (JSON, CSV) are fine because they return trivial objects (Array, Hash, String, Number).

**Comment by ysbaddaden** [comment]
@matiasgarciaisaia could you extract the definition of device manifests? It's a mere TEXT column with JSON content. Then I shall be able to determine _if_ we use the XML parser in the wild, and if we do, what is currently used, and see if we could migrate/correct (or implement a new, limited, API).

```sql
SELECT definition FROM manifests;
```

**Comment by ysbaddaden** [comment]
After looking into production databases, we couldn't find any device manifest of type `xml` with arbitrary `script` field mapping ops (only `lookup` ops).

Let's evolve this feature to pass a pre-parsed `message` as a trivial Array / Hash structure.

**Comment by ysbaddaden** [comment]
As per #1791 we now pass a trivial data structure, yet still expose `message.xpath(query)` as a custom function, that allows to query anything in the XML, returned as a trivial data structure.

**Comment by diegoliberman** [comment]
Let's wait until January to merge this, so that we send it to production when Julien is back from vacations.
