### ISSUE TITLE
Inventory ordering is broken when the sample concentration is manually modified

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1800]
1. Create an unblinded box
2. Find 1 of the samples and modify its concentration to whatever
3. Download the inventory and you'll see that the ordering isn't updated, the sample remains at the position it used to be with the previous concentration.

Reminder: unblinded inventory is ordered by batch, concentration and replicate number.

### Test cases for Blinded boxes
It should order by sample UUID

- [ ] LOD box
- [ ] Variants box
- [ ] Challenge box

### Test cases for Unblinded boxes
It should order by batch, concentration, replicate

- [ ] LOD box
- [ ] Variants box
- [ ] Challenge box

### Bonus
Let's take the opportunity to place the columns in a more logic order.  `Concentration` should be to the left of `Replicate`

### Screenshots
![image](https://user-images.githubusercontent.com/25181052/202293991-bfdb1edf-5989-4e3e-b67b-f7b64897bbde.png)

The challenge shows that the ordering by batch is also broken
![image](https://user-images.githubusercontent.com/25181052/202296556-4492e895-bd23-45ec-b45f-9ca6b062f326.png)

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine now.Cc @diegoliberman
