### ISSUE TITLE
Upgrade to Ruby 2.4

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/cdx#1806]

**Comment by diegoliberman** [comment]
Let's wait until January to merge this, so that we send it to production when Julien is back from vacations.

**Comment by ysbaddaden** [comment]
@sardar-usman This is on staging. You might want to try a bunch of things everywhere, to verify we didn't break anything. I'm quite confident that we didn't (there is a good test suite), but :shrug:

**Comment by sardar-usman** [comment]
@ysbaddaden I have performed the smoke testing and things are good. Nothing is broken, everything is working fine.
