### ISSUE TITLE
Bug when migrating the concentration

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1817]
This concentration:
![image](https://user-images.githubusercontent.com/25181052/205945857-0de03361-bbb3-454b-8fd8-0330b11cfbf3.png)

Was migrated to `1000` when the correct value is `10`.

This concentration
![image](https://user-images.githubusercontent.com/25181052/205946166-2df28af5-47d5-4cfc-82b0-ecb8379c8adf.png)

Was migrated to `10330000` when the correct value is `10.33`.

### Game plan for Demo
Consider that the data has already been migrated there.  I think we don't need to worry about this.  I don't care what's the final concentration for those 2 test cases I created. 

### Game plan for Local
Consider we're dealing with data and we need to be careful. You should setup a local environment with the current production version, create a few samples, and then upgrade + run the migrations.  And check that the concentrations were correctly transformed.  What I don't know, is what happens with the current buggy migration: do we have to create a 2nd migration that fixes the error of the first one? Do we create a new migration that replaces the buggy one? 

### Game plan for Production
We'll have to talk with the team. Do we add the fix into the current release? Do we create a new release?

**Comment by ysbaddaden** [comment]
@diegoliberman we junk the current release and create a new release.

**Comment by diegoliberman** [comment]
@ysbaddaden last time something like this happened, we created a new release, and added a comment in the bad one saying that we never deployed that to production: https://github.com/instedd/cdx/releases/tag/0.21.0
