### ISSUE TITLE
Keep uploaded batches information if SamplesReport creation throw error

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1845]
Example: When creating a Challenge box where, minimally, we need to have a virus and a distractor batch. If we don't include them, then we`re losing all the uploaded batches/samples/concentrations info and I have to go with creating new samples from scratch:

![image](https://user-images.githubusercontent.com/13782680/213242707-e7ce4ad7-e583-496e-8851-f315b2aa1709.png)

Keeping the information of the uploaded batches will avoid having to redefine them.

**Comment by sardar-usman** [comment]
@ysbaddaden Now it keep the uploaded batches information, if SamplesReport creation throw error. Working as expected.
