### ISSUE TITLE
Allow to reopen batch details when creating a box

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1846]
Now we cannot "reopen details" for defined batches to check if we made a mistake when defining them. 
In the picture below, all the definitions for batch 12 remain hidden and we cannot see them. Let's suppose that we don't recall if we made it a distractor or not, or, that we forget to make it a distractor and we want to change that: once we press "Add" there is no step back nor to change neither to check... Given that boxes will be quite sophisticated can be improved:

![image](https://user-images.githubusercontent.com/13782680/213244223-74c2cbba-7d93-4f3c-8b46-727dc75569f1.png)

**Comment by sardar-usman** [comment]
@ysbaddaden It is working as expected.
