### ISSUE TITLE
Warn the user that defined replicates were not confirmed when adding new batch to box

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1847]
When creating a box, if pressing the "Add button" for this batch:

![image](https://user-images.githubusercontent.com/13782680/213244933-88df4d1c-8b10-4702-9b59-97046caacdf7.png)

Will provoke losing the 2 replicates of 40 copies/ml since we didn't press the blue check... While it's correct, could provoke unwanted errors, add a warning message.

**Comment by diegoliberman** [comment]
Work item deleted in Commit
