### ISSUE TITLE
Improve the Locations tree in the Laboratory view

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#185]
Found in version: 20150318.190402-c0469e9

Steps:
Go to the Laboratories listing
Press the Create Laboratory button or go to edit some Laboratory
Expand the drop down list of Locations

Obtained:
The Locations cannot be found easily

Expected:
Nice to have something like a search input field

![screen shot 2015-03-18 at 7 47 14 pm](https://cloud.githubusercontent.com/assets/518152/6721201/4f387578-cda9-11e4-86a4-847eaa1739ab.png)

**Comment by nekron** [comment]
fixed in 356eaf9

**Comment by mmuller** [comment]
Ok in Version: 0.4-pre5
