### ISSUE TITLE
Reduced the Space in Result Upload Error pop up screen.

### ISSUE THREAD

**Issue by sardar-usman** [instedd/cdx#1851]
Steps that you should follow in order to see the bug, ie.
1. Go to 'Samples' page.
2. Click on 'Upload Result' button.
3. Click on 'Add file' button.
4. A pop up appeared.
5. There is lot of space between "Skip Invalid IDs" and error message.
 
**Expected**

Pop screen should be according to figma.
<img width="978" alt="Screenshot 2023-01-20 at 5 00 12 PM" src="https://user-images.githubusercontent.com/45853972/213760158-d882dbbe-f3f7-45da-9e6f-3670d4f7b775.png">

**My setup**

- Device: Laptop
- OS: macOS
- Browser: Chrome

**Comment by ysbaddaden** [comment]
@sardar-usman can you add a screenshot?

**Comment by diegoliberman** [comment]
@leandroradusky isn't this for QA already? The PR was merged already.

**Comment by sardar-usman** [comment]
@leandroradusky It looks good now. Working fine.
