### ISSUE TITLE
Add SamplesReports permissions to predefined roles

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1853]
Context: for the new entity `SamplesReports` permissions are not set for existing users.

Solution: do the same that was done in https://github.com/instedd/cdx/pull/1687 for the `Box` entity.

**Comment by ysbaddaden** [comment]
@sardar-usman I'll do the QA for this one (it's manually running a migration task on the server).

**Comment by ysbaddaden** [comment]
@sardar-usman I ran the command on staging, and the "samples report" policies were added to the default institution & site roles (admin & reader).

I verified and the policies were correctly added to my institutions. You might want to have a look also.

**Comment by diegoliberman** [comment]
I updated statuses in Commit (Dev done, Review done) and set the pending to zero instead of 1h.  cc @ysbaddaden

**Comment by diegoliberman** [comment]
@ysbaddaden I'm not getting permission to create Samples Report in Staging.  Institution `UCSD Demo`. User `dliberman+ucsd+demo@manas.com.ar`. 

![image](https://user-images.githubusercontent.com/25181052/216621196-30796980-45b9-4930-8e12-4078ce04307e.png)

**Comment by ysbaddaden** [comment]
Would it be possible that the policy isn't computed for owners?

**Comment by ysbaddaden** [comment]
Urgh. We ADDED a resource and thus ADDED new policies so we MUST run a rake task to recompute the policies :facepalm: 

This is all documented in the wiki:
https://github.com/instedd/cdx/wiki/Granting-proper-access-after-creating-a-new-entity:-Policies---Permissions---Roles

**Comment by ysbaddaden** [comment]
So, during the next release, we must run these tasks:

```sh
$ bin/rails policy:add_samples_report_permissions
$ bin/rails policy:calculate_computed
```

**Comment by ysbaddaden** [comment]
@diegoliberman @sardar-usman the samples report permissions have now have been recomputed for existing users, not only added to the default roles!

**Comment by diegoliberman** [comment]
Thanks @ysbaddaden ! 

PS: I think this `rake` command troubled us about 4 times already :P
