### ISSUE TITLE
Can't create Box Report for transferred Box

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/cdx#1854]
**Steps to reproduce:**

1. create a Box;
2. transfer the Box to another Institution (the receiver);
3. confirm the Transfer in the receiver Institution;
4. (you may upload Sample results, or not);
5. try to create a Box Report;
6. you get an "no such box with this uuid" error message.

**Expected Result**

The behavior should be allowed as awardees shall create Box Reports after uploading their measurements (in our scenario).

**Potential Culprit**

The `samples_reports#find_box` action is filtering out transferred boxes.

**Comment by ysbaddaden** [comment]
@sardar-usman I'll do the QA for this one (it's manually running a migration task on the server).

**Comment by ysbaddaden** [comment]
@sardar-usman this should be on staging.

**Comment by sardar-usman** [comment]
@ysbaddaden I still can't create box report.

**Comment by sardar-usman** [comment]
@ysbaddaden I have manually added the Permissions and then it allowed to create reports. Working fine.
