### ISSUE TITLE
Showing wrong count for "Boxes".

### ISSUE THREAD

**Issue by sardar-usman** [instedd/cdx#1858]
**Steps to reproduce:**

1. Go to the Boxes page.
2. Showing the wrong count for created boxes.

**Expected Result**
Boxes count should be equal to created boxes.
 

<img width="1493" alt="Screenshot 2023-01-23 at 4 47 09 PM" src="https://user-images.githubusercontent.com/45853972/214033134-11bc82af-ae0e-4731-9d42-b4faf47cf1ad.png">

**My setup**

- Device: Laptop
- OS: macOS
- Browser: Chrome

**Comment by ysbaddaden** [comment]
I just reproduce the issue on my local. I'm investigating.

My first impression is that the `Boxes.count_samples` is dropping a box... maybe it skips boxes without samples?

**Comment by ysbaddaden** [comment]
Yeah, `count_samples` does an INNER JOIN on samples, but what if a box doesn't have any sample?

The root cause may actually be because of #1859 that allows to create to a box without samples.

**Comment by ysbaddaden** [comment]
**QA information**: if staging had boxes without samples, then the bug will appear as not fixed: the counter will always count them but they won't show up. We only fixed the cause for the bug (being able to create boxes without samples).

The proper fix would be to delete those boxes from the database, but there are only a few in staging, and it's probably not worth the hassle.

**Comment by sardar-usman** [comment]
@ysbaddaden I would be better if you remove the boxes from database for staging.

**Comment by ysbaddaden** [comment]
@sardar-usman Alright, I just did the cleanup.

**Comment by sardar-usman** [comment]
@ysbaddaden It is working fine now.
