### ISSUE TITLE
Rename SamplesReport resource as BoxReport

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/cdx#1860]
The displayed named for the feature is "Box Report" but the internal resource name is SamplesReport, this is leading to a dichotomy (external & internal names are different) and is a source of confusion when editing roles, because the box report policies are for the SamplesReport entity.

Let's settle on a single name: BoxReport.

**Comment by cclopez78** [comment]
@diegoliberman the team needs your feedback on this one.

**Comment by diegoliberman** [comment]
Answered in the PR

**Comment by ysbaddaden** [comment]
Copied for reference (I'm closing the current associated PR):

> I prefer to think it as a report of samples. The box is just a facilitator for filtering the samples included in the report. But Julien is making a good point. Perhaps we can change the UI titles? Something like "Samples reports from boxes" could work? The menu entry within samples could be just "Reporting". What do you think?

All very good point. Let's just change the menu entry, and keep the `SamplesReport` resource.

I like `Reporting` but maybe `Reports` would be enough. There is a `Reports` entry in the main topbar, but this one would be `Samples > Reports` so maybe it's not _that_ confusing?

**Comment by diegoliberman** [comment]
@leandroradusky could you rename "Box reports" to just "Reports"?  I would also change the page title to "Sample reports"
![image](https://user-images.githubusercontent.com/25181052/215892832-0e28699b-d43f-4397-92e2-bccc94ccd447.png)

**Comment by sardar-usman** [comment]
@ysbaddaden page title should be "Sample reports". or is it fine?
<img width="1426" alt="Screenshot 2023-02-02 at 7 28 49 PM" src="https://user-images.githubusercontent.com/45853972/216352191-1d83b85d-e4a0-400a-90c5-4bade97b5d22.png">

**Comment by ysbaddaden** [comment]
@diegoliberman See previous screnshot. I understand this is what you meant?

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine.

**Comment by diegoliberman** [comment]
> @diegoliberman See previous screnshot. I understand this is what you meant?

Yes, you understood correctly.
