### ISSUE TITLE
Migration of new fields for existing batches (in production)

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1864]
With respect to the columns that will be appended in the `Batch` entity: they have this information available on a spreadsheet for the existing batches. When we implement the data migration, we have to map these columns for the existing batches taking this spreadsheet as a reference for one time only.

(Alternatively, they will have to go batch by batch defining it for the existent batches, but was mentioned that this migration can be done). 

For new batches they will define the full information.

**Comment by ysbaddaden** [comment]
Closing as duplicate of #1922

**Comment by diegoliberman** [comment]
Work item deleted in Commit
