### ISSUE TITLE
Wrong "Delete Confirmation" message for Boxes.

### ISSUE THREAD

**Issue by sardar-usman** [instedd/cdx#1881]
Steps that you should follow in order to see the bug, ie.
1. Go to 'Boxes' page.
2. Click on any Box from the list.
3. Click on "Delete Box button"
4. A pop up screen is appeared.
5. Wrong message for deleting the box.

**Expected**

It should show the message for deleting the Box while for now it showing the message for batches..

**My setup**

- Device: Laptop
- OS: macOS
- Browser: Chrome
<img width="1502" alt="Screenshot 2023-01-30 at 10 02 38 PM" src="https://user-images.githubusercontent.com/45853972/215553423-fe88ae46-4cc4-43f0-a546-048c9e9a58b3.png">

**Comment by diegoliberman** [comment]
@leandroradusky quick fix?

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine now.
