### ISSUE TITLE
Box Report Pdf file is not behaving correctly.

### ISSUE THREAD

**Issue by sardar-usman** [instedd/cdx#1884]
Steps that you should follow in order to see the bug, ie.
1. Go to 'Box Reports' page.
2. Click on any report from the list.
3. Click on "Download PDF" button from the report.
4. It downloads the Box report in Pdf formate.
5. The Pdf file is not correct.
6. It crops the data of the first page.

**Expected**
Data of the pages should not be cropped.

**My setup**

- Device: Laptop
- OS: macOS
- Browser: Chrome 

<img width="1797" alt="Screenshot 2023-02-01 at 5 42 56 PM" src="https://user-images.githubusercontent.com/45853972/216056278-b6b5e315-f575-4587-8038-32f8b18620b8.png">

**Comment by leandroradusky** [comment]
I confirm that this is happening when Muhammad does it, but I cannot reproduce the error, not in my local nor in staging, so I'm a little lost in this issue. 

Maybe is a good excuse to move forward with #1843? cc @ysbaddaden @diegoliberman.

Otherwise, any hints/inputs are accepted.

**Comment by ysbaddaden** [comment]
@leandroradusky maybe it has something to do with the browser current zoom? Like one is at 100% but another one is at 110% and this is affecting one of the several libraries that generate the PDF (html2canvas, resize, render to image, render to pdf...)?

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine now.
