### ISSUE TITLE
Allow to enter replicates with zero concentration

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1901]
![image](https://user-images.githubusercontent.com/25181052/217314106-2afcd632-57b2-4ed0-ae2a-6b9cf6b55b6f.png)

### BONUS
1. Reduce the space to enter the number of replicates, so that we gain space for increasing the field for defining the concentration.  See this image:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/25181052/217326170-b846013e-14e0-45c5-aa17-eaacbbb050b9.png">

2. Move the `instructions` label to the line below, closer to the input field
<img width="535" alt="image" src="https://user-images.githubusercontent.com/25181052/217326511-c44d8793-be9d-42a9-b39c-00bf1665568b.png">

**Comment by sardar-usman** [comment]
@leandroradusky The 'INSTRUCTIONS' label is not close to input field. @diegoliberman 
<img width="1163" alt="Screenshot 2023-02-10 at 3 09 52 PM" src="https://user-images.githubusercontent.com/45853972/218069249-39764386-3487-418d-9e7e-28998e61f6e2.png">

**Comment by diegoliberman** [comment]
@sardar-usman good catch! I decided that those details will be fixed in #1909.  If you find more, please add a comment into that issue.  Thanks!
