### ISSUE TITLE
General NIH tables

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1905]
The columns `target_organism_name` and `target_analyte_type` will have dynamic data depending on the dropdown selection (see #1917).  

The general tables for any box purpose to be exported are two: Results and Samples.

**Samples**: The template for this file has the following fields:

- sample_id: self-explanatory
- vqa_box_id: the `uuid` of the box
- sample_group: the `purpose` of the box + `"-panel"`
- sample_media: _to be completed by the awardee_
- sample_media_id: _to be completed by the awardee_
- sample_media_source: _to be completed by the awardee_
- sample_media_source_url: _to be completed by the awardee_
- sample_concentration: self-explanatory
- sample_concentration_unit: fixed to `copies/ml`
- sample_concentration_reference_gene: _new field in batch entity, see #1863_
- virus_sample_id: same as `sample_id`
- virus_batch_number: self-explanatory
- target_analyte_type: fixed to `inactivated virus`
- target_organism_name: fixed to `SARS-CoV-2`
- target_organism_taxonomy_id: _new field in batch entity, see #1863_
- pango_lineage: _new field in batch entity, see #1863_
- who_label: _new field in batch entity, see #1863_
- virus_sample_inactivation_method: self-explanatory

**Results**: The template for this file is the following: 

![image](https://user-images.githubusercontent.com/13782680/217743793-975bab1a-a92d-4f89-bb4e-378f84c32e5a.png)

The fields that should be fulfilled by CDx are:
- sample_id: self-explanatory
- vqa_box_id: the `uuid` of the box
- sample_group: the `purpose` of the box + `"-panel"`
- assay_readout: measured signal

The other columns should be there be populated by the Awardee.

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine as expected.
