### ISSUE TITLE
Specific LOD results table

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1906]
The columns `target_organism_name` and `target_analyte_type` will have dynamic data depending on the dropdown selection (see #1917).  

When exporting the tables from LOD boxes, an additional table should be exported with the following columns:

- protocol_id: _to be completed by the awardee_
- technology_platform: _to be completed by the awardee_
- vqa_box_id: the `uuid` of the box
- sample_group: the `purpose` of the box + `"-panel"`
- target_analyte_type fixed to `inactivated virus`
- target_organism_name: fixed to `SARS-CoV-2`
- target_organism_taxonomy_id: new field in batch entity, see #1863 
- pango_lineage: new field in batch entity, see #1863 
- who_label: new field in batch entity, see #1863 
- limit_of_blank: new computed field in the report, see #1904 
- limit_of_blank_unit: fixed to `copies/ml`
- limit_of_detection: computed in the report
- limit_of_detection_reference_gene: new field in batch entity, see #1863  
- limit_of_detection_unit: fixed to `copies/ml`
- limit_of_detection_sn_ratio: **to be confirmed** fixed to a value based on SD (standard deviation) used in LOD calculation
- limit_of_detection_ci_percent: **to be confirmed** fixed to a value based on SD (standard deviation) used in LOD calculation
- limit_of_detection_detail: fixed to `linear regression`
- analytical_sensitivity: _to be completed by the awardee_
- analytical_sensitivity_unit: _to be completed by the awardee_

**Comment by sardar-usman** [comment]
@leandroradusky As the description when exporting the tables from LOD boxes isn't the same, unfortunately.
[QA_samples.csv](https://github.com/instedd/cdx/files/12068550/QA_samples.csv)

**Comment by leandroradusky** [comment]
@sardar-usman When you download the zip there are several files included... You should check for this issue the file named `QA_lod.csv` not the `QA_samples.csv` since that is part of the issue called `General NIH tables`. Let me know. cc @diegoliberman

**Comment by sardar-usman** [comment]
@leandroradusky It is working as expected.
