### ISSUE TITLE
Can create box without selecting to create or select samples

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/cdx#1913]
Try to create a box, select a purpose but don't select an option to create new samples or select existing sample and submit the form. **The box will be created** and won't show up in the list of boxes yet be counted (triggering bug #1858).

We must validate than a valid option (`add_batches` or `add_samples`) was selected in BoxForm.

**Comment by sardar-usman** [comment]
@ysbaddaden It's not allowing to create Box without any (add_batches or add_samples). Working as expected.
