### ISSUE TITLE
Critical enhancements to NIH tables

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1916]

**Comment by ysbaddaden** [comment]
@diegoliberman Anything in particular to do & estimate, or is that an Epic and we estimate breakdowns, or?

**Comment by diegoliberman** [comment]
No.  It's just a bucket of hours in case we realize there are some critical enhancements that need to be implemented (which usually happens).

**Comment by devduarte** [comment]
Cancelled in favor of Boxes CSV upload.
