### ISSUE TITLE
Update new fields for the existing batches

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1922]
The attached Excel contains the new fields data for the existing batches.  We need to update the records on production with this data.
1. The production target institution is UCSD, id=18.  Please double check this with Mati.  If the institution has more than 1k samples, then it's the one.
2. We need to loop the Excel batches, find the corresponding one in CDx, and update the 4 fields.
3. For each batch that was found, we need to search the samples associated to the batch and also update the 4 fields.
4. We also need to search for Samples associated to the batch but were transferred to another institution, and update the 4 fields.

This is 1 time script.  But, it could be useful for the future.  If later we add even more fields to the batch, maybe we need to go through the same.  It would be worth keeping this script in the repository. 

[BatchIDs_2023-02-14.xlsx](https://github.com/instedd/cdx/files/10741784/BatchIDs_2023-02-14.xlsx)

**Comment by leandroradusky** [comment]
Updated file with information of the fields for batches:

[cdx batch data.xlsx](https://github.com/instedd/cdx/files/11849478/cdx.batch.data.xlsx)

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine.
