### ISSUE TITLE
Show CSV summary in frontend when uploading a box

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1941]
For more details, see https://manas.slack.com/archives/C034BR64J/p1684854103901369

When creating a new box from a CSV file now only the file name is shown:

![image](https://github.com/instedd/cdx/assets/13782680/f6e8458a-e0e4-46fa-a604-6feaf5b00ce3)

But, the contents of the box ─how many samples, in how many batches, and batches that weren't found with a tooltip─ should be informed as they were informed before, when the validations were done in the front end (just displayed, the validations are now ok well done in the backend).

![image](https://github.com/instedd/cdx/assets/13782680/9541f38b-64cc-4f44-befd-89a45f216830)

As Julien suggested in the thread: Let's create an issue to have a small react component to parse the CSV and list the number of batches & samples before submit (where we properly handle/validate the CSV).

**Comment by sardar-usman** [comment]
@bolom It is working as expected.
