### ISSUE TITLE
Improve batch selection in box creation when batch number matches an existing one

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1944]
Context: In a hands-on demo with the client, he copied the `batch number` in order to create a box in the `Create new samples` mode. This displayed the batch in a dropdown, but if the user doesn't click in the dropdown element the form to create samples won't appear.

Copy/pasting:
![image](https://github.com/instedd/cdx/assets/13782680/96f2c93a-ba3d-4ce1-9f09-8551d3145fa4)

Losing focus / pressing tab:
![image](https://github.com/instedd/cdx/assets/13782680/ebf34ad8-9aeb-4450-9ba8-4fc05b747907)

If there is a perfect match and the text box loose focus or tab/enter is pressed, the batch matching the input should be automatically selected from the dropdown.

**Comment by ysbaddaden** [comment]
The `autoselect` option will select an option when there is only one match. So if you type `A.1` you'll have all four examples, but when you paste `A.1.1.2` then you'll only have that option and it shall be autoselected!

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine.
