### ISSUE TITLE
Show "CSV template" download button only in "Create (box) from CSV" mode

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1945]
The `CSV template` download button is shown in the box creation form no matter which mode is selected.

![image](https://github.com/instedd/cdx/assets/13782680/25860eb1-17eb-4b58-8d98-a92192138b9e)

It should be shown only in `Create from CSV file` mode.

**Comment by sardar-usman** [comment]
@bolom It is working as expected.
