### ISSUE TITLE
Inventory order for boxes (unblinded) should have the same order than the labels when printing

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1948]
When printing labels for a box, they're sorted in the order that the batches were entered into the form.  Whereas, when downloading, it's sorted by Batch ID alphabetically. To make the like of technicians easier (they have to stick 50~100 labels to tubes in a specific order) they should have the same order in both places.

We will keep the sorting in the order that the batches were entered into the form.

We should test this behavior for the three modes of box creation: create new samples, select samples from inventory, and upload CSV files.

**Comment by ysbaddaden** [comment]
Hum, removing the default `order by uuid` should fix the issue (but make sure to keep the scrambled order when blinded).

**Comment by sardar-usman** [comment]
@leandroradusky Now Inventory order for boxes (unblinded) has the same order as the labels when printing, working as expected.
