### ISSUE TITLE
Bug: the box remains blinded even when all its samples were unblinded

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1961]
After uploading the results for a box, where all there are rows for all the samples, the box remains in the blinded status, even when all its samples were unblinded.

![image](https://github.com/instedd/cdx/assets/25181052/c9a9e8d3-783f-4dc5-b770-ca4c5ff69c46)

**Comment by sardar-usman** [comment]
@ysbaddaden It's working fine as expected.
