### ISSUE TITLE
When creating a box, the new batch fields aren't copied to the created samples

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1962]
When you create a Box by using the `Upload CSV` or `Create new samples` options, the values of 4 new fields created for Batches (see image below) aren't copied to the samples that were created for that box.

![image](https://github.com/instedd/cdx/assets/25181052/3008dafb-9c27-42b4-969c-97baac785834)

**Comment by diegoliberman** [comment]
Surprisingly, it does work when creating the sample from the Batch.

![image](https://github.com/instedd/cdx/assets/25181052/4d1e7c0b-2551-43bb-9c4c-cd16c008a4c2)

**Comment by sardar-usman** [comment]
@ysbaddaden It is working fine now.
