### ISSUE TITLE
Text overlap for the 4 new fields in batches and samples

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1963]
The fields should have more width, similar to the `specimen role` field.  Additionally, if the text doesn't fit, it should elipsis, as it happens with the `specimen role` field.

![image](https://github.com/instedd/cdx/assets/25181052/d974614f-5292-4d33-acb2-d6cbd9abbe1c)
![image](https://github.com/instedd/cdx/assets/25181052/8192307f-0c91-4147-856b-99bc77e06b40)

**Comment by sardar-usman** [comment]
@ysbaddaden It looks better now. Working fineas expected..
