### ISSUE TITLE
The UX for the new batch/samples field is odd

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1964]
If you enter values "fastly" for the 4 fields, you get with a weird ux:
1. `not found` message even when the focus has already left the field long ago
2.  loading icons in the 4 fields if you go fast enough (I guess this is ok).
3. `not found` message for all fields

I think we should show the `not found` message only if the user is still with the focus in the field.

![image](https://github.com/instedd/cdx/assets/25181052/54df5769-e5d2-49b2-9a25-8867c6667805)
![image](https://github.com/instedd/cdx/assets/25181052/17cf6e4d-d0e6-429f-8014-15ae5d6f6162)

**Comment by leandroradusky** [comment]
After some testing, this is happening when the tab is pressed before the loading of values is finished. For the clicking, the click in other places prevented, then, the best solution that I found for this is to do the same, to add :

```
if (this.isLoading()) {
  event.preventDefault();
}
```

In the tab key handling for `react-select`. This, when the tab key is pressed will "wait" until the loading of possible values is finished to allow "tabing" to the next field.

Do we agree with this solution or do you think something better can/should be done?

cc @ysbaddaden @diegoliberman

**Comment by diegoliberman** [comment]
I would need to see it in action.  Maybe you can show me in local?

**Comment by sardar-usman** [comment]
@leandroradusky It looks good now. When the query searching for the data is canceled, the component stops doing it, working as expected.
