### ISSUE TITLE
Creating a report crashes when there are partial results

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1965]
It seems that crashes when creating a report for a box where partial results were uploaded.  For instance, results for 9 out of the 19 samples in the box.

**Comment by ysbaddaden** [comment]
Confirmed. It crashes while calculating the linear regression:


![Capture d’écran de 2023-07-21 12-58-07@2x](https://github.com/instedd/cdx/assets/47380/736ceaa1-218b-402e-babb-53c2785330e8)

**Comment by sardar-usman** [comment]
@ysbaddaden It looks great, working as expected now.
