### ISSUE TITLE
Downloading NIH table crashes

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1968]
I wasn't able to detect what am I doing in particular to make it crash, but every time I followed the flow for creating the report, it crashed when downloading the NIH report.

Update: it crashed even for a new institution created from scratch

**Comment by sardar-usman** [comment]
@ysbaddaden It's still crashing when downloading the NIH report. cc @diegoliberman 

https://github.com/instedd/cdx/assets/45853972/204f8c07-3732-438d-8c9e-d48c1ecff928

**Comment by sardar-usman** [comment]
@ysbaddaden It is working fine now.
