### ISSUE TITLE
Reports | Not allowing to create the sample reports.

### ISSUE THREAD

**Issue by sardar-usman** [instedd/cdx#1969]
[upload_sample_results (2).csv](https://github.com/instedd/cdx/files/12003687/upload_sample_results.2.csv)
Steps that you should follow in order to see the bug, ie.

Log in as an Admin User.
Create a Box.
Upload the results.
Try to create the report with uploaded measurement samples.
It shows an error "The selected box should contain samples with uploaded measurements".
It was working fine on Friday but today (Monday) it's showing an error.

Expected:
It should create the Sample Report.

Here is the Box id: `9296b022-f696-0fe2-8777-1606ec5f555a`

My setup
Device: Laptop
OS: macOS
Browser: Chrome
<img width="1794" alt="Screenshot 2023-07-10 at 3 32 53 PM" src="https://github.com/instedd/cdx/assets/45853972/93f7ddf1-bcd1-4aa8-add9-1757ae3dfade">
<img width="1471" alt="Screenshot 2023-07-10 at 8 25 00 PM" src="https://github.com/instedd/cdx/assets/45853972/e124d720-21aa-4a3c-aaa5-4b13d3a3a887">

**Comment by ysbaddaden** [comment]
I can't reproduce after all my various fixes.

**Comment by leandroradusky** [comment]
I can't reproduce neither... Can you test again in staging @sardar-usman ?

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine now.
