### ISSUE TITLE
Incorrect Batch error when uploading CSV with samples

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1970]
1. Create an institution from scratch
2. Create two batches as show in the screenshot below
<img width="451" alt="image" src="https://github.com/instedd/cdx/assets/25181052/0f857bb9-66db-40e9-8fa3-ca2f25fa59e8">

3. Create a CSV file as this one
<img width="489" alt="image" src="https://github.com/instedd/cdx/assets/25181052/ddd5fc41-86aa-4bd3-a622-1ed7f6150397">

[upload_box (1).csv](https://github.com/instedd/cdx/files/12015884/upload_box.1.csv)

4. Create a box and try to use the CSV for uploading the samples
<img width="1133" alt="image" src="https://github.com/instedd/cdx/assets/25181052/dc7cda9b-5bc5-411d-8ae3-26c4f070efeb">

5. Save

6. You'll get an error saying that a batch doesn't exist.
<img width="605" alt="image" src="https://github.com/instedd/cdx/assets/25181052/3a0aecb0-b5ee-4acb-898a-7ac5e8f929b5">

**Comment by ysbaddaden** [comment]
I followed the exact sequence on my local environment but I couldn't reproduce the error :(

**Comment by diegoliberman** [comment]
> I followed the exact sequence on my local environment but I couldn't reproduce the error :(

@sardar-usman can you try to reproduce this error in Staging?

**Comment by ysbaddaden** [comment]
I understood the issue. A fix is on its way.

**Comment by sardar-usman** [comment]
@ysbaddaden It is showing the correct error now. Working fine now.
