### ISSUE TITLE
The measured signal field is not editable but it has the style of editable fields

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1971]
It is confusing, it looks like an editable field but it isn't.

<img width="547" alt="image" src="https://github.com/instedd/cdx/assets/25181052/06e86fa9-312f-44f8-9ae6-3c2ed3a64b40">

It should be displayed as other non editable fields:
<img width="514" alt="image" src="https://github.com/instedd/cdx/assets/25181052/b3818611-381a-477f-a885-d021315360dd">

**Comment by sardar-usman** [comment]
@ysbaddaden It is working fine now.
