### ISSUE TITLE
When uploading samples with a CSV, the replicate number should be taken as an input

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1972]
If we don't allow to enter the replicate number, and if they input a CSV with samples from the same batch and the same concentration, all of them remain with the same replicate number --> 1

I think that a column in the CSV should be "replicates".  If the user enters "4", then the system will create 4 replicates for that row.  
An alternative would be that the replicate column has the actual number so the user has full control.  I'm not sure what would be more comfortable for them.  Maybe we could ask AlexC?

**Comment by ysbaddaden** [comment]
I put the `question` label to first verify & figure out how the CSV import is working.

**Comment by sardar-usman** [comment]
@leandroradusky It is working as expected.
