### ISSUE TITLE
New fields for batches entities (v2)

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1987]
The fields in batches entities should include all missing fields in [this](https://docs.google.com/spreadsheets/d/13eew7mJOp0fbh_hs8SbUGHtnZvZ7giqp/edit#gid=1065749321) table, since these properties will be exported in the NIH tables.

In my recollection these fields are:

- `gisaid_clade`
- `virus_sample_source`
- `virus_sample_source_url`
- `virus_source`
- `virus_location`
- `virus_sample_type`
- `virus_sample_formulation`
- `virus_sample_concentration`
- `virus_sample_concentration_unit`
- `virus_sample_genome_equivalents`
- `virus_sample_genome_equivalents_unit`
- `virus_sample_genome_equivalents_reference_gene`
- `virus_preinactivation_tcid50`
- `virus_preinactivation_tcid50_unit`
- `virus_sample_grow_cell_line`

Please note that these are the field numbers expressed in the table, when added into the batches entity, they shouldn't have the `virus_` prefix on their name.

**Comment by leandroradusky** [comment]
@ysbaddaden Had comments on the implementation of this issue.

**Comment by ysbaddaden** [comment]
Unlike #1863 there is a lot of new attributes this time, for a total of 19 custom attributes, specific to a single extraneous feature (NIH tables generation).

We may want to look into the `#custom_fields` column of the Entity Framework. Maybe consider an additional, deployment-specific, `field.yml` for these custom attributes?

Then, only the NIH table templates would have knowledge of them.

:information_source: we'll have to copy the attributes from Batch to Sample on transfer (CDx severs the Sample -> Batch relationship during transfer).
