### ISSUE TITLE
Configure device timezone

### ISSUE THREAD

**Issue by spalladino** [instedd/cdx#199]
Interpret incoming datetimes from that device using the specified timezone

**Comment by nekron** [comment]
Should we assume the timezone of the location?

**Comment by nditada** [comment]
Let's start with just a setting under the device page for this.

**Comment by nditada** [comment]
Every incoming datetime WITHOUT timezone should be considered to be in the setting timezone. Store everything in UTC in ES.

**Comment by nditada** [comment]
Refactor to recreated date with same values and new timezone
