### ISSUE TITLE
Enhance logging in device events processing

### ISSUE THREAD

**Issue by spalladino** [instedd/cdx#202]
- Add line and column that failed for CSVs
- Add the target field name in the manifest that was being parsed when failed
- Add this information into the existing Device Events table, no UI required in this issue.

**Comment by nditada** [comment]
Review need to refactor data model with @nekron and @waj

**Comment by romeroadrian** [comment]
We are logging the record index and target field that failed. 

When data is json record index is the item number and target field is the key that failed. When data is CSV record index is the line number that failed and target field is the column (in CSV with headers this is the name of the header, when there is no header this is a number indicating the position of the column)
