### ISSUE TITLE
Enhance logging in cdx sync client

### ISSUE THREAD

**Issue by spalladino** [instedd/cdx#203]
Issues are not logged anywhere currently

**Comment by nditada** [comment]
We should log errors locally and report those to CDx as device errors. We need to design how to add a new type of 'event' for this, as it's not directly coming from a specific device...

**Comment by nditada** [comment]
Log to a text file:
- activation attempts (credential exchange, auth, etc.)
- file monitor log (new file detected)
- rsync log (connected, disconnected, started transfer, failed, finished transfer)

Store this in the preferences folder.
Add a menu option from the tray icon to open the file.
