### ISSUE TITLE
Do not use nested object type for custom fields mappings

### ISSUE THREAD

**Issue by spalladino** [instedd/cdx#208]
Review if the `custom_fields` bag in an indexed document should be a [multilevel object](http://www.elastic.co/guide/en/elasticsearch/guide/master/complex-core-fields.html#inner-objects) and not a [nested object](http://www.elastic.co/guide/en/elasticsearch/guide/master/nested-objects.html), which seems to incur in a larger overhead. 

Querying on nested fields also require a more complex [nested filter](http://www.elastic.co/guide/en/elasticsearch/reference/1.x/query-dsl-nested-filter.html), rather than simply qualifying the field with the container, such as `custom_fields.end_time`.

**Comment by nditada** [comment]
Will be solved by #253
