### ISSUE TITLE
Refactor manifests

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#243]
- [ ] If a target_field matches the name of a core field, it must be declared as core and vice versa.
- [ ] If the field is core, it can only specify the target and the source. It can't contain any other field.

**Comment by nditada** [comment]
Also refactor the manifest to split it into 2 sections: one that defines new custom_fields that can't clash with core_field names, another section that maps device fields to core_fields.

**Comment by nekron** [comment]
Something like:

```{
  "metadata" : {
    "version" : "1.0.3",
    "api_version" : "1.1.0",
    "device_models" : ["MTB Device Model"],
    "source": {"type" : "json"}
  },
  "custom_fields" : {
   {
        "name" : "some_custom",
        "type" : "string",
        "pii" : true
      }
  },
  "field_mapping" : {
    "sample.uid" : {"lookup" : "sample_uid"},
    "sample.type" : {"lookup" : "sample_type"},
    "some_custom" : {"lookup" : "custom/path"}
  }
}
```
