### ISSUE TITLE
Store patient_age with 'units'

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#245]

**Comment by matiasgarciaisaia** [comment]
See #236 for context

**Comment by matiasgarciaisaia** [comment]
As ES doesn't provide a way to store durations (ie, `3 months`, `2 days`, `5 years`), we will store durations in an integer format (in days) for it to be searchable, alongside with the received age (`age`) and different human readable formats (`age_in_days`, `age_in_months`, `age_in_years`) as specified by `convert_date`.

Manifests should specify how to convert the data received to the integer in days.
