### ISSUE TITLE
Fix device breadcrumbs

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#293]
- [x] Device messages: can't return to device (/edit is missing)
- [x] Generate Key: device is missing in breadcrumb 
- [x] Generate Activation Token: device is missing in breadcrumb
- [x] Custom mappings: can't return to device (/edit is missing)
- [x] Manifests view: manifests index is missing in breadcrumb
- [x] Filters: doesn't have breadcrumb at all
- [x] Subscribers: doesn't have breadcrumb at all
- [x] Policies: only index is present

**Comment by waj** [comment]
I also added 'New' to the breadcrumb where necessary.

**Comment by waj** [comment]
Fixed in 2fdb92f

**Comment by mmuller** [comment]
Ok in Version: 0.4-pre6
