### ISSUE TITLE
Complete Device Filters

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#303]
- [x] Add filter by site
  - [ ] ~~Link the site filter to the institution filter~~
  - [ ] ~~The filter by site should be a plain autocomplete for hierarchical sites~~
- [x] Add filter by manufacturer
- [ ] ~~Add filter by activity~~
- [x] Add also a filter by institution and a institution column, if the user has access to more than one institution
- [x] Add an institution select button if the user can create devices in more than one institution.
- [x] Do not display the create new device button if the user can't create devices in any institution.

**Comment by bcardiff** [comment]
@nekron there is no last_activity date in device. Should that keep track only of device_message or also keep track of commands/logs created?

**Comment by bcardiff** [comment]
* last activity of a device will be developed later probably
* ui for searching in a hierarchy manner the sites is deferred. 
* linking institutions and sites now is useless due to previous item

**Comment by pmallol** [comment]
Ok in Version: 0.7-pre3
