### ISSUE TITLE
Add UUID to institutions an laboratories

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#309]
The internal ruby id should be hidden to the outside world.

Index and return the UUID instead of the ID.

**Comment by asterite** [comment]
Question: inside elasticsearch and to the outside world, an institution's id is viewed as "id" or "uuid"? If it's "uuid" then we need to change fields.yml, right?

**Comment by nekron** [comment]
Yes. Change it to uuid so the internal cdx id is always the entity uuid.

**Comment by nekron** [comment]
Also change the http://cdp-stg.instedd.org/api/laboratories endpoint to filter by institution uuid and return the laboratories uuid.
