### ISSUE TITLE
Split Institutions into Manufacturers, Institutions and Health Organizations

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#326]
- manufacturer:
 - [ ] Is the only one with permission to create manifests
 - [ ] Is the only one that can see the device model list
 - [ ] They shouldn’t be able to see the labs list
 - [ ] They should be able to create devices to test the manifests
 - [ ] They shouldn’t be able to see the current nndd medical dashboard
- Health Organizations:
 - [ ] They shouldn’t be able to create devices or labs
 - [ ] They should only see the list of devices and labs if there is at least one institution that shared that list with them
 - [ ] They shouldn’t be able to see the device models list
- Institutions:
 - [ ] They should be able to create devices and labs
 - [ ] They shouldn’t be able to see the device models list

If a user belongs to more than one organization, then the list of tabs that he will see will be the union of his permissions.

The implicit policy should only allow the user to create an institution. When the user creates an institution, then another policy will be added to complement that permissions.

**Comment by cisaacs01** [comment]
Disagree with manufacturers being the only ones able to create a device manifest. Some devices may need to be added but when the manufacturer hasnt expressly signed up to using CDX. Example could be Alere (as of date of this note), they are not signed up to use CDX but many institutions use their devices that are able to output data to a destination of the institutions choosing.

**Comment by cisaacs01** [comment]
Why would an institution not be able to see the device model list?

**Comment by nekron** [comment]
In Alere's case, we as super admins can develop and add the missing manifest. A lab operator won't have the necessary knowledge to build a manifest for the device he is operating, as he doesn't know (and he doesn't need to know) the internal details of how it transmits the data it collects.

That's why a regular institution (a lab), doesn't need a menu on its navigation bar to give them direct access to the device models list, it will only be noise for them. That doesn't mean that they won't see the device models when creating a device or when seeing that device on a list or when seeing a test that it reported.

**Comment by cisaacs01** [comment]
Makes sense but would suggest we need to recognise the role of the CDX super admin i.e. InSTEDD or FIND. When categorising permissions or functions such as this it would be helpful to know this entity is present.  UI considerations will need to be incorporated i.e. to add a new device not on list please contact us.

**Comment by mmuller** [comment]
Ok in version 0.6-pre3
