### ISSUE TITLE
Manufacturers should be able to test a device model before publishing it

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#328]
- [x] Add a publish action and state to device models
- [x] "unpublished" models won't be considered for devices outside the institution
- [x] Only allow deleting non published device models.
 - [x] Ensure no orphan manifests, devices, and tests from mysql and Elasticsearch

**Comment by spalladino** [comment]
@jkicillof how should the `publish` action look like in the UI? Once a model is published, there is no "unpublishing" it. Should we add a `publish` button in the edit form, forcing the user to first create a model and then going back to edit it to publish it? Or add a `published` checkbox in the form, and display an inline warning to the user letting her know that once the change is saved, there is no turning back?

See https://projects.invisionapp.com/d/main#/console/4103589/94546556/preview

**Comment by spalladino** [comment]
@nekron what does the `Ensure no orphan manifests, devices, and tests from mysql and Elasticsearch` imply? Should we force delete them? Or only allow to delete a device model if it has no devices and tests?
