### ISSUE TITLE
Add google login

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#338]

**Comment by matiasgarciaisaia** [comment]
Duplicates #380?

**Comment by nekron** [comment]
Not quite. The login with google was added in https://github.com/instedd/cdx/commit/a0f8ed5d4f07b89023dcec56676ba10998bad8c6 but then the link was missing after the UX style was applied (the Devise default screens were replaced by custom ones), so #380 was created to put that link in those new screens.

**Comment by mmuller** [comment]
Ok in version 0.6-pre3
