### ISSUE TITLE
Precalculate permissions for each user based on policies

### ISSUE THREAD

**Issue by spalladino** [instedd/cdx#343]
Recursively evaluating policies every time a permission needs to be checked is too expensive. Precalculate permissions for each user.

**Comment by spalladino** [comment]
## Model

The model is a table with one entry for each ability of a user.

User | Effect | Action | Resource Type | Resource ID | Institution | Lab | Owner
------ | -------- | -------- | --------------------- | ---------------- | ------------- | ----- | ---------
1 | Allow | Read | Device | * | 1 | * | * | *
1 | Deny | Read | Device | 5 | * | * | * | *

Where Institution, Lab and Owner are all the possible conditions that apply to a resource.

## Propagating permissions

Permissions are propagated to a grantee by performing the product between the grantor's permissions and the statements in the policy. For example, if User 1 has:

Action | Type |  ID | Institution | Laboratory
---- | --- | --- | --- | ----
Read | Devices | * | 1 | *
Read | Devices | * | 2 | *

And grants user the 2 permissions:

* Read devices from laboratory 1
* Read devices from laboratory 2

The permissions for user 2 will be all the possible combinations, expressed as intersections:

Action | Type |  ID | Institution | Laboratory
---- | --- | --- | --- | ----
Read | Devices | * | 1 | 1
Read | Devices | * | 1 | 2
Read | Devices | * | 2 | 1
Read | Devices | * | 2 | 2

Note that invalid combinations are simply not propagated. For example, given a grantor with access to devices with `lab=1`, if he grants access to `lab=2`, then no permissions will be propagated.

## Removing redundant entries

If an entry is subsumed under another one, then the former can be removed. For example, given the following two entries:

Action | Type |  ID | Institution | Laboratory
---- | --- | --- | --- | ----
Read | Devices | * | 1 | *
Read | Devices | * | 1 | 3

The second entry is included in the first one, so it can be removed.

## Records with fixed ID

If a statement uses a fixed ID, then the ID can simply be propagated, instead of the full combination of it with all current permissions. Going back to the first example, given a grantor with permissions:

Action | Type |  ID | Institution | Laboratory
---- | --- | --- | --- | ----
Read | Devices | * | 1 | *
Read | Devices | * | 2 | *

Should he grant access to a user to device 1, the result, according to the algorithm, would be:

Action | Type |  ID | Institution | Laboratory
---- | --- | --- | --- | ----
Read | Devices | 1 | 1 | *
Read | Devices | 1 | 2 | *

**As long as the grantor does have access to device 1**, this can be simplified by just granting access to:

Action | Type |  ID | Institution | Laboratory
---- | --- | --- | --- | ----
Read | Devices | 1 | * | *

Note that this optimization can only be performed if the fact that the grantor has access to device 1 is re-checked whenever the device changes. For instance, if the device is moved to a different laboratory, then the grantor might lose access to it; in this event, the propagated entry to the grantee must be removed.

## Re-evaluation of policies

Whenever a policy applied to a user changes, then all the permissions for that user must be re-evaluated, as well as all the permissions of the grantees of such user, and so on recursively. 

Note that a loop might actually occur. In this situation, the evaluation should proceed until the user being updated is unchanged. Since on every iteration only more permissions are added, and there are finite combinations of them, the algorithm should eventually converge.

Since this process is most likely to be computationally intensive, it should be performed in a background process. Ensure that these updates are handled by a single worker, otherwise two workers simultaneously editing policies might oscillate.

**Comment by spalladino** [comment]
## Evaluating permissions

A user can access a resource if any *allow* entry matches such resource, and no *deny* entries match it. A match is checked through all the properties of the resource. For example, when checking if user U1 has access to read the device:
```
Device ID=1 Institution=I1 Laboratory=L1 Owner=O1
```

The following check is performed:
```
EXISTS
  User= U1 AND
  Effect= Allow AND
  Type= (Device OR *) AND
  ID= (1 OR *) AND
  Institution= (I1 OR *) AND
  Laboratory= (L1 OR *) AND
  Owner= (O1 OR *) 
AND NOT EXISTS
  User= U1 AND
  Effect= Deny AND
  Type= (Device OR *) AND
  ID= (1 OR *) AND
  Institution= (I1 OR *) AND
  Laboratory= (L1 OR *) AND
  Owner= (O1 OR *) 
```

A similar query is performed to retrieve all devices accessible by a user.

**Comment by spalladino** [comment]
* [ ] Remove `is_owner` condition
* [ ] Add implicit policy to create an institution
* [ ] When institution is created, add some default permissions (later, based on the kind of institution, see #326)
* [ ] Create computed policies model
* [ ] Naively precalculate policies when a new policy is created
* [ ] Remove redundant permissions
* [ ] Recalculate when a policy changes
* [ ] Recalculate when a resource changes
* [ ] Define behaviour when a user is deleted

**Comment by spalladino** [comment]
To define: how to handle propagated denies? For example:

* Granter 1 has `allow device/*` and `deny device/1`
* He grants `allow device/*` to User 2
* User 2 then has both `allow device/*` and `deny device/1`
* Granter 3, who has `allow device/*`, grants `allow device/*` to User 2
* User 2 cannot access device/1 since he has a deny entry for it, even though never explicitly denied

**Comment by spalladino** [comment]
## Except

The `effect` attribute (which could be allow or deny) is to be removed in favour of `except`, which accepts a list of resources, and affects only the statement where it is present.

**Comment by spalladino** [comment]
## Checking auth methods

### can?

```ruby
Policy.can?(action, resource, user) => boolean
```

* When resource is a class or an AR scope, returns true iif the `user` has a policy that allows her to perform the `action` on any subset of the resource class, even if the computed subset is empty. Used to check if a page should be shown to a user at all.

* When resource is an instance, returns true iif the user can perform the `action` on the `resource` instance.

### can_delegate?

```ruby
Policy.can_delegate?(action, resource, user) => boolean
```

Exactly the same as `can?`, but only considers policies that are marked as delegable.

### authorize

```ruby
Policy.authorize(action, resource, user) => AR scope
```

* When resource is a class, returns the AR scope of that class where the `user` can perform the specified `action`.

* When resource is an AR scope, returns another scope chained with it, where the `user` can perform the specified `action`.

* When resource is an instance, returns an AR scope containing just that instance if the `user` can perform the specified `action` on it, or an empty scope if she cannot.

**Comment by nekron** [comment]
I believe authorize was returning the instance or nil if the resource is an instance.

**Comment by spalladino** [comment]
Fixed!
