### ISSUE TITLE
Breadcrumb is displayed when the user is not signed into CDX

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#345]

**Comment by mmuller** [comment]
![screen shot 2015-09-16 at 2 14 19 pm](https://cloud.githubusercontent.com/assets/518152/9912322/47a19732-5c7d-11e5-8ab5-eb2e2adf9d4e.png)

**Comment by asterite** [comment]
Fixed in 8b947f60315cd599f5556d22f286f1269cdd7e2f

**Comment by mmuller** [comment]
Ok in version 0.6-pre3
