### ISSUE TITLE
The design proposal is not correctly displayed on the new device view

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#348]
Found in version 0.5-pre2

Steps:
Go to create a new device

Obtained:
The design proposal is not correctly displayed on the new device view

![screen shot 2015-09-18 at 1 01 36 pm](https://cloud.githubusercontent.com/assets/518152/9964221/73ead068-5e05-11e5-8e47-ed2b4d7b15f5.png)

https://projects.invisionapp.com/d/main#/console/4103589/93836811/preview

**Comment by nekron** [comment]
The main issue here is that  the user only has one institution, and yet the institution select is displayed. The rest of the style is scheduled for a latter release.

**Comment by matiasgarciaisaia** [comment]
Already implemented in 7ab76e312bf036503553aeb39ab340c2bd5e487f

**Comment by mmuller** [comment]
Now in version 0.6-pre3 the institution select is not displayed when the user only has one institution.
