### ISSUE TITLE
Store laboratory location's lat & lng

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/cdx#368]
The location service is returning both the location ID and it's lat and lng, but we're only storing the ID.

We need the lat&lng for showing the maps. It would be best to store the lab's lat&lng (and not the one from it's location), but it's a start.

**Comment by matiasgarciaisaia** [comment]
Implemented in 831323b3e1ead88bdc155d8489a1d097e7d3a92a

**Comment by nekron** [comment]
See #404 regarding the labs real lat&lng storage.

**Comment by pmallol** [comment]
Ok in Version: 0.6-pre4
