### ISSUE TITLE
If device fails to set the key or the authentication token, the edit page is displayed but fails to render the barcodes

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#369]
The `@uuid_barcode_for_html` is only filled for the `edit` action and is empty when trying to render the edit page from the regenerate_key action.

```
ActionView::Template::Error (undefined method 'to_html' for nil:NilClass):
    2: %p
    3:   %strong UUID:
    4:   = @device.uuid
    5:   = raw @uuid_barcode_for_html.to_html
    6:
    7: = render 'form'
    8:
```

**Comment by asterite** [comment]
I can't reproduce this. In which case the `regenerate_key` action fails?

**Comment by nekron** [comment]
It's mostly due to deployment issues. But anyway, the view breaks when trying to display the error message.

**Comment by asterite** [comment]
I can fix it but I won't have a way to test that it doesn't break. If the code later changes there won't be a way to maintain it because it'll be dead code. I say we close this issue as "can't reproduce".

**Comment by nekron** [comment]
This was previous to the device screen refactor. The entire device creation would fail now if the secret key can't be set.
