### ISSUE TITLE
Support single-tenant deployments

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#371]
We foresee the likelihood of countries wanting to have their own server in-country. A CDx server instance should be able to be configured as 'single-tenant', meaning basically that users cannot self-register. Multiple institutions can be created, but they will have to be created by the server super-admin

**Comment by nekron** [comment]
We need an stg single tenant server to test this deploy.

**Comment by cisaacs01** [comment]
Does single tenant deploy remove link to Google sign in on login page? If so #1005 is redundant.

**Comment by mmuller** [comment]
Now users can self-register (version 0.11-pre15)

**Comment by nekron** [comment]
Single tenant deploy does not remove the link to the google sign in on the login page. #1005 should be implemented that way.

**Comment by nekron** [comment]
Splitted into #1038.
