### ISSUE TITLE
Build the device dashboard layout

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#375]
Build the card and tabs layout.

Add only tests filtered by device and device messages as tabs.

If the device has not reported any test yet, display the setup instructions link.

https://projects.invisionapp.com/d/main/default/#/console/4103589/93836668/preview

**Comment by waj** [comment]
![cdx_show_device](https://cloud.githubusercontent.com/assets/22697/10397963/bf80251a-6e80-11e5-8de7-4a0516851ae6.png)
