### ISSUE TITLE
Handle patient merging while creating encounters

### ISSUE THREAD

**Issue by bcardiff** [instedd/cdx#384]
Right now encounters enforce that the same patient (as db model) is used in an encounter.

But actually two db patients might refer to mergeable patientes if one of them does not define a entity_id and (?) rest of the information allows merging.

It would be desired to allow the user creating the encounter to decide / validate that a merge between those patients is desired.

**Comment by spalladino** [comment]
Fixed in cd5929c8f594bba63d04b556f736b368a408eba6

**Comment by nekron** [comment]
Fixed in https://github.com/instedd/cdx/pull/489
