### ISSUE TITLE
Multiple IDs per Sample

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#400]
Different teams in a lab can use different ids for the same sample.

- A user should be able to query all the tests of a given sample, across its multiple ids.
- Keep an id relation between the sample and the corresponding tests.
- The sample will have a list of alternate_uuids containing the uuids of the different samples that were merged into the resulting one. Keep the own uuid there, just to simplify the queries.
- Index all the different ids for every related test.

![img_20151009_174925959](https://cloud.githubusercontent.com/assets/957103/10459528/4c7f5346-71a6-11e5-8428-fa0f1b7391a8.jpg)

**Comment by spalladino** [comment]
![20151008_124930](https://cloud.githubusercontent.com/assets/429604/10371891/c19c5c26-6dbb-11e5-8144-3c5341be374c.jpg)

**Comment by nekron** [comment]
- Keep an id relation between the sample and the corresponding tests.
- The sample will have a list of alternate_uuids containing the uuids of the different samples that were merged into the resulting one. Keep the own uuid there, just to simplify the queries.
- Index all the different ids for every related test.

![img_20151009_174925959](https://cloud.githubusercontent.com/assets/957103/10459528/4c7f5346-71a6-11e5-8428-fa0f1b7391a8.jpg)

**Comment by mmuller** [comment]
Ok in version 0.11-pre10
