### ISSUE TITLE
Allow the user to edit Encounters

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#412]
Add a link from the Test Result view screen to access the related encounter.
If the user has edit permission redirect him to the edit screen.
If the user can only see the encounter, redirect him to the view screen.

**Comment by bcardiff** [comment]
The edit page is there, yet to finish this feature we are on hold on #435 since that will impact in the encounters_controller.

**Comment by spalladino** [comment]
Fixed in e99b964d83f7bec3f6add9338190fcae62bb14a5

**Comment by mmuller** [comment]
Ok in version 0.7-pre7
