### ISSUE TITLE
Allow a user to define a diagnostic for an encounter

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#413]
The diagnostic should contain a list of the conditions evaluated by the different tests with a positive/negative/indeterminate result and a quantitative_result. It should also contain an observations field to let the user add some notes. Asume an initial value for each result if all the tests of that particular condition ended up with the same result, otherwise let it with indeterminate.

The creation of the diagnostic will confirm an encounter.

Allow the creation of a diagnostic from the show Encounter screen. See #412

**Comment by bcardiff** [comment]
@nekron the core fields defines positive, negative and n/a. 

How does n/a plays in the merging? 
* n/a + positive = positive?    
* n/a + n/a = indeterminate?

Should be merging use the assay name or the assay condition as key?

**Comment by nekron** [comment]
`n/a` means that there was no information regarding that condition. Probably because it wasn't relevant. The typical `n/a` case would be a result for a `rif` assay when the `mtb` assay result was negative, in the same test. What should that be? In that case `rif` could just be negative.

Adding up, the merge of `n/a` is more probably a `negative` than an `indeterminate`, but I like the idea of not assuming anything and let it as `indeterminate`.

**Comment by bcardiff** [comment]
Why there would be an assay with n/a? That assay shouldn't be there in the first place. Or I am missing something?

**Comment by nekron** [comment]
As I said, the typical n/a case would be a result for a `rif` assay when the `mtb` assay result was negative, in the same test. The device may then report negative or may not report anything at all. You can then choose to fill the assay information or not.

Another case would be an assay which its result is only quantitative, like white blood cells count. This result is not positive or negative. It could be left in `nil`, but `n/a` is a valid value in this case too.

**Comment by pmallol** [comment]
Ok in Version: 0.7-pre10
