### ISSUE TITLE
Merge samples within an encounter in encounters UI

### ISSUE THREAD

**Issue by spalladino** [instedd/cdx#423]
See #400 

Related screens:
https://projects.invisionapp.com/d/main/default/#/console/4103589/93837344/preview
https://projects.invisionapp.com/d/main/default/#/console/4103589/102642724/preview
https://projects.invisionapp.com/d/main/default/#/console/4103589/96562434/preview

**Comment by pmallol** [comment]
Ok in Version: 0.7-pre10
