### ISSUE TITLE
Google Login isn't working in staging

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/cdx#434]
Login with Google isn't working in `Version: 0.6-pre2`.

`https://accounts.google.com/o/oauth2/auth?access_type=online&client_id=&redirect_uri=http%3A%2F%2Fcdp-stg.instedd.org%2Fusers%2Fauth%2Fgoogle%2Fcallback&response_type=code&scope=email+profile&state=e9f76351181a563e426b2f707fb893533ae0c481ee63051c` says:

```
400. That’s an error.

Error: invalid_request

Missing required parameter: client_id

Learn more

Request Details
access_type=online
scope=email profile
response_type=code
redirect_uri=http://cdp-stg.instedd.org/users/auth/google/callback
state=e9f76351181a563e426b2f707fb893533ae0c481ee63051c
client_id=
That’s all we know.
```

**Comment by matiasgarciaisaia** [comment]
Seems there's no `client_id` configured in `settings.yml`

**Comment by pmallol** [comment]
Sign in with Google working ok in Version: 0.6-pre4
