### ISSUE TITLE
Allow users to select an Institution in the Site creation

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#448]
Found in version: 
0.6-pre3

Prerequisites:
There are some Institutions

Steps:
Go to the create a Site
Observe the form

Obtained:
There is no a list of Institutions visible

Expected:
A list of Institutions should be visible to the users

![screen shot 2015-10-27 at 8 03 08 pm](https://cloud.githubusercontent.com/assets/518152/10775286/d5f7cff0-7ce5-11e5-9ab9-22692aba8e0a.png)

**Comment by bcardiff** [comment]
@mmuller 

* if the user has more than one Institute the dropdown appears.
* if the user has a policy that allows him to create sites in more than one institution (that can have sites), the dropdown appears.

Maybe the user you used had a sole Institue, and other(s) Manufacturer(s) and that's the reason the dropdown still does not appear. 

could you confirm?

**Comment by mmuller** [comment]
@bcardiff You are right, if the user has more than one Institute the drop down appears. 
Closing this issue.
