### ISSUE TITLE
Flash messages are not styled

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#470]
"Invalid email or password" for instance:

<img width="917" alt="screen shot 2015-11-05 at 4 57 08 pm" src="https://cloud.githubusercontent.com/assets/5470539/10979958/4caf4b7e-83de-11e5-8531-154cc7e6d245.png">

<img width="511" alt="screen shot 2015-12-03 at 3 41 55 pm" src="https://cloud.githubusercontent.com/assets/957103/11570180/a23f8048-99d4-11e5-8553-b16e7338e915.png">

**Comment by matiasgarciaisaia** [comment]
Notifications style: https://projects.invisionapp.com/d/main#/console/4103589/104858177/preview

**Comment by mmuller** [comment]
Ok in version 0.11-pre7
