### ISSUE TITLE
[siteedit] Delete sites

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#503]
As a user with site management permission, I want to delete an existing site that has no devices.

Ask the user for confirmation. If the site has sub-sites or devices, reject the delete with an explanation.

**Comment by nekron** [comment]
The site can already be deleted, but the devices are just left there, floating in the void.

Restrict the deletion.

**Comment by nekron** [comment]
Delete always implies logical delete.

**Comment by matiasgarciaisaia** [comment]
UI design pending - for now, the explanation is implemented with this alert box:

<img width="532" alt="screen shot 2015-11-10 at 7 05 25 pm" src="https://cloud.githubusercontent.com/assets/5470539/11100650/4040f088-8891-11e5-8890-bb2a5b99cce4.png">

**Comment by pmallol** [comment]
Ok in Version: 0.7-pre3
