### ISSUE TITLE
[hierorgs] Move site to another parent site

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#506]
As a user with site management permission, I want to move an existing site from one parent site to another.

The user has to have site management permissions for both parent sites in order to do that.

**Comment by nditada** [comment]
Quite complex to solve this: 
  - It requires recalculating all the permissions for both parent nodes, since people with access to them would be affected.
  -  The tests are indexed based on the hierarchical sites, moving a site implies having to reindex all the tests.

To discuss with FIND to see if it can be de-prioritized.

**Comment by cisaacs01** [comment]
Most of the site moving is anticipated during facility registry setup. Once setup i dont anticipate much moving of the sites. Renaming is more important at this point which should be achievable without changing the database ID of the site. How about move is possible if no tests are allocated. If tests are allocated then popup message telling user they cant.

**Comment by nditada** [comment]
@cisaacs01  Renaming is already possible. If we don't need to transfer tests (which could create lots of complications in terms of region ownership, reporting, etc.), what are the things we are interested in transferring? Devices only?

**Comment by cisaacs01** [comment]
Correct - devices only.

**Comment by nekron** [comment]
Implement this as following:
- Create a new site with the same attributes of the older one (name, location, sample reset policy)
- Transfer all the devices to the newly created site
- Archive the old site
- All the users will have to be reassigned to the new site by a system administrator (no policy recalculation is needed). The new administration will probably want to review the access to this site anyway.
- All the tests will still belong to the old site and will only be accessed from the previous parent site (no reindex is needed). The information of the previous tests belongs to the previous administration.

**Comment by nditada** [comment]
:+1:

**Comment by nekron** [comment]
What should be the desired behavior when a device that has been moved, reports an update on an existing test?
Option 1: Its a different test, because it now belongs to a new administration, it will lead to duplicated results.
Option 2: Keep track of all the sites that the device has been to, and report the updates properly according to the start time and end time of the tests.

Idem samples. After we have identified the test, we can lookup the sample in the same site of the test.

**Comment by nditada** [comment]
Let's go with option 1, if the device is an different place and the test is run again, it's a different result. Very unlikely scenario though. Can we move this to ready now?

**Comment by spalladino** [comment]
@nditada note that if a device model re-uploads all tests in a recurrent basis, this will duplicate all of the moved device's tests

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
