### ISSUE TITLE
[perms] See users with access per site

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#507]
As a user with site management permission, I want to see a list of all the users that have access to sites.

This should probably be part of the detail view of a site, while exploring individual sites through the hierarchy. e.g. "I select a node in the hierarchy, click on the 'users' tab on the right and see a list of users with their permissions. If I click on a different node of the hierarchy, the tab selection remains 'users'"

**Comment by nditada** [comment]
Discuss with FIND, we need to have roles to do this properly.

**Comment by mmuller** [comment]
Ok in version: 0.11-pre6
