### ISSUE TITLE
Add a toggle to choose to grant permission to a site and the entire hierarchy or just to that site

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#513]
And implement the underlying functionality in the policies model.

**Comment by nditada** [comment]
@nekron Do we have a design in invision for this? can you link?

**Comment by nekron** [comment]
https://projects.invisionapp.com/d/main#/console/4103589/113464930/preview
and
https://projects.invisionapp.com/d/main#/console/4103589/113464672/preview

**Comment by mmuller** [comment]
Ok in version 0.11-pre7
