### ISSUE TITLE
Scope users by the selected site

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#515]
Display the list of users scoping by the selected site. This means, only display the users that belongs to a role inside the selected institution or site.

**Comment by spalladino** [comment]
Is this a duplicate of #507?

**Comment by nekron** [comment]
#507 is the user story, this is a single task of just scoping the list that we have. It will require a couple more changes to actually complete the whole story, i.e. roles or filters.

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
