### ISSUE TITLE
Soft delete for all entities

### ISSUE THREAD

**Issue by spalladino** [instedd/cdx#523]
Do not permanently delete any entity

**Comment by nditada** [comment]
Should we change messages like this?
<img width="861" alt="screen shot 2015-12-14 at 3 33 53 pm" src="https://cloud.githubusercontent.com/assets/1359189/11789964/25a60adc-a278-11e5-8562-03701cac83dc.png">
@nekron do you want to open a separate issue? A little styling to that alert could come in handy as well ^_^

**Comment by pmallol** [comment]
Ok in Version: 0.7-pre12
