### ISSUE TITLE
CDx client uploads tests to previously configured device

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#525]
Found in client version cdx-win32-development-7fbfd63.exe
CDx Version: 0.6-pre4

1. As Manufacturer create a device model for Genoscan, check the Supports activation checkbox and publish it
2. As Institution admin create a device 'Foo' with the recently published device model
3. Configure a CDx Client with the authentication token of the 'Foo' device
4. Upload tests
5. Right-click the CDx client icon in the task bar and click Reconfigure
6. As Manufacturer create a device 'Bar' with the same configurations as device 'Foo'
7. Configure the CDx client with 'Bar''s authentication token and try uploading tests

Obtained:
Tests uploaded for device 'Bar' are uploaded to device 'Foo'

Expected:
When configuring a CDx client with a "device X" token, test uploaded should appear under that device's detail view.

**Comment by mmuller** [comment]
Ok in version 0.6-pre7
