### ISSUE TITLE
Allow the user to upload a pdf with instructions for a device

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#543]

**Comment by pmallol** [comment]
After trying to upload a .pdf with instructions the user is redirected to a blank page reading:
`An unhandled lowlevel error occurred. The application logs may have details.`

**Comment by spalladino** [comment]
@waj should we configure paperclip to [store all attachments in S3](https://github.com/thoughtbot/paperclip/wiki/Paperclip-with-Amazon-S3)? The same may apply as well to device model images.

**Comment by pmallol** [comment]
Ok in Version: 0.7-pre10
