### ISSUE TITLE
Review table ellipsis styles

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/cdx#558]
Review the styles for avoiding overflows in tables with @mscebba.

See #549, and 39fde3c9ca4cd1be2890dcbc9b4220623f6e0032

**Comment by bcardiff** [comment]
take a look to [this snippet](play.csssecrets.io/table-column-widths)  cited in CSS Secrets

**Comment by mmuller** [comment]
Ok in version 0.10-pre2
