### ISSUE TITLE
JS error thrown in 'New Subscriber' page

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#561]
Found in version 0.6-pre7

Steps:
Go to 'Apps' section
Open the browser console
Click the '+' icon in order to create a new subscriber
Observe console log 

Obtained:
The following JS error is thrown:
`Uncaught TypeError: Cannot read property 'imageSrc' of undefinedn @ application-8d69a3357db87d41d81ecac4b4217ead.js:12(anonymous function) @ application-8d69a3357db87d41d81ecac4b4217ead.js:12ie.extend.each @ application-8d69a3357db87d41d81ecac4b4217ead.js:1ie.fn.ie.each @ application-8d69a3357db87d41d81ecac4b4217ead.js:1s.init @ application-8d69a3357db87d41d81ecac4b4217ead.js:12e.fn.ddslick @ application-8d69a3357db87d41d81ecac4b4217ead.js:12(anonymous function) @ application-8d69a3357db87d41d81ecac4b4217ead.js:13(anonymous function) @ application-8d69a3357db87d41d81ecac4b4217ead.js:3ie.event.dispatch @ application-8d69a3357db87d41d81ecac4b4217ead.js:2v.handle @ application-8d69a3357db87d41d81ecac4b4217ead.js:2ie.event.trigger @ application-8d69a3357db87d41d81ecac4b4217ead.js:2(anonymous function) @ application-8d69a3357db87d41d81ecac4b4217ead.js:2ie.extend.each @ application-8d69a3357db87d41d81ecac4b4217ead.js:1ie.fn.ie.each @ application-8d69a3357db87d41d81ecac4b4217ead.js:1ie.fn.extend.trigger @ application-8d69a3357db87d41d81ecac4b4217ead.js:2e.turbo.onLoad @ application-8d69a3357db87d41d81ecac4b4217ead.js:3c @ application-8d69a3357db87d41d81ecac4b4217ead.js:2p.fireWith @ application-8d69a3357db87d41d81ecac4b4217ead.js:2ie.extend.ready @ application-8d69a3357db87d41d81ecac4b4217ead.js:2s @ application-8d69a3357db87d41d81ecac4b4217ead.js:1`

**Comment by asterite** [comment]
This is only reproducible if there are no filters
