### ISSUE TITLE
Display test orders in the tests index

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#576]
Add an additional "filter" to switch between tests and test orders (encounters).

**Comment by asterite** [comment]
For test orders (encounters) we are not indexing the sites where those happened. I think we should probably do that, otherwise there's no way to filter them based on the selection of the sites navigation bar.

**Comment by spalladino** [comment]
### Columns
- entity_id
- start_time
- end_time
- diagnosis
- site
- institution (if applies)

### CSV
All fields, including custom. Check TestResultsCsvBuilder, it should be possible to reuse most of it.

### Filters
- Condition
- Result
- Date
- Encounter ID

**Comment by spalladino** [comment]
Pending: filter by site in context

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
