### ISSUE TITLE
NNDD Dashboard fails to load with a 404 error

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#581]
Found in Version: 0.7-pre3

After logging in to Cdx the user is redirected to a broken Dashboard.
![screen shot 2015-11-30 at 11 34 00 am](https://cloud.githubusercontent.com/assets/9214460/11474338/48b6d8c6-9756-11e5-91b7-63c1ef251450.png)

**Comment by spalladino** [comment]
Fixed in https://github.com/instedd/cdx/commit/a1a66a083d68ffde65261970fd923816f8417af8

**Comment by pmallol** [comment]
Ok in Version: 0.7-pre3
