### ISSUE TITLE
Icons in New Encounter buttons not found and a 404 error appears in console

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#584]
Found in Version: 0.7-pre3

Preconditions:
There are tests uploaded

1. Navigate to tests and click the + button to create a new encounter
2. Click on Append sample and a sample

Obtained:
Icons in buttons are missing.

**Comment by asterite** [comment]
Can be reproduced locally with assets precompiled in production mode, and running the app in production mode

**Comment by mmuller** [comment]
Icons are missing in 'Append sample' and 'Add tests' popups. (Tested in version 0.7-pre7)

**Comment by asterite** [comment]
I can see the icons in version 0.7-pre8. @mmuller Can you confirm this?

**Comment by mmuller** [comment]
@asterite the icons are not present in version 0.7-pre8

![screen shot 2015-12-15 at 2 26 14 pm](https://cloud.githubusercontent.com/assets/518152/11818241/029855b6-a338-11e5-886f-46d569d05ece.png)

**Comment by pmallol** [comment]
Ok in Version: 0.7-pre10
