### ISSUE TITLE
Error when creating a new encounter 

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#585]
Found in version Version: 0.7-pre3

Preconditions:
There are test results uploaded 
 
1. Navigate to Tests
2. Click the + button to create a new encounter
3. Append a sample
4. Click Save to create a new encounter

Obtained: 
A notice pops up reading: `Error creating encounter ActiveRecord::RecordInvalid`.
The encounter is not created.

**Comment by asterite** [comment]
The issue seems to be that there are existing test results in the database which have "patient_age" as a core field. This is now a core field of an Encounter. @nekron Should I add a migration to move these fields from TestResult to Encounter, and then reindex all?

**Comment by nekron** [comment]
We can remove the existing tests, there is no need to keep that information.
Because you will also need to regenerate the diagnosis for the existing encounters as they were created before that existed.
