### ISSUE TITLE
[perms] Replace text area with policy ui

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#590]
Allow the user to define the policy json using a nice ui to add statements.

Limit the flexibility of the json to the things described in the UI (ie: one resource per statement)

https://projects.invisionapp.com/d/main#/console/4103589/113464662/preview
https://projects.invisionapp.com/d/main#/console/4103589/113464672/preview
https://projects.invisionapp.com/d/main#/console/4103589/113464930/preview

**Comment by matiasgarciaisaia** [comment]
Still pending:
- [ ] Page is scrolling up when selecting other tab or adding a new one while `fixed`
- [ ] Javascript error when saving a policy with a definition but empty name/site/etc - control is not shown

**Comment by nekron** [comment]
Moved to separated tickets: #762 and #763

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre10
