### ISSUE TITLE
[perms] Generate default roles when creating institutions and sites

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#591]
- institution admin (same access as the owner)
- institution reader
- site admin
- site reader
- site technician
- site supervisor (can publish diagnoses)

**Comment by asterite** [comment]
Could you specify the JSON policy for each of the default roles?

**Comment by asterite** [comment]
Will there be 4 roles for each site in the system, and 2 for each institution in the system?

**Comment by nekron** [comment]
Keep in mind that an institution admin role should have different permissions depending on the type of institution. And Site roles won't apply for health organizations or manufacturers.

**Comment by asterite** [comment]
Started in https://github.com/instedd/cdx/tree/feature/591-default-roles . Now we just need to define the exact policies for each role and we are done.

**Comment by mmuller** [comment]
Ok in version 0.11-pre12
