### ISSUE TITLE
Site location map is broken in site view

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#594]
Found in version 0.7-pre3

1. Create a Site 'Foo' selecting any location in the locations selector
2. Save
3. In Sites, click on site 'Foo'

Obtained:
The map view is broken
![screen shot 2015-12-02 at 10 19 22 am](https://cloud.githubusercontent.com/assets/9214460/11531942/3fad56a8-98df-11e5-8a5c-6b0cff8284d7.png)

**Comment by nekron** [comment]
The referral url in the google console API was still targeting the old cdp-stg site.

**Comment by mmuller** [comment]
Ok in version 0.7-pre7
