### ISSUE TITLE
Fix air and margins in emails

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#597]
Desired:
<img width="1080" alt="screen shot 2015-12-02 at 4 41 42 pm" src="https://cloud.githubusercontent.com/assets/957103/11541942/c1d893fc-9913-11e5-9088-d6f8e04c5c1b.png">

Current:
<img width="885" alt="screen shot 2015-12-02 at 4 45 22 pm" src="https://cloud.githubusercontent.com/assets/957103/11542019/204a54ca-9914-11e5-8089-2000b16e2530.png">
Also note that the "Welcome <email>" line shouldn't be there.

The reset password email should have a similar style to the confirmation email. The white box shouldn't reach the bottom of the email:
<img width="884" alt="screen shot 2015-12-02 at 4 41 01 pm" src="https://cloud.githubusercontent.com/assets/957103/11541892/893732d8-9913-11e5-9d34-075ad4416fe0.png">

https://projects.invisionapp.com/d/main#/console/4103589/97366064/preview

**Comment by mmuller** [comment]
Ok in version 0.11-pre10
