### ISSUE TITLE
Allow the user to register a new patient

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#601]
Include:
- Name
- Birthday
- Location
- Address
- Email
- Phone

Country and State are not PII.

All fields should be stored within the core fields.

Location should behave like site location.

**Comment by bcardiff** [comment]
https://projects.invisionapp.com/d/main#/console/4103589/94153877/preview

**Comment by bcardiff** [comment]
@nekron how should be handle the patient_id when creating a patient from the web? cc: @jkicillof

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre6
