### ISSUE TITLE
Allow the user to create a patient from the new test order screen

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#604]
Display an empty screen for patient selection to avoid complexity in the sample generation.

https://projects.invisionapp.com/d/main#/console/4103589/93837627/preview

https://projects.invisionapp.com/d/main#/console/4103589/93837626/preview

**Comment by bcardiff** [comment]
@nekron the new test order screen is the one with new existing/samples and listing the whole tests. We prefer to add the patient selection to the current screen or to do the new "new test order" more similar to https://projects.invisionapp.com/d/main#/console/4103589/93837627/preview ?

**Comment by nekron** [comment]
We should implement the new design

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
