### ISSUE TITLE
Add filters to the patient index

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#606]
Allow the user to filter by:
- patient name
- patient id
- Location
- Last encounter (date)

**Comment by bcardiff** [comment]
If patient_id filter needs to handle a like/substring search we need to store the raw patient_id. We are up to do the same with patient name, yet.

@nekron heads up / confirm patient_id search should be like/substring search saving not encrypted data for this.

**Comment by spalladino** [comment]
@nekron: currently patients have location but not site, so permissions can be granted per location or institution but not site; this means that site users cannot read patients. Is this OK? Should we add a "site" to a patient?

**Comment by bcardiff** [comment]
As a follow up, permission is still per institution. Patients can be filtered by site based on the existence of a test order/encounter on that site.

**Comment by mmuller** [comment]
Ok in version 0.11-pre8
