### ISSUE TITLE
Dropdown menu of advanced filters in Tests are hidden

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#617]
Found in Version: 0.7-pre8

1. Navigate to Tests
2. Click the grey arrow button to expand advanced filters
3. Try filtering by Device

Obtained:
![screen shot 2015-12-04 at 1 59 35 pm](https://cloud.githubusercontent.com/assets/9214460/11595963/fc03d536-9a90-11e5-9852-1b9ccdc4b85c.png)

**Comment by nekron** [comment]
Duplicated of #490. Fixed in 0.7-pre9.
