### ISSUE TITLE
Setup instructions email can't be sent to recipient

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#628]
Found in version Version: 0.7-pre9

Preconditions:
There is a Device already created

1. Navigate to Devices and click on device to view its details
2. Click on SETUP
3. Click the link to 'email setup instructions to a lab operator'
4. Type the recipient's email and click SEND

Obtained: 
Nothing seems to happen, there is no confirmation message and neither does the popup window disappears. A 500 server error appears in the Console and the email is not sent.

Expected:
The email is successfully sent to the recipient.

**Comment by spalladino** [comment]
Caused by https://github.com/instedd/cdx/blob/release/0.7/app/mailers/application_mailer.rb#L2

**Comment by mmuller** [comment]
Ok in version 0.7-pre10
