### ISSUE TITLE
Wrong name for Setup Email Instructions Recipient label

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#629]
Found in version: 0.7-pre9

Preconditions:
There is a Genoscan Device already created

1. Navigate to Devices and click on device to view its details
2. Click on SETUP
3. Click the link to 'email setup instructions to a lab operator'

Obtained: 
Recipient label reads **Receiptment** instead.

**Comment by mmuller** [comment]
Ok in version 0.7-pre10
