### ISSUE TITLE
Attempting to create a Genoscan message in Playground throws an error due illegal quoting

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#632]
Found in Version: 0.7-pre9

Summary: 
The cdx playground loads a Genoscan message automatically inside Data

In CDx Playground:
1. Select Device
2. Set "Test results to generate:" to 1
3. Click on Create message

Obtained:
An error that reads "Error: Illegal quoting in line 2.". The message is not created.

**Comment by spalladino** [comment]
Fixed in 47c5d529af47231d2fdb2309713aeaa0986ab0b6

**Comment by pmallol** [comment]
Ok in Version: 0.7-pre12
