### ISSUE TITLE
Update encounter diagnosis when loading the encounter so the user can validate the automatic change

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#635]
Add a legend in the edit encounter window (in 12px italic) below the Diagnosis label that says "Each time a new test arrives, the list of conditions will be updated for you to diagnostic".
Add an additional legend for View Encounter that says: "There are new conditions that need to be reviewed".
https://github.com/instedd/cdx/issues/502#issuecomment-165522027 (Option A)

**Comment by bcardiff** [comment]
@nekron when the user that is viewing the encounter does not have edit permission, should he/she see the indication that the diagnostic is probably outdated?

**Comment by nekron** [comment]
Updated the original comment.

**Comment by mmuller** [comment]
Ok in version 0.11-pre9
