### ISSUE TITLE
Button to add things stops being clickable after scolling down the page

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#638]
Found in version Version: 0.7-pre9

Preconditions:
There are several tests uploaded, so that Tests page is scrollable 

1. Navigate to Tests
2. Scroll down the page so that the button is still visible next to the tests listing
3. Attempt clicking the add button

Obtained:
The button is not clickable anymore 
Note: this happens throughout CDx

![screen shot 2015-12-18 at 11 04 06 am](https://cloud.githubusercontent.com/assets/9214460/11898638/0e5e8a7c-a578-11e5-917f-21fa00505c76.png)

**Comment by mmuller** [comment]
Ok in version  0.7-pre11
