### ISSUE TITLE
Incorrect download link for pdf instructions in setup email

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#641]
Found in Version: 0.7-pre10

Preconditions:
There is a Device model 'foo' with instructions uploaded. 
There is a Device 'X' with model 'foo'

1. Open Device 'X' listed in Devices
2. Click the SETUP tab and the "email setup instructions to a lab operator" link
3. Type an email and hit Send
4. Open the message when it arrives and click on "Download instructions as a pdf file"

Obtained: 
A new tab opens and the link looks something similar to:
`http://cdx-stg.instedd.orghttp//s3.amazonaws.com/cdx-staging/device_models/setup_instructions/...`

**Comment by nekron** [comment]
The url is pointing to http://s3.amazonaws.com/cdx-staging/device_models/setup_instructions/000/000/008/original/b4e8714ab7283f906ca31ddc04ffc958864291d5.pdf?1450456406 but it cannot be accessed

**Comment by bcardiff** [comment]
The missing url is probably due to an old file. It seems to work in stg the upload/download. Yet, some fixes were introduced to fix dev due to 0024847

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre6
