### ISSUE TITLE
Error when trying to upload a large file in Device Model view

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#665]
Found in version 0.7-pre11

Preconditions:
There is a Device Model 'Foo'

Steps:
Go to edit the Device Model 'Foo'
Select a large file (~2.3MB) as 'Setup instructions' 
Press 'Save'

Obtained:
'413 Request Entity Too Large' error is thrown

Expected:
A validation error should be displayed

**Comment by pmallol** [comment]
Ok in Version: 0.10-pre1
