### ISSUE TITLE
Map in 'new site' form doesn't work

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#669]
When typing a region, the map doesn't show it. Clicking on the map doesn't allow the user to select a region either. Found in 0.8-pre1

**Comment by spalladino** [comment]
Fixed in 0.8 in db680c8

**Comment by mmuller** [comment]
Now in version 0.10-pre2 after typing a region, it is  displayed on the map, but after clicking on the map the region is not selected. @nekron please confirm if it is the expected behavior.

**Comment by nekron** [comment]
It is, there is no reverse geo-coding.
