### ISSUE TITLE
Sites dropdown is not being filtered by selected institution

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#672]
In several forms such as "new site", the list of sites displayed in the dropdown shows sites that are not part of the selected institution.

**Comment by nditada** [comment]
<img width="873" alt="screen shot 2016-01-05 at 12 22 28 pm" src="https://cloud.githubusercontent.com/assets/1359189/12118775/0b43f83a-b3a7-11e5-80de-098302efc358.png">

**Comment by vtiffenberg** [comment]
Couldn't find any other than site which suffered from this problem. Role is being covered by other issues (#671 and #689)

**Comment by mmuller** [comment]
Ok in version 0.10-pre2
