### ISSUE TITLE
Fix alignment issue in fixed fields in forms

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#674]
There is a misalignment between the "INSTITUTION" label and the pre-selected "Demo Institution"

<img width="571" alt="screen shot 2016-01-05 at 12 23 40 pm" src="https://cloud.githubusercontent.com/assets/957103/12118817/3db38970-b3a7-11e5-82d7-6aa414e9ef90.png">

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
