### ISSUE TITLE
Check condition codes in Epicenter manifest

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#675]
Epicenter is reporting MYCOBACTERIUM_TUBERCULOSIS, PYRAZINAMIDE, and ISONIAZID. It should report mtb, pza and inh.

<img width="537" alt="screen shot 2016-01-05 at 11 45 18 am" src="https://cloud.githubusercontent.com/assets/957103/12119004/d07024d0-b3a7-11e5-9d81-5f091f7b71a2.png">

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre4
