### ISSUE TITLE
Hide Site selection combo in device creation for a lab user

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#677]
If the user has access to only one site, hide the combo and create the device in the site in context.

**Comment by bcardiff** [comment]
This conflicts with #830. A device can be asigned to an institution without a site. Hiding the site select on creation if the user has only one site leaves out the option for not assigning it. So, how we can detect a lab user @nekron  or what we can do in this scenario?

**Comment by nekron** [comment]
We can check if the user has the ability to create another site, if he can, then is not a site user and is an institution-level admin.

**Comment by bcardiff** [comment]
So, if the current user
* can not create site
* it can only view 1 site

we want

* to not be able to create a device at the institution level
* to be able to create device in the sole site he has access to

right? @nekron

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
