### ISSUE TITLE
Editing an encounter will lead to having a duplicated sample Id as a Unified sample

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#683]
Go to an encounter reported by a test (that reported encounter_id), edit it and save it twice.

The sample is displayed as a unified sample with another sample with the same id:

<img width="1317" alt="screen shot 2016-01-05 at 1 25 57 pm" src="https://cloud.githubusercontent.com/assets/957103/12120607/41c93d1c-b3b0-11e5-994a-1da91a9f367d.png">

**Comment by nekron** [comment]
I weren't able to reproduce this bug. The closest that I got was by moving a device to a new site and reporting a test for the same sample Id and patient in the new site. When trying to edit and save the encounter it raised a validation error saying that the sample Id had already being used. And after that happened, the same error started to pop up when trying to edit a second encounter of another device in another site with the same sample Id.

After moving the device, the original test was displayed in the tests index as belonging to the second site.

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
