### ISSUE TITLE
Add medical history to the patient view page

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#695]
Add a link from there to the encounter.

**Comment by bcardiff** [comment]
@Mscebba the card-unkown image of the patient should be updated. Notice that it is also used in the device cards so, maybe we should split those cases.

**Comment by mmuller** [comment]
@nekron the link to the encounter is not clear. It would be helpful to add an arrow. (Version 0.10-pre2)

**Comment by nekron** [comment]
That "small arrow" is really necessary, let's open a new issue for that

**Comment by nekron** [comment]
Moved to #815
