### ISSUE TITLE
Implement Alere FTP client

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#706]
The client should be a process running in the background of the cdx server and that should connect to the ftp server and read the files stored there.

Allow the user to configure the ftp address (with user and password) that will be accessed by cdx to read the tests.

Provide a local ftp server, and scope the access by institution uuid (or device uuid). Don't asume the files will always be isolated. Check the device serial number before importing, as they could be multiple devices reporting to the same ftp server. I.e.: an external server.

The file name convention for Alere PIMA is:
`[device serial number]_[YYYY-MM-DD]_[HH-MM-SS]_AssayID_[#]_(Assay name).csv`
The file name convention for Alere Q is:
`[ASSAY-ID]_[INSTRUMENT-SERIAL]_[DATE-TIME].csv`
Include the file name convention as a part of the device model configuration.

The structure of the Alere PIMA csv and the setup options can be found in:
[CCG-PIMA-01-02-EN_Alere Connectivity Pack I and II Configuration Guide f....pdf](https://github.com/instedd/cdx/files/90877/CCG-PIMA-01-02-EN_Alere.Connectivity.Pack.I.and.II.Configuration.Guide.f.pdf)

The structure of the Alere Q csv can be found in:
[98_00000_TN_Result_Export_Format_for_HIV_VLWB.pdf](https://github.com/instedd/cdx/files/90895/98_00000_TN_Result_Export_Format_for_HIV_VLWB.pdf)
[98_00000_TN_Result_Export_Format_for_HIV_Detect.pdf](https://github.com/instedd/cdx/files/90896/98_00000_TN_Result_Export_Format_for_HIV_Detect.pdf)
[98_00000_TN_Result_Export_Format_for_Unknown_Assay.pdf](https://github.com/instedd/cdx/files/90899/98_00000_TN_Result_Export_Format_for_Unknown_Assay.pdf)

Build two manifests, one to parse the Alere PIMA and another for the Alere Q CSV's

**Comment by spalladino** [comment]
@nekron do we have examples of the CSV files, besides their definition?

**Comment by cisaacs01** [comment]
I can get some of these. Leave it with me.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by spalladino** [comment]
@nekron regarding the test identifier in Alere PIMA:
> Test ID
> Integer
> Constraint: Not empty.
> Value: 0 < ID <1000
> A none unique number for identifying single results on the instrument. Test IDs will be re-used on a particular instrument after the related test was deleted in the instrument’s archive. 

How should we differentiate between tests from the same device with a repeated ID?

**Comment by cisaacs01** [comment]
The way we did this previously was to also take into account the date stamp and sample ID as additional fields to be used in unique identification.

**Comment by spalladino** [comment]
Requires https://github.com/instedd/playbooks/issues/1 for deployment

**Comment by mmuller** [comment]
Ok in version 0.11-pre10

**Comment by cisaacs01** [comment]
Can you provide the test script used for this please. My own testing has showed that PIMA files set on FTP server are not picked up from by CDx.

**Comment by nekron** [comment]
As you can see in https://github.com/instedd/cdx/issues/976, we are having some troubles with this.

**Comment by cisaacs01** [comment]
You are aware that files from AlereQ are sent as ZIP files to the FTP server? Screenshot in GitHub indicates you are attempting to parse a CSV file.

**Comment by nekron** [comment]
I was not aware of that. I thought that you had sent us the files as a zip to simplify the email, not that those showed the default format.

There is no reference of the files being zipped in any of the export format documents. Can you confirm with Alere that the files are always sent as a zip?

**Comment by cisaacs01** [comment]
I used to work for Alere so i was preety certain they were. I have however, just to avoid me looking like a dick confirmed again with the current Alere team and they say that nothing has changed. Have also tested recently by exporting files from the device we have in the office.

**Comment by nditada** [comment]
Let's continue on #982
