### ISSUE TITLE
Fix randomly broken tests

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#712]
Running rspec with seed 65147 will cause `spec/models/computed_policy_spec.rb:686` to fail.

**Comment by bcardiff** [comment]
`rspec ./spec/models/computed_policy_spec.rb:686 --seed 65147` doesn't fail.
`rspec --seed 65147` does fail

One other random failing test is `spec/controllers/institutions_controller_spec.rb:28`. Blueprints seems to no be the issue :-(

**Comment by nekron** [comment]
See `rspec bisect`

**Comment by bcardiff** [comment]
`rspec ./spec/jobs/daily_demo_data_spec.rb[1:1:1,1:1:2] ./spec/models/computed_policy_spec.rb[1:6:2:1] ./spec/models/site_spec.rb[1:9:2] --seed 65147`
