### ISSUE TITLE
Fix javascript errors of device_models/_form.haml

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#714]
There is a javascript error that's being thrown in every page: `Uncaught TypeError: Cannot read property 'addEventListener' of null`

This code is in application.js:181-193, but the only page that has an element with id device_model_picture is the device_models/_form.haml

```
  // Drag Picture to an input file and preview it

  var imageLoader = document.getElementById('device_model_picture');
      imageLoader.addEventListener('change', handleImage, false);

  function handleImage(e) {
      var reader = new FileReader();
      reader.onload = function (event) {

          $('.upload-new-file img').attr('src',event.target.result);
      }
      reader.readAsDataURL(e.target.files[0]);
  }
```

If possible, try to change this to use a react component. If not, Fix the link to the file `/assets/jquery.custom-file-input.js`: include it using the tag helper and add the missing file to the repo.

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
