### ISSUE TITLE
Build the new test order page

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#721]
Add the initial menu that lets the user select to create a new test order or to create a test order from already existing tests.

https://projects.invisionapp.com/d/main#/console/4103589/126180544/preview

For the "already existing" use the current creation page.

Build a simple page for the "new test order" menu and after created go to the old view page.

https://projects.invisionapp.com/d/main#/console/4103589/93837627/preview

**Comment by bcardiff** [comment]
current screens that needs some tidy up, but are feature complete (cc: @Mscebba )

![screen shot 2016-01-20 at 5 20 50 pm](https://cloud.githubusercontent.com/assets/459923/12461958/761709c8-bf9a-11e5-8f57-beea3c6ed80d.png)

![screen shot 2016-01-20 at 5 21 24 pm](https://cloud.githubusercontent.com/assets/459923/12461966/7a4aa608-bf9a-11e5-9b67-2c6865cb48c7.png)

some of the css classes are shared among "patient's medical history"
samples list needs to be adapted, and the should be replaced with one with a remove semantic.

**Comment by mmuller** [comment]
Ok in version 0.11-pre8
