### ISSUE TITLE
Add number of elements in the top of each of the tables

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#722]
- [x] sites
- [x] devices
- [x] users
- [x] patients
- [x] logs
- [x] roles

Eg: https://projects.invisionapp.com/d/main#/console/4103589/96539136/preview

**Comment by cisaacs01** [comment]
Should be in line with the design described at https://find.plan.io/projects/cdx/files

**Comment by mmuller** [comment]
Ok in version 0.11-pre7
