### ISSUE TITLE
Style accept invitation screen

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#727]
Follow the design of the account registration screen.

![screen shot 2016-01-21 at 4 02 53 pm](https://cloud.githubusercontent.com/assets/957103/12491228/baa80a9c-c058-11e5-8862-561afbfd9122.png)

https://projects.invisionapp.com/d/main#/console/4103589/97051641/preview

**Comment by mmuller** [comment]
Ok in version 0.11-pre7
