### ISSUE TITLE
Fix site combo in roles creation

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#741]
- [ ] Allow the user to select no site at all for an institution wide role.
- [x] Pre-select the current site in context if there is one.

**Comment by vtiffenberg** [comment]
No site can be selected, and roles can be created at institution level.

The actual problem is not with the site combo but with the policy definition UI, which allows for invalid states which can not be created on the server. Will separate this into a different issue.

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
