### ISSUE TITLE
Fix overlapping filters when side navigation is expanded

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#744]
Mainly in the users screen, but all the filters will overlap if the screen is a little too small
<img width="1437" alt="screen shot 2016-02-03 at 5 32 42 pm" src="https://cloud.githubusercontent.com/assets/957103/12796247/88b345c6-ca9c-11e5-9853-ec52edab93e5.png">

**Comment by mmuller** [comment]
Ok in version 0.11-pre4
