### ISSUE TITLE
Fix vertical alignment between different kind of filters

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#745]
The text fields and select fields have their underlines at different heights.

<img width="814" alt="screen shot 2016-02-04 at 2 44 55 pm" src="https://cloud.githubusercontent.com/assets/957103/12824017/e32e8d06-cb4d-11e5-95af-323810fe4d82.png">

This happens in all the filters.

**Comment by Mscebba** [comment]
Fixed in commit:
https://github.com/instedd/cdx/commit/a8296c40b1b7513a394d3fb4060e0aa50c419a23

**Comment by mmuller** [comment]
Ok in version 0.11-pre4
