### ISSUE TITLE
Role assignment in users page is throwing an error when trying to remove a role

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#748]
<img width="1440" alt="screen shot 2016-02-04 at 3 33 46 pm" src="https://cloud.githubusercontent.com/assets/957103/12825370/b9adf1a4-cb54-11e5-85ce-b7f88c5fa1d5.png">

**Comment by vtiffenberg** [comment]
`rake policies:update_roles` needs to be run on the server

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
