### ISSUE TITLE
Keep top menu bar items fixed horizontally

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#753]
When selecting different nodes in the hierarchy, depending on the length of the names, the menu gets displaced horizontally.

**Comment by bcardiff** [comment]
On master, after f81b25d, the top navbar has 3 more items and won't fit on medium screen. Items are wrapped in the white area.

![screen shot 2016-02-17 at 1 02 36 pm](https://cloud.githubusercontent.com/assets/459923/13115527/dd3fcdd2-d576-11e5-9a4d-f0635ce6acb8.png)

**Comment by nekron** [comment]
Consider #775

**Comment by Mscebba** [comment]
Items have to be rearranged in sections. There are to many categories on header nav. Currently we have a 1580px min-width. It must be scaled down to 1330px. Most frecuently resolution today is 1366px wide.

**Comment by mmuller** [comment]
Ok in version 0.11-pre2
