### ISSUE TITLE
[perms] Fix scroll issue when selecting other tab or adding a new one while `fixed`

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#762]
Page is scrolling up when selecting other tab or adding a new one while `fixed`:
![cdx-roles-scroll](https://cloud.githubusercontent.com/assets/5470539/12859836/881b2592-cc37-11e5-94bf-c3f95fef6214.gif)

**Comment by pmallol** [comment]
Ok in Version: 0.10-pre4
