### ISSUE TITLE
[perms] Fix Javascript error when definition contains an empty statement

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#763]
[Javascript error](https://gist.github.com/matiasgarciaisaia/a60ac3b2d6af3396bf82) when definition contains an empty statement
![cdx-role-save-error](https://cloud.githubusercontent.com/assets/5470539/12859849/9c311532-cc37-11e5-9f2d-a0c94bcca8a7.gif)

**Comment by pmallol** [comment]
Ok in Version: 0.10-pre4
