### ISSUE TITLE
[device] Deleting a device leaves tests in an inconsistent state

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#764]
- [x] Add `acts_as_paranoid` to the devices
- [x] There is a validation that prevents a test to be saved if the device doesn't exist. So far so good. When a new test arrives for the same patient, the blender looks for all the older tests and tries to update them with the new patient information, but the older test cannot be saved.
- [x] Trying to open a test for a deleted device leads to a server error. See #757.

**Comment by pmallol** [comment]
Ok in Version: 0.10-pre4
