### ISSUE TITLE
Back arrow between tests for same sample generates infinite loop

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#768]
Found in Version: 0.7-pre12

Preconditions:
There is an Institution. This Institution uploaded at least two tests that were made with same [sample 1234].

As Institution Admin:
1. Navigate to Tests
2. Open [test 1] that belongs to [sample 1234]
3. Inside the tests detail view in section 'Other Tests', click on the link to open the other [test 2] made with [sample 1234]
4. Click the Back arrow to go back
5. Once back in [test 1] click again the Back arrow to go back to Tests

Obtained: 
The user is redirected to [test 2] again. If the Back arrow is clicked once more, the user gets back to [test 1], and so on.

Expected:
The user should go back to Tests eventually, after clicking the Back arrow in either [test 1] or [test 2]

**Comment by nekron** [comment]
Check that this is still an issue in 0.9

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre6
