### ISSUE TITLE
Keep Advanced filters in Tests visible when filtering by any of them

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#769]
In Version: 0.7-pre12, when filtering Tests by a Device that has no tests results uploaded yet, the page will reload and hide the Advanced filters while showing 0 Tests as a result of the filter settings.
This could lead to confusion, and it would also be useful for the user to see what are tests being filtered by.

![screen shot 2016-02-16 at 11 03 40 am](https://cloud.githubusercontent.com/assets/9214460/13078325/fb5f3274-d49c-11e5-85ac-63625909aed3.png)

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
