### ISSUE TITLE
[hiereorgs] Fix styling issues of the hierarchical navigation checkbox

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#772]
Styling issues remaining:
- [ ] Enlarge left margin next to checkbox
- [ ] Border colour for checkbox needs to be lightened
- [ ] Highlight selected location (CSS for that trampled by something else)
- [ ] Lines to the left are too short and too thin
- [ ] Line under search is black instead of light gray.

Split from #571.

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
