### ISSUE TITLE
Inviting a new user requires logged user to press enter in email input

### ISSUE THREAD

**Issue by bcardiff** [instedd/cdx#773]
When inviting user:

![screen shot 2016-02-16 at 3 59 37 pm](https://cloud.githubusercontent.com/assets/459923/13087394/6a52f67e-d4c6-11e5-8908-c894b46bd83b.png)

if the logged user press **Send**, no invitation is sent
if the logged user press **ENTER** in the email input and then **Send**, the expected invitation is sent.

The UI allows sending multiple recipient invitation, yet for single user the first steps should send the expected invite.

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre4
