### ISSUE TITLE
Role name cannot be updated

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#774]
Found in Version: 0.9-pre1

As Institution Admin
Navigate to Roles
Create a new Role named "Medical Reader" and Save
Open "Medical Reader" role and change its name to "Lab Reader"
Save

Obtained:
The user is notified of successful update but the role name is not updated
Note that changes in Role Policy are saved.

Expected:
The user is notified of successful update but the role name is updated, changing from "Medical Reader" to "Lab Reader"

**Comment by mmuller** [comment]
Ok in version 0.11-pre4
