### ISSUE TITLE
User Invitation email is not receieved

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#777]
Found in Version: 0.9-pre1

Preconditions:
There is an Institution Foo with a Site already created

As Institution Foo Admin:
1. Navigate to Users
2. Click on the envelope button to create a new 'User Invitation'
3. Choose Role and type the user email and press Enter so actually select it
4. Click the Save button to send the invitation

Obtained:
The recently invited user appears listed and its activity states that the Invitation was sent, however, the email is not received

Expected:
The user is listed properly and the email sent and received successfully

**Comment by bcardiff** [comment]
Did any email got out from stg?
The invited user did already exist in the system or it was a fresh email?

**Comment by nekron** [comment]
Confirmation emails are working. Only invites are broken.
http://poirot-stg2.instedd.org/activities/2016-02-18/cf42b274-9ece-2b39-0302-f45e1615ba32

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre3
