### ISSUE TITLE
Implicit roles throws JS error when editing

### ISSUE THREAD

**Issue by bcardiff** [instedd/cdx#779]
Go to edit a role (Institution Admin)
A JS error is thrown

@nekron, should this roles be editable at all? The sole action available should be to change their name, since the policy definition of is not supported by the UI.

**Comment by nekron** [comment]
They should. See #800.

**Comment by bcardiff** [comment]
fixed together with #799

**Comment by pmallol** [comment]
Still present in Version: 0.11-pre3

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
