### ISSUE TITLE
After updating a Site the information about its Devices is lost

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#780]
Found in version:
0.9-pre1

Preconditions:
There is a Site 'Bar'
The Site 'Bar' has a Device 'Foo'
The Device 'Foo' has Test Results
The information about the Device 'Foo' is correctly displayed under the 'Performance' tab and the 'Logs' page

Reproduce steps:
Go to edit the Site 'Bar'
Rename the Site 'Bar' and save the change
Observe the displayed data in the 'Performance'
Observe the displayed events in the 'Logs' page 

Actual result:
There are no Logs for the Device 'Foo'
There are no Tests for the Device 'Foo' in the 'Performance' tab 

![screen shot 2016-02-18 at 10 06 08 am](https://cloud.githubusercontent.com/assets/518152/13144116/4e20a2aa-d627-11e5-828b-7aae314ece17.png)

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre1
