### ISSUE TITLE
Institution name is being dropped down of the section

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#783]
- Increase the size of the placeholder to the same size of the sidebar to give it enough space.
- Hide the overflow
- Include a tooltip to display the full name

<img width="407" alt="screen shot 2016-02-18 at 10 47 12 am" src="https://cloud.githubusercontent.com/assets/957103/13145119/46323a26-d62d-11e5-897e-9c2184c4fde8.png">

**Comment by mmuller** [comment]
Ok in version 0.11-pre1
