### ISSUE TITLE
"n/a(n/a)" appears in card-detail for patients without a defined birthday

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#784]
Found in Version: 0.10-pre1

Preconditions:
There are tests results uploaded for patient "John Doe"

Navigate to Patients
Click on listed name "John Doe"

Obtained:
Inside the card-detail, below the patient's name, next to reported gender, it appears "n/a(n/a)". 

Expected: 
The patient's card shouldn't show data for unreported fields

![screen shot 2016-02-18 at 11 31 13 am](https://cloud.githubusercontent.com/assets/9214460/13147115/b90614e2-d636-11e5-80ee-b7f896e88a9f.png)

**Comment by vtiffenberg** [comment]
![screen shot 2016-02-18 at 3 29 45 pm](https://cloud.githubusercontent.com/assets/4836220/13153804/95bf0cd2-d654-11e5-8db1-38fb3a328512.png)

When viewing a test result detail, patient with n/a as name, are showing as URLs

**Comment by mmuller** [comment]
Ok in version 0.11-pre4
