### ISSUE TITLE
404 error when attempting to download log Raw Message

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#787]
Found in Version: 0.10-pre1

Preconditions:
There is an Institution with a site and a device reporting tests

1. Navigate to Logs
2. Click on 'Download' to download a raw message 

Obtained:
A 404 error `Failed to load resource: the server responded with a status of 404 (Not Found)` 

Expected: 
A csv message is successfully downloaded containing the test information

**Comment by vtiffenberg** [comment]
Should have been fixed with the commit on #751

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre1
