### ISSUE TITLE
Condition filter shows options in lowercase

### ISSUE THREAD

**Issue by vtiffenberg** [instedd/cdx#788]
Make them uppercase, as in the table underneath

**Comment by vtiffenberg** [comment]
![screen shot 2016-02-18 at 4 08 45 pm](https://cloud.githubusercontent.com/assets/4836220/13154890/ee74259c-d659-11e5-8bc2-c66903d20406.png)

Also missing uppercase in patient detail

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre7
