### ISSUE TITLE
When reviewing diagnosis in a test order fields are unaligned

### ISSUE THREAD

**Issue by vtiffenberg** [instedd/cdx#791]
1. Go to test results
2. Show as test orders (first filter)
3. Pick any test
4. Next to DIAGNOSIS: click on "There are new conditions that need to be reviewed."
5. Textarea is unstyled and fields are unaligned

**Comment by vtiffenberg** [comment]
![screen shot 2016-02-18 at 3 34 14 pm](https://cloud.githubusercontent.com/assets/4836220/13154020/9fad0bd0-d655-11e5-877a-cc37fa5d748d.png)

**Comment by mmuller** [comment]
Ok in version  0.11-pre4
