### ISSUE TITLE
Slash symbol is required in the Birthday field of the Patient view

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#792]
Found in version:
0.10-pre2

Preconditions:
There is a Patient 'Foo'
For the Patient 'Foo' the Birthday field is empty

Reproduce steps:
Go to the Patient 'Foo' view
Fill the Birthday field with '12251948'
Press 'Save'

Actual result:
The form cannot be submitted 
Slash symbol is required in the Birthday field of the Patient view

Expected result:
Slash symbol should be added automatically

![screen shot 2016-02-18 at 3 37 21 pm](https://cloud.githubusercontent.com/assets/518152/13154003/8f4db1ae-d655-11e5-9b10-9369b0cada9f.png)

**Comment by bcardiff** [comment]
Date inputs relay on user locale and we don't have a nice input for dates.
The user local force a format for input it and to render dates.

I would vote for adding later a date input control for adding the slash symbol automatically. This control should deal with different locales.

**Comment by nekron** [comment]
This will be fixed with #840 in 0.12
