### ISSUE TITLE
Patient address cannot be correctly defined

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#795]
Found in version:
0.10-pre2

Preconditions:
The Patient 'Foo' has no 'Address'

Reproduce steps:
Go to edit the Patient 'Foo'
Fill the 'Address' field with valid values for street, city, state, zip code, and country
Submit the form

Actual result:
Patient address cannot be correctly defined

Expected result:
Street, city, state, zip code, and country should be defined correctly

![screen shot 2016-02-18 at 3 58 47 pm](https://cloud.githubusercontent.com/assets/518152/13154617/923093c0-d658-11e5-950c-a8ec24320a61.png)

**Comment by nekron** [comment]
The address can be saved and stored even if it cannot be located in the map. Nevertheless, the autosuggested field should respect the entered house number and respect the floor and / or apartment number.

**Comment by nekron** [comment]
Also consider the case stated in #842.

**Comment by mmuller** [comment]
Ok in version 0.11-pre12
