### ISSUE TITLE
Link from the test to the site is targeting site show instead of site edit

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#797]
It should target site edit.

<img width="767" alt="screen shot 2016-02-18 at 4 07 11 pm" src="https://cloud.githubusercontent.com/assets/957103/13155095/c9870b36-d65a-11e5-96db-b5225731f934.png">

**Comment by vtiffenberg** [comment]
Same thing happens in the Device show page. Inside its card

**Comment by bcardiff** [comment]
I would vote for having a show that redirects to edit.

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre4
