### ISSUE TITLE
Replace the image displayed in the Patient view

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#798]
Found in version:
0.10-pre2

Preconditions:
There is a Patient 'Foo'

Reproduce steps:
Go to edit the Patient 'Foo'

Actual result:
The image displayed has a symbol '?'

Expected result:
The image included in the proposed design has a silhouette

![screen shot 2016-02-18 at 4 16 32 pm](https://cloud.githubusercontent.com/assets/518152/13155133/092b0a76-d65b-11e5-9541-495df424e0ad.png)

**Comment by nekron** [comment]
https://projects.invisionapp.com/d/main#/console/4103589/93837628/preview

**Comment by mmuller** [comment]
Ok in version 0.11-pre1
