### ISSUE TITLE
"Close" cross image showing as broken

### ISSUE THREAD

**Issue by vtiffenberg** [instedd/cdx#801]
In users invitation and user's detail pages.

**Comment by vtiffenberg** [comment]
![screen shot 2016-02-18 at 4 23 42 pm](https://cloud.githubusercontent.com/assets/4836220/13155493/c6e735d4-d65c-11e5-8209-2dbdd8a3d596.png)

**Comment by nekron** [comment]
The image is there, but it's being linked from the modal jsx without the rails helper.

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre4
