### ISSUE TITLE
Top of policies table is unstyled

### ISSUE THREAD

**Issue by vtiffenberg** [instedd/cdx#802]
It should match the rest of the models: insteadd of a grey background and light grey font, there's a small black font on white for the title.

**Comment by vtiffenberg** [comment]
![screen shot 2016-02-18 at 4 31 46 pm](https://cloud.githubusercontent.com/assets/4836220/13155752/fb2b7dfe-d65d-11e5-8957-8a1b1693be77.png)

**Comment by vtiffenberg** [comment]
It also happens with Alerts, Incidents, Alert Messages and Device Models

**Comment by mmuller** [comment]
Ok in version 0.11-pre4
