### ISSUE TITLE
Expanding or minimizing an Institution in navigation menu acts as a selection

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#803]
Found in Version: 0.10-pre2

Preconditions:
There are at least two Institutions with several sites 

1. Click on CDx logo to open the navigation menu
2. Click on the > icon to expand or to minimize items inside Institutions

Obtained: 
Institution is selected while items inside Institutions are expanded and minimized

Expected:
Clicking the > icon should only expand or minimize items belonging to an Institution

**Comment by bcardiff** [comment]
fixed, a side effect now is that the user may hide the selection in the tree view.
1. expand
2. select child
3. collapse parent

but I don't see other way

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
