### ISSUE TITLE
New alert select ones show a red cross which triggers a JS error

### ISSUE THREAD

**Issue by vtiffenberg** [instedd/cdx#804]
Hide cross and style textareas

**Comment by vtiffenberg** [comment]
![screen shot 2016-02-18 at 4 46 57 pm](https://cloud.githubusercontent.com/assets/4836220/13156255/542d3bac-d660-11e5-9184-31c72c9c2329.png)

**Comment by anthonyoleary** [comment]
this should be fixed in the latest branch: https://github.com/finddx/cdx/tree/hotfix/anamolie-alert

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre4
