### ISSUE TITLE
Device list download as CSV should match other listings

### ISSUE THREAD

**Issue by vtiffenberg** [instedd/cdx#808]
It is now a link under the table, it should be an arrow icon to the right of the counter. Like in Sites

**Comment by vtiffenberg** [comment]
![screen shot 2016-02-18 at 5 11 24 pm](https://cloud.githubusercontent.com/assets/4836220/13156747/c8b463c2-d662-11e5-850e-bd021645b539.png)

**Comment by mmuller** [comment]
Ok in version 0.11-pre4
