### ISSUE TITLE
New site form should not show grey box with stats

### ISSUE THREAD

**Issue by vtiffenberg** [instedd/cdx#809]
It should still be on edit, but should be removed from the new page.

**Comment by vtiffenberg** [comment]
![screen shot 2016-02-18 at 5 14 15 pm](https://cloud.githubusercontent.com/assets/4836220/13156816/255dc92e-d663-11e5-8fff-c4fb186d8297.png)

**Comment by pmallol** [comment]
Removed ok in Version: 0.11-pre4
