### ISSUE TITLE
Devices field in Alerts shows devices for different Institutions as well

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#816]
Found in Version: 0.10-pre2

Preconditions:
There are at least two Institutions that belong to the same user. Both have Sites and Devices.

1. Click the CDx logo to open navigation and select an Institution
2. Navigate to Alerts on top menu
3. Click the + button to create a new alert
4. Click the arrow to open the dropdown menu inside 'Devices' field

Observed:
'Devices' allows the user to select between all devices from all its Institutions. 
Note that 'Sites' field only shows sites for the selected Institution in step 1.

Expected:
'Devices' should only show those devices belonging to the selected Institution to select in its dropdown menu.

**Comment by nekron** [comment]
@anthonyoleary

**Comment by anthonyoleary** [comment]
This should be fixed in the latest branch: https://github.com/finddx/cdx/tree/hotfix/anamolie-alert

**Comment by mmuller** [comment]
Ok in version 0.11-pre4
