### ISSUE TITLE
In Device creation the validation message about FTP settings are displayed when they are not required

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#818]
Found in Version: 0.10-pre3

Reproduce steps:
Go to create a Device
Fill the form but don't select the Device Model
Save the form

Obtained:
The Device cannot be created because there is no a Device Model selected. It is correctly notified as validation message. 
Besides that the following message is displayed: '`Ftp hostname is required if any other FTP setting is present`' 

Expected:
The validation message about FTP settings should be displayed only when they are required

![screen shot 2016-02-19 at 11 53 27 am](https://cloud.githubusercontent.com/assets/518152/13178766/6d18bcaa-d6ff-11e5-8ea4-1dee8de34bb9.png)

**Comment by bcardiff** [comment]
@mmuller this seems non repro in 0.11. Can you confirm?

**Comment by vtiffenberg** [comment]
It went all the way to the other end: the error doesn't even appear when it's supposed to

**Comment by mmuller** [comment]
@bcardiff  the issue is not present in version 0.11-pre3

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
