### ISSUE TITLE
In Logs page the reprocess action throws 404 'Page not found'

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#821]
Found in version:
0.10-pre3

Preconditions:
There is a **failed** test 'Foo'

Reproduce steps:
Go to the Logs listing
For the Log relating to 'Foo' click the 'Reprocess' link 

Actual result:
404 'Page not found' is thrown

![screen shot 2016-02-19 at 2 30 29 pm](https://cloud.githubusercontent.com/assets/518152/13183374/641155b6-d715-11e5-9259-f7b42efe0de8.png)

**Comment by mmuller** [comment]
Ok in version 0.11-pre1

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre1
