### ISSUE TITLE
Replace 'Tests' with 'Test orders' in Test Orders listing

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#822]
Found in version:
0.10-pre3

Preconditions:
There is at least one Test Order

Reproduce steps:
Go to the Tests listing
Apply the filter in order to display the Test Orders listing
Observe the total count of Test Orders

Actual result:
The total count reads 'X tests'

Expected: 
The total count should be read 'X test orders'

![screen shot 2016-02-19 at 2 57 32 pm](https://cloud.githubusercontent.com/assets/518152/13184177/2a873e88-d719-11e5-8a2f-df6a0d81d0eb.png)

**Comment by pmallol** [comment]
It reads 'test results' instead of 'test orders' in Version: 0.11-pre7

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre10
