### ISSUE TITLE
Alert cannot be updated because 'Error range' value is not saved in Alert for Device Errors

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#824]
Found in Version: 0.10-pre4

1. Navigate to Alerts
2. Create new Alert as follows

> Step 1: select  ‘Device Errors’ category
> Step 2: Enter the ‘ERRORS’ value, ‘100-500’
> Step 3: Select ‘record’ field for ‘AGGREGATION TYPE’ drop down.
> Step 4: Select ‘email’ field for CHANNEL
> Step 5: Select an ‘INTERNAL RECIPIENT’ to receive alerts
> Step 6: enter text into the ‘EMAIL MESSAGE’, such as: “Hello mr {lastname}, Your {alertname} occurred”.

3. Save Alert
4. Click on recently created alert 
5. Modify 'DESCRIPTION' and click on Update Alert

Obtained:
Alert cannot be updated. A notice appears reading: `error_code : errorcode must be an integer`

Expected:
Error code "100-500" is saved and alerts can be updated successfully 

![cdx-alerts-error](https://cloud.githubusercontent.com/assets/9214460/13184878/1ae51f1e-d71d-11e5-8474-42ae8c2a13f4.png)

**Comment by anthonyoleary** [comment]
this should be fixed in the latest branch: https://github.com/finddx/cdx/tree/hotfix/anamolie-alert

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre4
