### ISSUE TITLE
Add Test Order ID to Test Order view

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#825]
Found in version:
0.10-pre3

Preconditions:
There is at least one Test Order

Reproduce steps:
Go to the Tests listing
Apply the filter in order to display the Test Orders listing
Observe the filters
Open some Test Order
Observe the data displayed in the Test Order view

Actual result:
There is a filter to find Test Orders by ID but the user cannot get that value from the UI. The Test Order ID is not included in the Test Order details.

Expected: 
The Test Order ID should be displayed in the Test Order view

![screen shot 2016-02-19 at 3 11 36 pm](https://cloud.githubusercontent.com/assets/518152/13184504/217d7bb6-d71b-11e5-897b-9a56bd942d2b.png)
![screen shot 2016-02-19 at 3 11 11 pm](https://cloud.githubusercontent.com/assets/518152/13184505/2184f3b4-d71b-11e5-8934-452a94551d1b.png)

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre7
