### ISSUE TITLE
Inconsistent state of disabled fields in created Alert

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#826]
Found in Version: 0.10-pre4

1. Navigate to Alerts
2. Create new Alert as follows:

> Step 1: select ‘Device Errors’ category
> Step 2: Enter the ‘ERRORS’ value, ‘100-500’
> Step 3: Select ‘record’ field for ‘AGGREGATION TYPE’ drop down.
> Step 4: Select ‘email’ field for CHANNEL
> Step 5: Select an ‘INTERNAL RECIPIENT’ to receive alerts
> Step 6: enter text into the ‘EMAIL MESSAGE’, such as: “Hello mr {lastname}, Your {alertname} occurred”.

3. Save Alert
4. Click on recently created alert
 
Obtained: 
Some fields appear as available to be modified but when clicked are actually disabled (e.g: AGGREGATION TYPE, AGGREGATION FREQUENCY, AGGREGATION THRESHOLD, CHANNEL, SMS PER DAY LIMIT). Same happens with disabled fields that when hovered with the mouse the mouse pointer changes as if the select combo was an activated field (e.g: SITES, DEVICES, etc).

![cdx-alerts](https://cloud.githubusercontent.com/assets/9214460/13184864/0a3d7e18-d71d-11e5-8b20-45a6190949b2.png)

**Comment by anthonyoleary** [comment]
Fixed it for the text box elements, need to find a solution for the drop downs.

**Comment by vtiffenberg** [comment]
Seems like they are all editable now. Closing

**Comment by pmallol** [comment]
Working ok in Version: 0.11-pre7
