### ISSUE TITLE
Improve the 'Result' options in 'Tests' filters

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#827]
Found in version:
0.10-pre3

Reproduce steps:
Go to the Tests listing
Expand the filter by 'Result'
Observe the values displayed as options

Actual result:
'Show all', 'positive', 'negative', and 'n/a' are displayed as options in Result filter

Expected:
'n/a' should be replaced with something like 'Not Result' 

![screen shot 2016-02-19 at 4 19 03 pm](https://cloud.githubusercontent.com/assets/518152/13186341/929e6414-d724-11e5-8301-5f0e5bf38e36.png)

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre8
