### ISSUE TITLE
Rename "Settings" page to "My Account"

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#828]
<img width="857" alt="screen shot 2016-02-19 at 4 38 58 pm" src="https://cloud.githubusercontent.com/assets/957103/13186966/5ac84174-d727-11e5-891c-0e5c66a01c4e.png">

https://projects.invisionapp.com/d/main#/console/4103589/97715347/preview

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre7
