### ISSUE TITLE
Unable to edit assigned site of device if institution has only one site

### ISSUE THREAD

**Issue by bcardiff** [instedd/cdx#830]

**Comment by bcardiff** [comment]
check 
https://github.com/instedd/cdx/commit/034f6e072e6c7d9c1f766ae8d1a4d70e1be65007#diff-bcd4183945b82d9312c7873caa2a9d0fR22

**Comment by bcardiff** [comment]
@nekron should a user be able to remove the site assigned to a device and leave it assigned just to the institution?

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre3
