### ISSUE TITLE
Move map to bottom of pages for new site or patient creation

### ISSUE THREAD

**Issue by cisaacs01** [instedd/cdx#843]
In the “New Site” screen, move the map to the bottom so that when scrolling down the map widget doesn’t “capture” the scrolling and starts zooming out rather than continue scrolling the page.

**Comment by bcardiff** [comment]
Moving maps to the bottom of the page won't effectively solve the scrolling vs. zooming issue.
The branch uses the solution proposed be http://cliffcloud.github.io/Leaflet.Sleep/ that will avoid zooming unless the user enters by a mouse move or click in the map.

**Comment by bcardiff** [comment]
Moving maps to the bottom of the page won't effectively solve the scrolling vs. zooming issue.
The branch uses the solution proposed be http://cliffcloud.github.io/Leaflet.Sleep/ that will avoid zooming unless the user enters by a mouse move or click in the map.

**Comment by mmuller** [comment]
Ok in version 0.11-pre7
