### ISSUE TITLE
Customer tree data disappears on browser back button

### ISSUE THREAD

**Issue by cisaacs01** [instedd/cdx#846]
**To create:**
Select institution with multiple sites
Select sites tab from top menu bar
Select site and enter detail view
Click browser back button

**Expected**
User is returned to site list view

**Actual**
User is returned to site list view but all data in site tree is missing

**Comment by cisaacs01** [comment]
Superseded by #863

**Comment by nditada** [comment]
@cisaacs01 actually this is different from #863. This is a bug in loading the content of the tree, not related to collapsing.

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre7
