### ISSUE TITLE
Always keep site navigator open

### ISSUE THREAD

**Issue by cisaacs01** [instedd/cdx#863]

**Comment by nditada** [comment]
@cisaacs01 can we discuss this one next Tuesday? What is the concern with allowing users to collapse that? Particularly for users that have access only to 1 site, the downside of loosing that screen real state is huge.

**Comment by cisaacs01** [comment]
Can discuss yes. Understood regarding user with access to only 1 site but for other users the navigator ensures the user is on the right site(s) to view the detail they are interested in. Much of the screen estate is taken up with unnecessary white space, almost all screens could benefit from having a reduction here and so I’m not too concerned with having the navigator open permanently.

**Comment by nditada** [comment]
Would it be ok if we defaulted to open and made sure it doesn't get closed unless the user intentionally does that? I see no harm in allowing users to collapse it.

**Comment by cisaacs01** [comment]
Ok



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by mmuller** [comment]
Ok in version 0.11-pre12
