### ISSUE TITLE
Use DOB rather than patient age in patient list view

### ISSUE THREAD

**Issue by cisaacs01** [instedd/cdx#864]
Allows easier identification of patients

**Comment by nditada** [comment]
Display this as `[date of birth]([age] y/o)`, e.g: 05/25/1990 (26 y/o)

**Comment by asterite** [comment]
@nditada Should we also rename the table header from "Age" to "DOB"?

**Comment by cisaacs01** [comment]
Yes please. Use ‘Date of Birth’ rather than the acronym.

**Comment by nditada** [comment]
+1
