### ISSUE TITLE
Tests from deleted Device still has a device link that redirects to 404 page

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#868]
Found in Version: 0.10-pre4

1. Create 'Device Foo'
2. Upload tests results with 'Device Foo'
3. Delete 'Device Foo'
4. Open a test uploaded in 2.
5. Click on link "Device Foo" in description: "Test performed on **Device Foo** by"

Obtained: 
After clicking the link for deleted device the user is redirected to a 404 error page

Expected:
Links for deleted devices should be desabled

Related to #764

**Comment by bcardiff** [comment]
This should apply also to sites. Rather than disable the link we should either:

a) display something that expose the site is deleted (strike  / grayed)
b) show the link, but upon click alert that the device/site is deleted.

**Comment by nekron** [comment]
Maybe we should have some view page to display the deleted site/device. And if it was moved (site), include a link to the new one.

**Comment by bcardiff** [comment]
Those would be far new features/filters. Can we agree to show the site in a read only with the title like : ~~Site Foo~~ (DELETED)   idem with device?  At least until @jkicillof intervene.

**Comment by nekron** [comment]
Agree.

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre4
