### ISSUE TITLE
Create manifest for Alere PIMA

### ISSUE THREAD

**Issue by cisaacs01** [instedd/cdx#869]

**Comment by nekron** [comment]
Anything in particular? The manifest is in: https://github.com/instedd/cdx/blob/master/db/seeds/manifests/alere_pima_manifest.json and it's already uploaded to the stg server.

**Comment by cisaacs01** [comment]
Sorry, was looking at http://cdx-dev.instedd.org/

Have also raised #841. FTP server should be able to be set at Institution and Site level rather than at Model.
