### ISSUE TITLE
Navigation context moves horizontally when toggling subsites selection

### ISSUE THREAD

**Issue by bcardiff** [instedd/cdx#882]
![5j8w211st3](https://cloud.githubusercontent.com/assets/459923/13291268/dc729504-daf5-11e5-976c-e5a1f127ccdc.gif)

**Comment by asterite** [comment]
The issue seems to be that the checkbox coming after the input is put inline (though it was rendered below, somehow). But when clicked, it changed. I don't know what that happened, but putting a div after the search input worked.

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
