### ISSUE TITLE
Layout issue in Add Sample

### ISSUE THREAD

**Issue by bcardiff** [instedd/cdx#884]
Maybe a style was changed to fit in other part of the app and this got broken.
They gray appear on overlay. Otherwise is looks white with the same issue

<img width="958" alt="screen shot 2016-02-24 at 12 02 03 pm" src="https://cloud.githubusercontent.com/assets/459923/13291682/6fc74524-daf7-11e5-8141-72153f220494.png">

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
