### ISSUE TITLE
[nndd] default style is unable to show legends

### ISSUE THREAD

**Issue by bcardiff** [instedd/cdx#885]
A `...` is shown as label on a first walkthrough

<img width="443" alt="screen shot 2016-02-24 at 12 03 25 pm" src="https://cloud.githubusercontent.com/assets/459923/13291748/adce7e50-daf7-11e5-9384-b1ab8f6246ce.png">

**Comment by asterite** [comment]
Now:

![screenshot 2016-02-25 16 20 51](https://cloud.githubusercontent.com/assets/209371/13331335/c55f387c-dbdb-11e5-8e75-f411aad0f488.png)

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
