### ISSUE TITLE
Remove blue style from the charts setup in nndd

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#894]
Target only btn-primary instead of just buttons in general.

<img width="1204" alt="screen shot 2016-02-25 at 11 51 17 am" src="https://cloud.githubusercontent.com/assets/957103/13323019/41693dbc-dbb6-11e5-9d74-7db7ed0dd30f.png">

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
