### ISSUE TITLE
Side navigation is being collapsed after changing the number of elements in page index

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#896]
It happens in every page index with pagination.

Check: 
- [x] patients
- [x] sites
- [x] devices
- [x] logs
- [ ] models
- [x] tests
- [x] test orders
- [x] users
- [x] alert groups
- [x] alert messages
- [x] incidents
- [x] roles
- [ ] and policies

**Comment by vtiffenberg** [comment]
@nekron : Policies and models don't have pagination at the moment. Should that be added?

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
