### ISSUE TITLE
On/off Icon not showing up in app, results in 404 error

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#897]
Found in Version: 0.11-pre3

Navigate to Settings > Roles
Click on button to create new Role

Obtained:
The switch icon in 'Delegable' is missing along with the following error in the console `GET http://cdx-stg.instedd.org/assets/ic-on-off.png 404 (Not Found)`

![screen shot 2016-02-25 at 1 43 17 pm](https://cloud.githubusercontent.com/assets/9214460/13326848/3d9237ce-dbc6-11e5-8275-84cc05a0adc2.png)

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
