### ISSUE TITLE
Filtering Patients by 'Last Encounter' shows same patient duplicated for each encounter

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#900]
Found in Version: 0.11-pre4

Preconditions:
There are encounters for same patient for each tests performed on different samples.
E.g.:
![screen shot 2016-02-26 at 9 58 07 am](https://cloud.githubusercontent.com/assets/9214460/13352931/77fa7daa-dc6f-11e5-91db-8994a14249ec.png)

Navigate to Patients and observe total count of patients
Filter by 'Last Encounter'

Obtained:
Any patient associated to several tests with encounters will appear duplicated

![screen shot 2016-02-26 at 9 45 18 am](https://cloud.githubusercontent.com/assets/9214460/13353185/4df2eec8-dc71-11e5-91dc-3371aa74db9a.png)

![screen shot 2016-02-26 at 9 45 39 am](https://cloud.githubusercontent.com/assets/9214460/13353191/576bfd8c-dc71-11e5-9a57-b1d8a2376e1d.png)

Expected:
Patients should appear only once in the Patients listing

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
