### ISSUE TITLE
Users cannot be updated

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#908]
Found in version:
0.11-pre4

Preconditions:
There is an existing User 'Foo'

Reproduce steps:
Go to the Users listing
Go to edit the User 'Foo'
Press 'Save'

Actual result:
403 (Forbidden) is thrown

Additional information:
This issue could be reproduced using the following user status:
-recently created user
-already activated account
-non activated account

**Comment by bcardiff** [comment]
The submit/cancel button affects is_active user flag. 
Assignment of the roles are persisted directly without pressing save.

The quick fix is hide the submit/cancel buttons if the logged user is unable to change the user (ie: is_active flag).

Ideally both, roles and is_active flag, should be persisted only when the save button is pressed.

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
