### ISSUE TITLE
Settings page throws server error for Site Administrators

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#917]
Found in Version: 0.11-pre4

Preconditions:
The User 'Foo' is Admin of the Site 'Bar'

Reproduce steps:
Sign in as User 'Foo'
Navigate to the Settings page

Obtained:
A server error is thrown

**Comment by vtiffenberg** [comment]
After this is deployed `rake site:add_prefix` should be run on the server

**Comment by mmuller** [comment]
Ok in version 0.11-pre7
