### ISSUE TITLE
Navigating to a patient many times ends up in duplicated requests

### ISSUE THREAD

**Issue by asterite** [instedd/cdx#918]
To reproduce:
- Open the browser's console's Network tab
- Click on "Patients" on the top bar
- Click on a patient
- Click the <- arrow to go back
- Click on a patient

Probably related to turbolinks.

![screenshot 2016-02-29 14 15 56](https://cloud.githubusercontent.com/assets/209371/13402435/01ddb286-deef-11e5-8a6a-0f39c214bdbf.png)

**Comment by bcardiff** [comment]
changing `$(document).ready(...)` to   `$(document).on('ready', ...)`  will probably fix this

**Comment by mmuller** [comment]
Ok in version 0.11-pre7
