### ISSUE TITLE
Do not count QC test types in dashboards

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#925]
Make sure that test results with "test type" "QC" are not being counted on devices dashboards (both individual and home). 

Reports already allows the user to filter by that type, so this does not apply for that page.

**Comment by bcardiff** [comment]
The QC tests in dashboard and device performance are hidden.
This also hide QC tests from alerts as a side effect.

**Comment by pmallol** [comment]
QC tests are not taken in consideration in dashboards. Working ok in Version: 0.11-pre8
