### ISSUE TITLE
The pagination controls are unaligned

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#935]
Found in Version: 0.11-pre6

Preconditions:
There is at least a Device

Reproduce steps:
Navigate to Devices index
Observe the pagination controls

Obtained: 
The pagination controls are unaligned

Additional informations:
It happens where the pagination controls are used

![screen shot 2016-03-02 at 4 17 47 pm](https://cloud.githubusercontent.com/assets/518152/13472191/83f2aa2a-e092-11e5-9d33-0dea36c910a3.png)

**Comment by nekron** [comment]
Duplicated of #910
