### ISSUE TITLE
Display quantitative results

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#941]
The test result list is not showing values for quantitative results (see attach).
<img width="516" alt="screen shot 2016-03-02 at 6 43 55 pm" src="https://cloud.githubusercontent.com/assets/1359189/13476519/f770ebd8-e0a6-11e5-8379-910e28f20291.png">

Also, the detail view should not show the "n/a" if there is no qualitative result and there IS a quantitative result (see other attach). 
<img width="999" alt="screen shot 2016-03-02 at 6 45 07 pm" src="https://cloud.githubusercontent.com/assets/1359189/13476517/f7691aca-e0a6-11e5-8069-423578d9b9fa.png">

**Comment by bcardiff** [comment]
In the table we show the qualitative result with either one of the following state (or none icon as shown in your initial comment)

![screen shot 2016-03-03 at 4 51 37 pm](https://cloud.githubusercontent.com/assets/459923/13507910/a40f0584-e163-11e5-9405-c606b724b493.png)

Those states are: positive, negative and indeterminate. 
When n/a is the associated value, no icon is shown.

@nditada maybe you want @jkicillof to point how qualitative and quantitive results should leave together. Both in the table, in the details page and when editing the test order's diagnosis. As far I can tell we can have none, either or both in the same condition.

**Comment by nekron** [comment]
@nditada @cisaacs01 We were talking this morning with @bcardiff and @jkicillof and we decided to include a separated column for the quantitative results, but the problem is now the name of the column.

We were wondering if there is a different way of referring to "Quantitative Results" and "Qualitative Results". Ideally we would like to find a more technical name or more common name for the technician that will be using the app.

**Comment by cisaacs01** [comment]
Quantitative and Qualitative are fine here. Used universally.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by nekron** [comment]
@bcardiff When n/a is the associated value, the condition should not be displayed in the qualitative column.

**Comment by pmallol** [comment]
Unable to verify until #976 is fixed

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre13
