### ISSUE TITLE
Patient without name are displayed as url in test result page

### ISSUE THREAD

**Issue by bcardiff** [instedd/cdx#945]
![screen shot 2016-03-04 at 3 18 40 pm](https://cloud.githubusercontent.com/assets/459923/13536063/820a7680-e21c-11e5-8bce-0355175be3ca.png)

We could render "(unknown name)".
The patient need to be linked since there might be other information from the test result coming along as DOB, Age, gender, etc.

found in : 0.11-pre-6

**Comment by pmallol** [comment]
Version: 0.11-pre7
![screen shot 2016-03-08 at 12 38 01 pm](https://cloud.githubusercontent.com/assets/9214460/13606427/b0b64d9a-e52a-11e5-9670-e510f9c432d0.png)
