### ISSUE TITLE
Unify the list of possible result values of test results and encounters

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#946]
- [x] Add `indeterminate` to the list of possible test result values.
- [x] Use the list of test result values to populate the possible diagnostic values.
- [x] Use the logic of how to merge the `n/a` results for the `indeterminate` results.

**Comment by nekron** [comment]
Also see #827

**Comment by pmallol** [comment]
There are some issues regarding "indeterminate" results, refer to tickets #965, #966

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre10
