### ISSUE TITLE
Tests can not filtered by 'Encounter ID'

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#947]
Found in Version: 0.11-pre6

Reproduce steps:
Navigate to Tests index
Select the 'Tests' option from 'Display as'
Fill the 'Encounter ID' field
Observe the Tests listing

Obtained:
Nothing happens
The Tests listing was not filtered by 'Encounter ID'

Expected:
Tests should be filtered by 'Encounter ID'

![screen shot 2016-03-07 at 11 21 38 am](https://cloud.githubusercontent.com/assets/518152/13572013/cb918622-e456-11e5-9d7c-7eb826735c85.png)

**Comment by vtiffenberg** [comment]
We decided that the expected behaviour was that that particular filter should not be shown in the Tests view, only in the Test Order view.

**Comment by mmuller** [comment]
Ok in version 0.11-pre7
