### ISSUE TITLE
Server error when accessing certain encounters

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#953]
Found in Version: 0.11-pre6

Reproduce steps:
Navigate to http://cdx-stg.instedd.org/encounters/2b9dd133-dce3-6acb-16d5-f319d77d7702?context=1f5b45d5-81d2-e63a-35ce-378a59acdcbb

Obtained:
A server error is thrown

Poirot activity:
http://poirot-stg2.instedd.org/activities/2016-03-08/c41551f5-63be-7ba4-f4a7-3614f1b0571c

Additional info:
The error is not thrown when accessing other encounters

**Comment by nekron** [comment]
This encounter exists in elasticsearch, but not in the database, and it doesn't have any tests.
