### ISSUE TITLE
Text areas and 'Cancel' button are not inline with labels in Alert Groups

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#954]
Found in Version: 0.11-pre7

1. Navigate to Settings and click on Alert Groups
2. Click on button to create new alert
3. Observe fields EMAIL/SMS message and CANCEL button

Obtained:
The text areas are not inline with the labels. Also the 'Cancel' button appears below the 'Create Alert' button

![screen shot 2016-03-08 at 2 44 50 pm](https://cloud.githubusercontent.com/assets/9214460/13610427/69085670-e53c-11e5-8984-2957e2e244f1.png)

Expected:
Textareas and cancel button should maintain same design and disposition as the rest of the app

**Comment by anthonyoleary** [comment]
Hi,It looks fine on my browser [chrome on Mac laptop], would it be possible to retest. Thank you.
![screen shot 2559-03-09 at 17 59 22](https://cloud.githubusercontent.com/assets/1208548/13645043/e625a5b0-e620-11e5-8162-c903875567f2.png)
![screen shot 2559-03-09 at 17 59 22](https://cloud.githubusercontent.com/assets/1208548/13645048/ebbdf554-e620-11e5-9694-2ce3101447a4.png)

**Comment by nekron** [comment]
This happens for screens smaller than 1900px wide. We are aiming for a standard minimum width of 1330px.

**Comment by nekron** [comment]
Also the **Create Alert** and **Cancel** buttons should be aligned to the left with the rest of the labels.

And they should say **Save** and **Cancel**, to match the rest of the application:

<img width="412" alt="screen shot 2016-03-09 at 3 27 37 pm" src="https://cloud.githubusercontent.com/assets/957103/13645798/7bff7fea-e60b-11e5-9847-863e301bbcbe.png">

**Comment by anthonyoleary** [comment]
I was able to simulate and fix this. I will do a pull request today on it.

**Comment by mmuller** [comment]
Ok in version 0.11-pre12
