### ISSUE TITLE
Link from the Site to the Tests doesn't preselect the current Site

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#955]
Found in Version: 0.11-pre7

Preconditions:
There are some Tests for the Site Foo

Reproduce steps:
Navigate to the edit view of the Site Foo
The dashboard shows the total count of Tests, Devices and Users
Click on the total count of Tests

Obtained:
The Tests listing is displayed but they are not filtered by Site

Expected:
The Tests listing doesn't include a filter by Site but the link from the Site to the Tests should preselect the current Site

Additional info:
This issue can be reproduced with Tests, Devices and Users

![screen shot 2016-03-09 at 10 38 18 am](https://cloud.githubusercontent.com/assets/518152/13636903/19e13308-e5e3-11e5-9f73-2f931ed80eb4.png)
![screen shot 2016-03-09 at 10 37 10 am](https://cloud.githubusercontent.com/assets/518152/13636902/19e141b8-e5e3-11e5-93e2-b457509e29ef.png)

**Comment by anthonyoleary** [comment]
anthony is looking at this.

**Comment by anthonyoleary** [comment]
cannot reproduce it.

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre13
