### ISSUE TITLE
Allow the user to select a patient when creating test orders for already reported tests

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#958]
Right now the patient is automatically selected from the data stored in the samples and tests.

Allow the user to select a patient before creating an encounter for a list of reported tests.

**Comment by nditada** [comment]
Consider the case that the samples added to the test order might already have a patient associated

**Comment by nekron** [comment]
Also keep in mind #984.

**Comment by mmuller** [comment]
Ok in version 0.12-pre2
