### ISSUE TITLE
Filters are not applied when processing the CSV

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#959]
Found in Version: 0.11-pre7

Preconditions:
There is at least two Devices
'Device Foo' belongs to the 'Device Model Foo'
'Device Bar' belongs to the 'Device Model Bar'

Reproduce steps:
Navigate to the Devices listing
Expand the 'Model' filter
Select 'Device Model Foo'
Observe the Devices listing
Download the listing as CSV
Observe the Devices included in the CSV

Obtained:
'Device Foo' and 'Device Bar' are included in the CSV

Expected:
The CSV should contain the items included in the Devices listing

Additional information:
This issue can be reproduced when processing a CSV from the following listing: **Users, Devices, Sites**.
CSV processing works fine for the Tests listing

**Comment by vtiffenberg** [comment]
- [ ] Sites
- [ ] Devices
- [ ] Users

**Comment by mmuller** [comment]
Ok in version 0.11-pre9
