### ISSUE TITLE
Alerts are being activated with QC tests

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#962]
In Version: 0.11-pre8

Preconditions:
There is a GeneXpert device activated
There is also an Alert group already configured for Device Errors ranging from 500 to 700

1. Upload the following QC test:

```
{
  "event": {
    "result": "MTB DETECTED MEDIUM|Rif Resistance NOT DETECTED",
    "assay_name": "MTB-RIF Assay",
    "sample_ID": "A-12347",
    "system_user": "JaneDoe",
    "device_serial_number": "123456",
    "end_time": "2016-03-09T20:08:41-05:00",
    "start_time": "2016-03-09T20:08:41-05:00",
    "event_id": "76B4AFBA09A143718CED4767ADS4EAE7",
    "test_type": "1",
    "error_code":"502"
  }
}
```

Obtained:
An alert message is sent to the recipient's mail.

Expected:
No alert emails should be triggered by QC tests

**Comment by pmallol** [comment]
Refer to comment:
https://github.com/instedd/cdx/issues/925#issuecomment-191422905

**Comment by nekron** [comment]
This should've been fixed by https://github.com/instedd/cdx/commit/561e335c2e29aa7c4074878ef468c58aa107e292

**Comment by anthonyoleary** [comment]
I just created a pull request for a fix. https://github.com/instedd/cdx/pull/971/files.

Tested in api/playground:     
"test_type": "0"  - generates an alert,
 "test_type": "1 - does not generate an alert.

**Comment by pmallol** [comment]
Still present in Version: 0.11-pre10

**Comment by mmuller** [comment]
Ok in version 0.11-pre12
