### ISSUE TITLE
Error test result belonging to GeneXpert device appears as "N/a"

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#965]
Found in Version: 0.11-pre8

Preconditions:
There is a GeneXpert device already created

1. Upload the following test:
```
{
  "event": {
    "result": "ERROR",
    "assay_name": "MTB-RIF Assay",
    "sample_ID": "12353",
    "system_user": "JaneDoe",
    "device_serial_number": "123456",
    "end_time": "2016-03-09T20:08:41-05:00",
    "start_time": "2016-03-09T20:08:41-05:00",
    "event_id": "76B4AFBA09FR43718CED4767ADS4EIE8",
    "test_type": "0"
  }
}
```
2. Navigate to Tests and filter by sample_ID
3. Click on test to see its details

Obtained:
The result for assays "MTB" and "RIF" appears as 'N/a'
![screen shot 2016-03-10 at 4 11 37 pm](https://cloud.githubusercontent.com/assets/9214460/13681175/d1f249da-e6da-11e5-9665-62e5e7bfb275.png)

Expected:
Results should appear as Error

**Comment by nekron** [comment]
This test should have a `Status: Error` field. In the example, this should be displayed along with the ID and Start Time.

If the test is successful, the Status is Success.

**Comment by vtiffenberg** [comment]
The result corresponding to each assay should be n/a, that's not incorrect. What was incorrect was that the "status" of the test was missing, which now shows the expected "error"

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre10
