### ISSUE TITLE
Indeterminate test result belonging to GeneXpert device appears as "N/a"

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#966]
Found in Version: 0.11-pre8

Preconditions:
There is a GeneXpert device already created

1. Upload the following test:
```
{
  "event": {
    "result": "Rif Resistance INDETERMINATE",
    "assay_name": "MTB-RIF Assay",
    "sample_ID": "12356",
    "system_user": "JaneDoe",
    "device_serial_number": "123456",
    "end_time": "2016-03-09T20:08:41-05:00",
    "start_time": "2016-03-09T20:08:41-05:00",
    "event_id": "76B4AFBA09FR44718CED4767ADS4EIE8",
    "test_type": "0"
  }
}

```
2. Navigate to Tests and filter by sample_ID
3. Click on test to see its details

Obtained:
The result for assays "MTB" and "RIF" appears as 'Negative' and the user cannot filter test by 'Result: Indeterminate'.

Expected:
Results should appear as Indeterminate.

**Comment by vtiffenberg** [comment]
We need to add Indeterminate to the GeneXpert manifest

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre10
