### ISSUE TITLE
Allow the user to type units in the quantitative result of a test order

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#968]
Right now the server is only allowing for the simbols +  and - to allow for numeric positive and negative values. Allow the user to write things like "400 cells/mm3".

**Comment by nditada** [comment]
Per conversation with Chris: Not needed for now, labs won't even need to type for a number manually.

**Comment by nekron** [comment]
This is for the diagnostic in the test order.

Regardless of the result provided by the device, we need to store that result in the diagnostic. This is needed to allow that result to be saved while keeping the units in the process.

**Comment by nekron** [comment]
If we don't do this, the quantitative result text will be trimmed at the moment of saving the diagnostic.

**Comment by nekron** [comment]
This was fixed along with #1016.

**Comment by pmallol** [comment]
As for Version: 0.11-pre13, empty 'Quant.' input field in a Test Order does not allow a user to type letters. 
Also, if a Test Order is generated from an uploaded test and the 'Quant.' field is already filled out with LOW/MEDIUM/HIGH (as a result of a GeneXpert MTB test), when clicked to edit it, the field is erased and cannot be filled out again.

**Comment by mmuller** [comment]
Ok in version 0.11-pre15.
Now strings can be saved as Quant values.
