### ISSUE TITLE
Issues with users with permissons from different instittutions

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#974]
Found in Version: 0.11-pre9

Preconditions:
There are two institutions [Inst A], [Inst B]

As [Inst A] admin:
1. Navigate to Users 
2. Invite user 'foo@mail.com' and assign role: "Institution [Inst A] Admin"

As [Inst B] admin:
1. Navigate to Users 
2. Invite user [foo@email.com] and assign role: "Institution [Inst B] Admin"
3. Click on user [foo@email.com] 

Obtained:
Both Institution Admins can see user [foo@email.com] 's permissions for other institutions. Also, clicking on user [foo@email.com] redirects to a 403 error. 
![screen shot 2016-03-16 at 3 55 21 pm](https://cloud.githubusercontent.com/assets/9214460/13825086/bc1f7fa6-eb8f-11e5-9e5c-ff652b1fa172.png)

Expected:
Institution Admins should see permissions of its users belonging **only** to the same Institution. They should also be able to access user's details to change, delete or add permissions.

**Comment by mmuller** [comment]
Ok in version 0.12-pre2
