### ISSUE TITLE
Tests can not be uploaded via FTP

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#976]
Found in version:
0.11-pre10

Preconditions:
There is a Device 'Foo' (device_id:67 in this test)
'Foo' belongs to 'Alere Q' Model

Reproduce steps:
Upload a new Test via FTP

Actual result:
The Test is not displayed in the web app

Logs details:
http://poirot-stg2.instedd.org/activities/2016-03-16/9433ea2a-fa78-2381-59df-11895adc68a1

![screen shot 2016-03-16 at 5 38 05 pm](https://cloud.githubusercontent.com/assets/518152/13827966/f6f99b44-eb9d-11e5-996c-27361dd18c06.png)
![screen shot 2016-03-16 at 5 35 38 pm](https://cloud.githubusercontent.com/assets/518152/13827968/f6fb75ea-eb9d-11e5-8395-3aa2b9094b7a.png)
![screen shot 2016-03-16 at 5 19 12 pm](https://cloud.githubusercontent.com/assets/518152/13827969/f6fde0d2-eb9d-11e5-9e62-22eb2a32b646.png)

**Comment by cisaacs01** [comment]
You are aware that files from AlereQ are sent as ZIP files to the FTP server? Screenshot in GitHub indicates you are attempting to parse a CSV file.

**Comment by nekron** [comment]
Let's keep this conversation in #706. This issue is related to the bug when trying to establish a connection with the ftp server.

We can always open a new ticket to implement the csv parsing if we confirm that's needed.

**Comment by mmuller** [comment]
Now in version 0.11-pre12 the following error is obtained: 
http://poirot-stg2.instedd.org/activities/2016-03-30/a2d055a6-d5a7-188c-dbbc-5332d6def811

**Comment by nekron** [comment]
It would be useful to have a button somewhere to reset the list of failed files, so a failing file can be reprocessed without having to go to the database and delete the ftp monitor log manually.

**Comment by mmuller** [comment]
Tests for Alere Q are correctly uploaded in version 0.11-pre13
