### ISSUE TITLE
Long results appear incomplete in tests listing

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#978]
Found in Version: 0.11-pre10

Preconditions:
There are several tests uploaded corresponding to different assays and with different results

1. Navigate to Tests

Observed:
Results such as "MYCOBACTERIUM_TUBERCULOSIS" appear incomplete under 'Results' column 

![screen shot 2016-03-17 at 1 10 58 pm](https://cloud.githubusercontent.com/assets/9214460/13853572/0970031e-ec46-11e5-8fe0-2eeac863072d.png)

**Comment by nekron** [comment]
Fix Epicenter manifest to report conditions using their abbreviated names.

**Comment by nekron** [comment]
The manifest is already fixed, those tests were processed with an older version of the manifest.

Please check that this issue is fixed for the new tests.

**Comment by pmallol** [comment]
Still present after changes on manifests

**Comment by mmuller** [comment]
Ok in version 0.11-pre12
