### ISSUE TITLE
Enhancements in email for alert notification

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#981]
As for Version: 0.11-pre10, this is how emails for alert notification look like:
![screen shot 2016-03-17 at 1 17 05 pm](https://cloud.githubusercontent.com/assets/9214460/13854092/9baa843c-ec48-11e5-8978-8ad0c21d758e.png)

Observed:
The CDx logo is missing and also the description does not make sense: "Alert occured [Alert Group name]".

Note that: "There's an error" correspond to the EMAIL MESSAGE set for that alert group

**Comment by mmuller** [comment]
The CDX logo is still missing in version 0.11-pre12

![screen shot 2016-04-01 at 10 58 39 am](https://cloud.githubusercontent.com/assets/518152/14209343/143c63a4-f7fa-11e5-8819-3d4e186c9d9c.png)

**Comment by anthonyoleary** [comment]
Anthony is working on this.

**Comment by anthonyoleary** [comment]
I tested it locally and it was fine. Would it be possible to see what the image url is?

the code for it is:  = image_tag "cdx-logo-med.png"   
same as used in other parts of the code.

**Comment by mmuller** [comment]
@anthonyoleary The URL is pointed to a local file instead of pointing to 'cdx-stg.instedd.org'
The current URL (```http://localhost:3000/assets/cdx-logo-med-bb543e72194c124bac5c437523efab5b.png```) should be replaced with: ```http://cdx-stg.instedd.org/assets/cdx-logo-med-bb543e72194c124bac5c437523efab5b.png```

**Comment by anthonyoleary** [comment]
@mmuller  , hi, the problem with http://cdx-stg.instedd.org/assets/cdx-logo-med-bb543e72194c124bac5c437523efab5b.png is that for the next deployment the fingerprint  bb543e72194c124bac5c437523efab5b might be different. We do not have an absolute url . But i think the current solution would be fine , for example, if deployed to http://cdx-stg-testxx.instedd.org , then the email url should contain this url not a local url?

**Comment by nekron** [comment]
Of course, nobody is asking to target the specific fingerprint version.

The problem there is that the helper in the email is setting the host to localhost instead of targeting cdx-stg.instedd.org as the rest of the app does.

**Comment by anthonyoleary** [comment]
I see the server setting under config/deploy/production.rb.  Because I did not deploy the build I never noticed it before. I will look at using it now [test in development moe first].

**Comment by anthonyoleary** [comment]
The solution seems to be in config/environments/production.rb  add,  config.action_mailer.default_url_options = { host: 'cdp-stg.instedd.org' }  . But has the missing logo image also happened for the other email templates such as device_mailer?   they both seem to use the layouts/mailer.tml.haml file.   I just don't want to change production.rb and risk breaking anything, unless QA is there to add this line and test it.

**Comment by nekron** [comment]
Other emails seems to be fine. I'll take a look at that config.

<img width="1236" alt="screen shot 2016-04-19 at 5 50 16 pm" src="https://cloud.githubusercontent.com/assets/957103/14655126/48ce2c0e-0657-11e6-9d76-d34e6f05b188.png">

**Comment by nekron** [comment]
`Settings.host` properly targets `"cdx-stg.instedd.org"` and that config is already set up to target that host:
```
irb(main):006:0> Rails::configuration.action_mailer.default_url_options
=> {:host=>"cdx-stg.instedd.org"}
```

**Comment by nekron** [comment]
The sidekiq process was running inside a different container, without the settings.local.yml volume override, so when the alert email was sent from inside that separated process, the Settings.host was the default host.
