### ISSUE TITLE
Test count conflict between Tests Menu and site detail view

### ISSUE THREAD

**Issue by cisaacs01** [instedd/cdx#983]
**Preconditions**
Site is created and has multiple test results

**Recreate**
Navigate to WHO institution / Buenos Aires Lab in site tree (turn off subsite selection)
Navigate to Tests menu - observe 3 tests with clear filters
Navigate to Sites menu and select Buenos Aires Lab
Observe test count showing as only 2

**Expected**
Test count in Test menu and Site detail to be the same

**Comment by nekron** [comment]
There was an indexing problem due to a wrong test from an older cdx version. Triggering a reindex solved the problem.
