### ISSUE TITLE
Add ability to change patient selection when creating new test order

### ISSUE THREAD

**Issue by cisaacs01** [instedd/cdx#984]
Currently if patient is selected during new test order process there is no way the user can change the patient if patient selection was made by mistake

**Comment by nditada** [comment]
@cisaacs01 would it be ok if the context of the test order that is being created is lost if the user needs to replace the current patient with a new one? It would be tricky to keep the state of the unsaved test order while the user goes to create a new patient.

**Comment by nditada** [comment]
Per conversation with @cisaacs01: All we need for now is to change the selected patient for another patient search result.

**Comment by mmuller** [comment]
Ok in version 0.12-pre2
