### ISSUE TITLE
Resources selector in Roles definition style looks broken

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#989]
Found in Version: 0.11-pre10

1. Navigate to Roles in Settings
2. Click the button to create a new role
3. Select 'Device' in Type option
4. Choose 'All devices except' in Resources 

![screen shot 2016-03-18 at 12 59 53 pm](https://cloud.githubusercontent.com/assets/9214460/13883687/58809a5e-ed09-11e5-861d-38542f894b2d.png)

Observed:
- There is a light-grey border that appears between the 'All devices except' and the input selector. 
- When a device is searched and selected it appears without any style and with a light blue X right next to it.
- There is also a light-grey border that gets drawn under the selector that overlays with the next radio button for 'Only some devices'

Expected:
![screen shot 2016-03-18 at 12 56 59 pm](https://cloud.githubusercontent.com/assets/9214460/13883605/f35d561c-ed08-11e5-9556-408ddec5aa2d.png)

**Comment by nekron** [comment]
Duplicated of #898
