### ISSUE TITLE
Option to delete policy missing in custom new Role

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#991]
Found in Version: 0.11-pre10

As Institution Admin:
1. Navigate to Roles inside Settings
2. Click button to create a new Role
3. Add a policy for type Institution and another one for Site

Observed:
There is no option to delete a policy added
![screen shot 2016-03-18 at 4 16 46 pm](https://cloud.githubusercontent.com/assets/9214460/13889490/9094a004-ed25-11e5-821d-91257ac125a5.png)

Expected:
There should be an X button next to each policy to delete it
![screen shot 2016-03-18 at 4 07 06 pm](https://cloud.githubusercontent.com/assets/9214460/13889507/aa57aae0-ed25-11e5-82d7-40b43adaba89.png)

**Comment by mmuller** [comment]
Ok in version 0.11-pre12
