### ISSUE TITLE
Rename 'Last Encounter' filter to 'Last Test Order' in Patients listing

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#994]
Found in version:
0.11-pre10

Reproduce steps:
Navigate to the Patients listing
Observe the Filters name
Observe the table headers

Actual result:
There is a filter 'LAST ENCOUNTER'
There is a header 'LAST ENCOUNTER'

Expected:
'LAST ENCOUNTER' should be replaced with 'LAST TEST ORDER'

![screen shot 2016-03-21 at 12 18 20 pm](https://cloud.githubusercontent.com/assets/518152/13923356/140bb5fe-ef5f-11e5-956a-6c941e8e779d.png)

**Comment by anthonyoleary** [comment]
anthony:easy fix, did a pull request for it.

**Comment by mmuller** [comment]
Ok in version 0.11-pre15
